// Oxford 3000, уровень B2: 835 единиц (слово + часть речи) в тематических блоках. Источник списка и уровней —
// tools/oxford-3000.json; проверка: node tools/program-check.js B2. Уточнение (6-й элемент) есть только у значений,
// которые Oxford разделяет (rest|n|relax). practice — дополнительные примеры и сочетания, confusables — близкие пары.
// Формат записи: [слово, перевод, часть речи, пример, перевод примера, уточнение?]
const OXFORD_B2 = {level:"B2", blocks:[
{id:"b2-health", title:"Здоровье и медицина", words:[
["cancer","рак (болезнь)","n","Smoking can cause cancer.","Курение может вызвать рак."],
["infection","инфекция","n","The wound became infected and the infection spread.","Рана воспалилась, и инфекция распространилась."],
["bacteria","бактерии","n","Bacteria can cause disease.","Бактерии могут вызывать болезни."],
["cell","клетка (организма); камера","n","The human body is made of cells.","Тело человека состоит из клеток."],
["organ","орган","n","The heart is a vital organ.","Сердце — жизненно важный орган."],
["lung","лёгкое","n","Smoking damages the lungs.","Курение вредит лёгким."],
["nerve","нерв","n","The nerve was damaged in the accident.","Нерв был повреждён в аварии."],
["breast","грудь (женская)","n","Breast cancer can be treated if found early.","Рак груди излечим, если обнаружен рано."],
["heel","пятка; каблук","n","My heel hurts after running.","После бега у меня болит пятка."],
["wound","рана","n","The wound is healing slowly.","Рана заживает медленно."],
["wound","ранить","v","Two soldiers were wounded.","Двое солдат были ранены."],
["cure","лечить, исцелять","v","This medicine can cure the disease.","Это лекарство может вылечить болезнь."],
["cure","лекарство, средство","n","There is no cure for the common cold.","От простуды нет лекарства."],
["recover","выздоравливать, восстанавливаться","v","She recovered quickly after the operation.","Она быстро восстановилась после операции."],
["surgery","хирургия, операция","n","He needs surgery on his knee.","Ему нужна операция на колене."],
["therapy","терапия, лечение","n","She is having therapy for her back.","Она проходит лечение спины."],
["vitamin","витамин","n","Oranges are rich in vitamin C.","Апельсины богаты витамином C."],
["pregnant","беременная","adj","She is six months pregnant.","Она на шестом месяце беременности."],
["unconscious","без сознания","adj","He was unconscious after the fall.","После падения он был без сознания."],
["conscious","в сознании; осознающий","adj","The patient is conscious now.","Пациент сейчас в сознании."],
["depressed","подавленный, в депрессии","adj","She felt depressed after losing her job.","После потери работы она была подавлена."],
["depressing","угнетающий","adj","The news was depressing.","Новости были удручающими."],
["blind","слепой","adj","The old dog is almost blind.","Старый пёс почти слепой."],
["psychology","психология","n","She studies psychology.","Она изучает психологию."],
["psychologist","психолог","n","He talked to a psychologist.","Он поговорил с психологом."],
["hurt","боль, обида","n","The hurt in her voice was clear.","В её голосе явно слышалась обида."],
["shock","шок, потрясение","n","The news came as a shock.","Новость стала потрясением."],
["shock","шокировать","v","His words shocked everyone.","Его слова всех шокировали."],
["shocked","потрясённый","adj","I was shocked by the price.","Я был потрясён ценой."]
]},
{id:"b2-feelings-2", title:"Чувства и характер", words:[
["anger","гнев","n","He could not hide his anger.","Он не мог скрыть свой гнев."],
["anxious","тревожный, обеспокоенный","adj","She is anxious about the exam.","Она волнуется из-за экзамена."],
["ashamed","пристыженный","adj","I am ashamed of what I said.","Мне стыдно за то, что я сказал."],
["shame","стыд; жалость","n","It is a shame you cannot come.","Жаль, что ты не можешь прийти."],
["desperate","отчаянный","adj","He was desperate for money.","Он отчаянно нуждался в деньгах."],
["delighted","очень довольный","adj","We were delighted with the results.","Мы были в восторге от результатов."],
["delight","радость, восторг","n","To my delight, she said yes.","К моей радости, она согласилась."],
["delight","радовать","v","The show delighted the children.","Шоу привело детей в восторг."],
["joy","радость","n","Her face was full of joy.","Её лицо светилось радостью."],
["enthusiasm","энтузиазм","n","She works with enthusiasm.","Она работает с энтузиазмом."],
["enthusiastic","восторженный, полный энтузиазма","adj","He is enthusiastic about the plan.","Он в восторге от плана."],
["impatient","нетерпеливый","adj","Do not be so impatient!","Не будь таким нетерпеливым!"],
["patient","терпеливый","adj","Be patient, the bus will come.","Наберись терпения, автобус придёт."],
["sympathy","сочувствие","n","I have no sympathy for him.","Я ему не сочувствую."],
["courage","смелость, мужество","n","It takes courage to say no.","Нужна смелость, чтобы сказать «нет»."],
["confidence","уверенность","n","She has a lot of confidence.","Она очень уверена в себе."],
["convinced","убеждённый","adj","I am convinced that he is right.","Я убеждён, что он прав."],
["willing","готовый, согласный","adj","She is willing to help.","Она готова помочь."],
["sincere","искренний","adj","Please accept my sincere apologies.","Примите мои искренние извинения."],
["wise","мудрый","adj","My grandfather is a wise man.","Мой дедушка — мудрый человек."],
["aggressive","агрессивный","adj","The dog became aggressive.","Собака стала агрессивной."],
["dishonest","нечестный","adj","It was dishonest of him to lie.","С его стороны было нечестно лгать."],
["evil","злой","adj","The film has an evil character.","В фильме есть злой персонаж."],
["evil","зло","n","Good will win over evil.","Добро победит зло."],
["humour","юмор","n","She has a good sense of humour.","У неё хорошее чувство юмора."],
["humorous","юмористический","adj","He gave a humorous speech.","Он произнёс юмористическую речь."],
["tough","трудный; жёсткий, крепкий","adj","It was a tough decision.","Это было трудное решение."],
["emotional","эмоциональный","adj","She gets emotional at weddings.","На свадьбах она становится эмоциональной."],
["lively","живой, оживлённый","adj","The market was lively.","На рынке было оживлённо."]
]},
{id:"b2-behaviour", title:"Поступки и отношения", words:[
["blame","винить","v","Do not blame me for your mistakes.","Не вини меня в своих ошибках."],
["blame","вина","n","She took the blame for the accident.","Она взяла вину за аварию на себя."],
["accuse","обвинять","v","He accused her of lying.","Он обвинил её во лжи."],
["forgive","прощать","v","I forgive you for being late.","Я прощаю тебе опоздание."],
["regret","сожалеть","v","I regret leaving so early.","Я жалею, что ушёл так рано."],
["regret","сожаление","n","I have no regrets.","Я ни о чём не жалею."],
["praise","хвалить","v","The teacher praised her work.","Учитель похвалил её работу."],
["praise","похвала","n","He received a lot of praise.","Он получил много похвал."],
["reward","награда, вознаграждение","n","There is a reward for finding the dog.","За находку собаки полагается вознаграждение."],
["reward","вознаграждать","v","She was rewarded for her hard work.","Её вознаградили за усердную работу."],
["deserve","заслуживать","v","You deserve a holiday.","Ты заслуживаешь отпуск."],
["offend","обижать, оскорблять","v","I did not mean to offend you.","Я не хотел тебя обидеть."],
["offensive","оскорбительный","adj","His comments were offensive.","Его замечания были оскорбительными."],
["offence","правонарушение; обида","n","Parking here is an offence.","Парковка здесь — нарушение."],
["obey","подчиняться, слушаться","v","Children should obey their parents.","Дети должны слушаться родителей."],
["beg","умолять, просить","v","I beg you, do not go.","Умоляю тебя, не уходи."],
["swear","клясться; ругаться","v","I swear I am telling the truth.","Клянусь, я говорю правду."],
["trust","доверие","n","Trust is important in a friendship.","Доверие важно в дружбе."],
["trust","доверять","v","I trust my friends.","Я доверяю своим друзьям."],
["honour","честь","n","It is an honour to meet you.","Для меня честь познакомиться с вами."],
["honour","чтить, оказывать честь","v","We honour those who died in the war.","Мы чтим погибших на войне."],
["impress","производить впечатление","v","Her English impressed everyone.","Её английский всех впечатлил."],
["impressed","впечатлённый","adj","I was impressed by the hotel.","Отель произвёл на меня впечатление."],
["comfort","утешать","v","She comforted the crying child.","Она утешила плачущего ребёнка."],
["comfort","комфорт, утешение","n","The hotel offers every comfort.","Отель предлагает все удобства."],
["hesitate","колебаться, медлить","v","Do not hesitate to ask.","Не стесняйся спрашивать."],
["interrupt","перебивать, прерывать","v","Please do not interrupt me.","Пожалуйста, не перебивай меня."],
["whisper","шептать","v","She whispered something in his ear.","Она прошептала что-то ему на ухо."],
["whisper","шёпот","n","They spoke in whispers.","Они говорили шёпотом."]
]},
{id:"b2-people-2", title:"Люди и роли", words:[
["citizen","гражданин","n","Every citizen has the right to vote.","Каждый гражданин имеет право голоса."],
["resident","житель","n","Residents complained about the noise.","Жители пожаловались на шум."],
["resident","проживающий","adj","The hotel has a resident doctor.","В отеле есть штатный врач."],
["participant","участник","n","All participants receive a certificate.","Все участники получают сертификат."],
["opponent","противник, соперник","n","He beat his opponent in two sets.","Он победил соперника в двух сетах."],
["representative","представитель","n","A representative of the company will call you.","Представитель компании вам позвонит."],
["representative","представительный, типичный","adj","The sample is representative of the population.","Выборка репрезентативна для населения."],
["specialist","специалист","n","She is a heart specialist.","Она специалист по сердцу."],
["specialist","специализированный","adj","You need specialist advice.","Тебе нужен совет специалиста."],
["executive","руководитель","n","She is a senior executive at the bank.","Она старший руководитель в банке."],
["executive","исполнительный","adj","He is on the executive committee.","Он в исполнительном комитете."],
["chairman","председатель","n","The chairman opened the meeting.","Председатель открыл собрание."],
["minister","министр","n","The minister answered questions.","Министр ответил на вопросы."],
["lord","лорд; господин","n","The lord owned all the land here.","Лорд владел всей землёй здесь."],
["master","мастер; хозяин","n","He is a master of his art.","Он мастер своего дела."],
["master","овладеть, освоить","v","She mastered French in two years.","Она освоила французский за два года."],
["pupil","ученик","n","The school has five hundred pupils.","В школе пятьсот учеников."],
["junior","младший","adj","He is a junior doctor.","Он младший врач."],
["senior","старший","adj","She is a senior manager.","Она старший менеджер."],
["elderly","пожилой","adj","An elderly woman lives next door.","По соседству живёт пожилая женщина."],
["fellow","собрат, товарищ (по чему-то)","adj","I met a fellow student at the library.","Я встретил в библиотеке однокурсника."],
["slave","раб","n","Slaves worked on the farms.","Рабы работали на фермах."],
["crew","экипаж, команда","n","The crew of the ship was rescued.","Экипаж корабля был спасён."],
["gang","банда; бригада","n","A gang of boys was waiting outside.","Снаружи ждала компания мальчишек."],
["witness","свидетель","n","The witness described the man.","Свидетель описал мужчину."],
["witness","быть свидетелем","v","She witnessed the accident.","Она стала свидетелем аварии."],
["critic","критик","n","The critics loved the film.","Критикам понравился фильм."],
["being","существо","n","Human beings need water.","Людям нужна вода."],
["self","собственное «я»","n","She is her old self again.","Она снова стала прежней."],
["household","домашнее хозяйство, семья","n","Most households have a car.","У большинства семей есть машина."]
]},
{id:"b2-things-3", title:"Предметы и материалы", words:[
["cable","кабель","n","The cable connects the TV to the box.","Кабель соединяет телевизор с приставкой."],
["wire","провод, проволока","n","Do not touch the wire!","Не трогай провод!"],
["steel","сталь","n","The bridge is made of steel.","Мост сделан из стали."],
["rubber","резина","n","Tyres are made of rubber.","Шины делают из резины."],
["rubber","резиновый","adj","Wear rubber gloves.","Надень резиновые перчатки."],
["silk","шёлк","n","The dress is made of silk.","Платье сделано из шёлка."],
["feather","перо","n","The pillow is filled with feathers.","Подушка набита перьями."],
["mineral","минерал","n","Water contains minerals.","Вода содержит минералы."],
["flame","пламя","n","The flames destroyed the house.","Пламя уничтожило дом."],
["burn","ожог","n","She has a burn on her hand.","У неё ожог на руке."],
["bullet","пуля","n","The bullet hit the wall.","Пуля попала в стену."],
["tank","бак, резервуар; танк","n","The fuel tank is empty.","Топливный бак пуст."],
["disc","диск","n","The music is on a disc.","Музыка на диске."],
["motor","мотор, двигатель","n","The motor is very quiet.","Двигатель очень тихий."],
["motor","моторный, автомобильный","adj","The motor industry is growing.","Автомобильная промышленность растёт."],
["monitor","монитор","n","The computer has a large monitor.","У компьютера большой монитор."],
["monitor","отслеживать, контролировать","v","Doctors monitored his heart.","Врачи следили за его сердцем."],
["panel","панель; комиссия","n","Press the button on the panel.","Нажми кнопку на панели."],
["switch","выключатель, переключатель","n","The light switch is by the door.","Выключатель у двери."],
["handle","ручка (двери, сумки)","n","The door handle is broken.","Дверная ручка сломана."],
["handle","справляться; обращаться с","v","She handled the problem well.","Она хорошо справилась с проблемой."],
["load","груз, нагрузка","n","The lorry carried a heavy load.","Грузовик вёз тяжёлый груз."],
["load","грузить","v","They loaded the boxes onto the truck.","Они погрузили коробки в грузовик."],
["pile","куча, стопка","n","There is a pile of books on the desk.","На столе стопка книг."],
["pile","складывать в кучу","v","Pile the plates by the sink.","Сложи тарелки у раковины."],
["bunch","связка, пучок; компания","n","He gave her a bunch of flowers.","Он подарил ей букет цветов."],
["dozen","дюжина","n","I bought a dozen eggs.","Я купил дюжину яиц."],
["dozen","дюжина (определитель)","det","There were a dozen people at the party.","На вечеринке была дюжина людей."],
["wrap","заворачивать","v","Wrap the present in paper.","Заверни подарок в бумагу."],
["print","отпечаток; печать","n","The book is in small print.","Книга напечатана мелким шрифтом."]
]},
{id:"b2-business", title:"Бизнес и финансы", words:[
["budget","бюджет","n","We have a small budget for the trip.","У нас небольшой бюджет на поездку."],
["income","доход","n","Her income has increased this year.","В этом году её доход вырос."],
["wage","заработная плата (почасовая)","n","Wages are low in this industry.","Зарплаты в этой отрасли низкие."],
["expense","расход, трата","n","Travel expenses are paid by the company.","Дорожные расходы оплачивает компания."],
["fee","плата, гонорар","n","The school fees are high.","Плата за обучение высокая."],
["debt","долг","n","He is in debt.","Он в долгах."],
["loan","заём, кредит","n","We took out a loan to buy the house.","Мы взяли кредит на покупку дома."],
["owe","быть должным","v","I owe you ten euros.","Я должен тебе десять евро."],
["fund","фонд, средства","n","The fund helps poor children.","Фонд помогает бедным детям."],
["fund","финансировать","v","The project is funded by the government.","Проект финансируется правительством."],
["funding","финансирование","n","The school needs more funding.","Школе нужно больше финансирования."],
["finance","финансы","n","She works in finance.","Она работает в финансах."],
["finance","финансировать","v","The bank financed the new building.","Банк профинансировал новое здание."],
["investment","инвестиция","n","Property is a good investment.","Недвижимость — хорошее вложение."],
["insurance","страхование, страховка","n","You need travel insurance.","Тебе нужна туристическая страховка."],
["pension","пенсия","n","He lives on a small pension.","Он живёт на маленькую пенсию."],
["saving","экономия; сбережения","n","I spent all my savings on the car.","Я потратил все сбережения на машину."],
["purchase","покупка","n","Keep the receipt for your purchase.","Сохраните чек за покупку."],
["purchase","покупать","v","She purchased a new laptop.","Она купила новый ноутбук."],
["stock","запас; акции","n","The shop has a large stock of books.","В магазине большой запас книг."],
["firm","фирма","n","She works for a law firm.","Она работает в юридической фирме."],
["corporate","корпоративный","adj","He wears a suit at corporate events.","На корпоративных мероприятиях он носит костюм."],
["agency","агентство","n","I found the flat through an agency.","Я нашёл квартиру через агентство."],
["contract","контракт, договор","n","She signed a two-year contract.","Она подписала двухлетний контракт."],
["contract","заключать договор; сокращаться","v","The company contracted a builder.","Компания наняла строителя по договору."],
["sector","сектор, отрасль","n","She works in the health sector.","Она работает в секторе здравоохранения."],
["industrial","промышленный","adj","This is an industrial area.","Это промышленный район."],
["labour","труд; рабочая сила","n","The cost of labour is rising.","Стоимость труда растёт."],
["commission","комиссия (плата); поручение","n","The agent takes a five per cent commission.","Агент берёт пятипроцентную комиссию."],
["commission","заказывать, поручать","v","The museum commissioned a new painting.","Музей заказал новую картину."]
]},
{id:"b2-management", title:"Управление и решения", words:[
["administration","администрация, управление","n","The administration is planning changes.","Администрация планирует изменения."],
["leadership","руководство, лидерство","n","The team needs strong leadership.","Команде нужно сильное руководство."],
["committee","комитет","n","The committee meets every month.","Комитет собирается каждый месяц."],
["council","совет (орган)","n","The city council closed the road.","Городской совет закрыл дорогу."],
["agenda","повестка дня","n","What is on the agenda for today?","Что сегодня на повестке дня?"],
["session","сессия, заседание, занятие","n","The training session starts at ten.","Тренировка начинается в десять."],
["proposal","предложение (план)","n","The committee rejected the proposal.","Комитет отклонил предложение."],
["propose","предлагать","v","I propose that we start early.","Я предлагаю начать пораньше."],
["approve","одобрять","v","The plan was approved.","План был одобрен."],
["approval","одобрение","n","We need the manager's approval.","Нам нужно одобрение менеджера."],
["consideration","рассмотрение, соображение","n","Your request is under consideration.","Ваша просьба рассматривается."],
["priority","приоритет","n","Safety is our first priority.","Безопасность — наш главный приоритет."],
["initiative","инициатива","n","She took the initiative and called him.","Она проявила инициативу и позвонила ему."],
["scheme","схема, программа, план","n","The government started a new housing scheme.","Правительство запустило новую жилищную программу."],
["procedure","процедура","n","Follow the safety procedure.","Соблюдай процедуру безопасности."],
["regulation","правило, регламент","n","There are strict regulations about food.","Есть строгие правила по еде."],
["requirement","требование","n","A degree is a requirement for this job.","Диплом — требование для этой работы."],
["criterion","критерий","n","Price is the main criterion.","Цена — главный критерий."],
["objective","цель, задача","n","Our objective is to win.","Наша цель — победить."],
["objective","объективный","adj","Try to be objective.","Постарайся быть объективным."],
["outcome","результат, исход","n","The outcome of the meeting was positive.","Итог встречи был положительным."],
["assess","оценивать","v","Teachers assess the students' work.","Учителя оценивают работу учеников."],
["assessment","оценка, оценивание","n","The assessment takes an hour.","Оценивание занимает час."],
["evaluate","оценивать, давать оценку","v","We evaluated the results.","Мы оценили результаты."],
["conduct","проводить; вести себя","v","The police conducted an investigation.","Полиция провела расследование."],
["conduct","поведение","n","His conduct at work was excellent.","Его поведение на работе было безупречным."],
["operate","управлять; работать (о технике)","v","He operates the machine.","Он управляет станком."]
]},
{id:"b2-politics", title:"Политика и общество", words:[
["parliament","парламент","n","Parliament passed the new law.","Парламент принял новый закон."],
["elect","избирать","v","She was elected president.","Её избрали президентом."],
["govern","управлять, править","v","The party governed for ten years.","Партия правила десять лет."],
["conservative","консервативный","adj","My grandfather has conservative views.","У моего дедушки консервативные взгляды."],
["conservative","консерватор","n","The conservatives won the election.","Консерваторы выиграли выборы."],
["civil","гражданский","adj","Civil rights are protected by law.","Гражданские права защищены законом."],
["justice","справедливость, правосудие","n","Everyone wants justice.","Все хотят справедливости."],
["freedom","свобода","n","Freedom of speech is important.","Свобода слова важна."],
["revolution","революция","n","The revolution changed the country.","Революция изменила страну."],
["crisis","кризис","n","The country is in an economic crisis.","Страна в экономическом кризисе."],
["conflict","конфликт","n","There is a conflict between the two groups.","Между двумя группами конфликт."],
["conflict","противоречить, конфликтовать","v","His story conflicts with hers.","Его рассказ противоречит её рассказу."],
["opposition","оппозиция; сопротивление","n","The opposition criticized the plan.","Оппозиция раскритиковала план."],
["oppose","выступать против","v","Many people oppose the new law.","Многие выступают против нового закона."],
["opposed","против, противостоящий","adj","I am opposed to the idea.","Я против этой идеи."],
["defend","защищать","v","The army defended the city.","Армия защищала город."],
["defence","защита, оборона","n","The best defence is attack.","Лучшая защита — нападение."],
["defeat","побеждать, наносить поражение","v","Our team defeated them.","Наша команда их победила."],
["defeat","поражение","n","It was a bad defeat for the team.","Это было тяжёлое поражение для команды."],
["victory","победа","n","The team celebrated the victory.","Команда праздновала победу."],
["military","военный","adj","He is in military service.","Он на военной службе."],
["military","армия, вооружённые силы","n","The military took control.","Военные взяли контроль."],
["armed","вооружённый","adj","The police are armed.","Полиция вооружена."],
["arms","оружие","n","The country sells arms.","Страна продаёт оружие."],
["violence","насилие","n","There is too much violence on TV.","На телевидении слишком много насилия."],
["threat","угроза","n","Climate change is a threat to us all.","Изменение климата — угроза для всех нас."],
["threaten","угрожать","v","He threatened to call the police.","Он пригрозил вызвать полицию."],
["command","команда, приказ","n","The soldiers waited for the command.","Солдаты ждали команды."],
["command","командовать","v","He commands a small army.","Он командует небольшой армией."],
["district","район, округ","n","We live in a quiet district.","Мы живём в тихом районе."]
]},
{id:"b2-law-2", title:"Право и порядок", words:[
["trial","судебный процесс; испытание","n","The trial lasted two weeks.","Суд длился две недели."],
["suspect","подозревать","v","The police suspect him of the theft.","Полиция подозревает его в краже."],
["suspect","подозреваемый","n","The suspect was arrested.","Подозреваемый был арестован."],
["investigation","расследование","n","The investigation took a year.","Расследование заняло год."],
["proof","доказательство","n","There is no proof that he did it.","Нет доказательств, что это сделал он."],
["deny","отрицать","v","He denied stealing the money.","Он отрицал, что украл деньги."],
["licence","лицензия, права","n","He lost his driving licence.","Он лишился водительских прав."],
["permit","разрешение (документ)","n","You need a permit to park here.","Чтобы парковаться здесь, нужно разрешение."],
["permit","разрешать","v","The law does not permit smoking here.","Закон не разрешает курить здесь."],
["register","регистрировать(ся)","v","Register for the course online.","Зарегистрируйся на курс онлайн."],
["register","реестр, журнал","n","The teacher checked the register.","Учитель проверил журнал."],
["justify","оправдывать, обосновывать","v","How can you justify this decision?","Как ты можешь обосновать это решение?"],
["obligation","обязательство","n","You are under no obligation to buy.","Ты не обязан покупать."],
["privacy","частная жизнь, конфиденциальность","n","Everyone has a right to privacy.","Каждый имеет право на частную жизнь."],
["protection","защита","n","Children need protection.","Дети нуждаются в защите."],
["secure","безопасный, надёжный","adj","Keep your money in a secure place.","Храни деньги в надёжном месте."],
["secure","обеспечивать безопасность; добиваться","v","The company secured a new contract.","Компания получила новый контракт."],
["rescue","спасать","v","Firefighters rescued the family.","Пожарные спасли семью."],
["rescue","спасение","n","The rescue took three hours.","Спасение заняло три часа."],
["capture","захватывать, поймать","v","The police captured the thief.","Полиция поймала вора."],
["capture","захват, поимка","n","The capture of the city ended the war.","Захват города завершил войну."],
["shooting","стрельба","n","There was a shooting in the city centre.","В центре города была стрельба."],
["shot","выстрел; снимок","n","We heard a shot.","Мы услышали выстрел."],
["incident","инцидент, происшествие","n","The police are investigating the incident.","Полиция расследует происшествие."],
["strict","строгий","adj","The school has strict rules.","В школе строгие правила."],
["dismiss","увольнять; отклонять","v","He was dismissed for stealing.","Его уволили за кражу."],
["cancel","отменять","v","They had to cancel the flight.","Им пришлось отменить рейс."]
]},
{id:"b2-science", title:"Наука и исследования", words:[
["phenomenon","явление, феномен","n","Snow in summer is a rare phenomenon.","Снег летом — редкое явление."],
["concept","концепция, понятие","n","The concept of time is difficult to explain.","Понятие времени трудно объяснить."],
["notion","понятие, представление","n","I have no notion of what he means.","Я не имею представления, что он имеет в виду."],
["principle","принцип","n","She lives by strict principles.","Она живёт по строгим принципам."],
["observe","наблюдать","v","Scientists observed the birds for a year.","Учёные наблюдали за птицами год."],
["observation","наблюдение","n","The patient is under observation.","Пациент под наблюдением."],
["detect","обнаруживать","v","The test can detect the disease early.","Тест может выявить болезнь на ранней стадии."],
["demonstrate","демонстрировать, доказывать","v","The experiment demonstrates how plants grow.","Эксперимент показывает, как растут растения."],
["illustrate","иллюстрировать, пояснять","v","This example illustrates the rule.","Этот пример иллюстрирует правило."],
["illustration","иллюстрация","n","The book has beautiful illustrations.","В книге красивые иллюстрации."],
["calculate","вычислять","v","Calculate the total cost.","Вычисли общую стоимость."],
["estimate","оценивать (приблизительно)","v","We estimate the cost at two thousand.","Мы оцениваем стоимость в две тысячи."],
["estimate","оценка, смета","n","Can you give me an estimate?","Можешь дать примерную оценку?"],
["measurement","измерение","n","Take the measurements of the room.","Сними размеры комнаты."],
["frequency","частота","n","The frequency of accidents has fallen.","Частота аварий снизилась."],
["sequence","последовательность","n","Put the pictures in the right sequence.","Расположи картинки в правильной последовательности."],
["component","компонент","n","The engine has many components.","У двигателя много компонентов."],
["structure","структурировать","v","The essay is well structured.","Сочинение хорошо структурировано."],
["species","вид (биологический)","n","This species of bird is rare.","Этот вид птиц редок."],
["creature","существо","n","Strange creatures live in the deep sea.","В глубинах моря живут странные существа."],
["wildlife","дикая природа","n","The park protects wildlife.","Парк защищает дикую природу."],
["universe","вселенная","n","The universe is enormous.","Вселенная огромна."],
["satellite","спутник","n","The satellite sends signals to Earth.","Спутник посылает сигналы на Землю."],
["solar","солнечный","adj","The house has solar panels.","В доме солнечные панели."],
["artificial","искусственный","adj","The flowers are artificial.","Цветы искусственные."],
["virtual","виртуальный","adj","We had a virtual meeting.","У нас была виртуальная встреча."],
["exploration","исследование, разведка","n","Space exploration is expensive.","Исследование космоса стоит дорого."],
["finding","вывод, результат (исследования)","n","The findings were published in a journal.","Результаты были опубликованы в журнале."]
]},
{id:"b2-verbs-1", title:"Действия и движение", words:[
["abandon","бросать, оставлять","v","They abandoned the car in the forest.","Они бросили машину в лесу."],
["grab","хватать","v","Grab your coat and come!","Хватай пальто и пошли!"],
["drag","тащить, волочить","v","Do not drag the chair, lift it.","Не тащи стул, подними его."],
["dig","копать","v","We dig a hole for the tree.","Мы копаем яму для дерева."],
["float","плавать (на поверхности), парить","v","Wood floats on water.","Дерево держится на воде."],
["melt","таять, плавить(ся)","v","The snow is melting.","Снег тает."],
["lean","наклоняться, прислоняться","v","Do not lean on the door.","Не прислоняйся к двери."],
["stretch","растягивать(ся), тянуться","v","Stretch your arms above your head.","Вытяни руки над головой."],
["stretch","отрезок; растяжка","n","This stretch of road is dangerous.","Этот участок дороги опасен."],
["slip","поскользнуться, выскальзывать","v","Be careful, you may slip on the ice.","Осторожно, на льду можно поскользнуться."],
["slide","скользить","v","The children slid down the hill.","Дети скатились с горки."],
["slide","горка; слайд","n","The children love the slide in the park.","Дети любят горку в парке."],
["sweep","подметать","v","Sweep the floor, please.","Подмети пол, пожалуйста."],
["rub","тереть","v","Do not rub your eyes.","Не три глаза."],
["tear","рвать","v","Be careful not to tear the paper.","Осторожно, не порви бумагу."],
["tear","слеза","n","A tear ran down her cheek.","По её щеке скатилась слеза.","drop"],
["tear","дыра, разрыв","n","There is a tear in my jacket.","У меня на куртке дыра.","rip"],
["split","раскалывать(ся), делить","v","Let's split the bill.","Давай разделим счёт."],
["split","разделение, раскол","n","There was a split in the party.","В партии произошёл раскол."],
["wind","заводить; извиваться","v","The road winds through the hills.","Дорога вьётся между холмами."],
["mount","взбираться; устанавливать; расти","v","Costs are mounting.","Расходы растут."],
["rush","мчаться, спешить","v","We rushed to the station.","Мы помчались на вокзал."],
["rush","спешка, наплыв","n","There is no rush.","Спешить некуда."],
["stare","пристально смотреть","v","Do not stare at people.","Не пялься на людей."],
["scream","кричать, вопить","v","She screamed when she saw the spider.","Она закричала, увидев паука."],
["scream","крик, вопль","n","We heard a scream.","Мы услышали крик."],
["strike","ударять; бастовать","v","The clock strikes every hour.","Часы бьют каждый час."],
["strike","забастовка; удар","n","The workers are on strike.","Рабочие бастуют."],
["crash","разбиваться, врезаться","v","The car crashed into a tree.","Машина врезалась в дерево."],
["crash","авария, крушение","n","Two people died in the crash.","В аварии погибли два человека."]
]},
{id:"b2-verbs-2", title:"Получать и достигать", words:[
["acquire","приобретать","v","She acquired a taste for jazz.","Она пристрастилась к джазу."],
["obtain","получать, добывать","v","You need to obtain a visa.","Тебе нужно получить визу."],
["gain","получать, приобретать","v","He gained experience abroad.","Он приобрёл опыт за границей."],
["gain","прибыль, выигрыш, прирост","n","There was a gain in weight.","Произошёл набор веса."],
["seek","искать, добиваться","v","He is seeking a new job.","Он ищет новую работу."],
["pursue","преследовать (цель), заниматься","v","She decided to pursue a career in law.","Она решила заняться юридической карьерой."],
["attempt","попытка","n","This is my second attempt.","Это моя вторая попытка."],
["attempt","пытаться","v","He attempted to climb the mountain.","Он попытался подняться на гору."],
["struggle","бороться, с трудом справляться","v","She struggled to open the door.","Она с трудом открыла дверь."],
["struggle","борьба","n","It was a long struggle.","Это была долгая борьба."],
["establish","основывать, устанавливать","v","The school was established in 1900.","Школа была основана в 1900 году."],
["found","основывать","v","The company was founded in 1990.","Компания была основана в 1990 году."],
["generate","порождать, генерировать","v","The project generated a lot of interest.","Проект вызвал большой интерес."],
["construct","строить, сооружать","v","The bridge was constructed in a year.","Мост построили за год."],
["construction","строительство","n","The house is under construction.","Дом строится."],
["creation","создание, творение","n","The creation of the park took years.","Создание парка заняло годы."],
["contribute","вносить вклад","v","Everyone contributed to the project.","Все внесли вклад в проект."],
["contribution","вклад","n","Thank you for your contribution.","Спасибо за ваш вклад."],
["enable","давать возможность","v","The money enabled us to travel.","Деньги позволили нам путешествовать."],
["ensure","обеспечивать, гарантировать","v","Please ensure the door is locked.","Пожалуйста, убедись, что дверь заперта."],
["guarantee","гарантировать","v","We guarantee delivery in two days.","Мы гарантируем доставку за два дня."],
["guarantee","гарантия","n","The phone has a two-year guarantee.","У телефона двухлетняя гарантия."],
["maintain","поддерживать, сохранять","v","It is hard to maintain a healthy diet.","Трудно придерживаться здорового питания."],
["retain","сохранять, удерживать","v","The town retains its old charm.","Город сохраняет своё старинное очарование."],
["preserve","сохранять, беречь","v","We must preserve the forest.","Мы должны сохранить лес."],
["resist","сопротивляться","v","I could not resist the cake.","Я не смог устоять перед тортом."],
["possess","обладать","v","She possesses great talent.","Она обладает большим талантом."],
["adopt","усыновлять; принимать","v","They adopted a child.","Они усыновили ребёнка."]
]},
{id:"b2-verbs-3", title:"Говорить и заявлять", words:[
["acknowledge","признавать","v","He acknowledged his mistake.","Он признал свою ошибку."],
["declare","объявлять, заявлять","v","The president declared a holiday.","Президент объявил выходной."],
["assume","предполагать, допускать","v","I assume you have read the report.","Я предполагаю, ты прочитал отчёт."],
["imply","подразумевать, намекать","v","Are you implying that I was wrong?","Ты намекаешь, что я ошибся?"],
["cite","цитировать, ссылаться","v","The article cites several studies.","Статья ссылается на несколько исследований."],
["remark","замечать, отмечать","v","She remarked that the room was cold.","Она заметила, что в комнате холодно."],
["remark","замечание","n","He made a rude remark.","Он сделал грубое замечание."],
["criticize","критиковать","v","The press criticized the government.","Пресса раскритиковала правительство."],
["criticism","критика","n","The film received a lot of criticism.","Фильм подвергся большой критике."],
["debate","дебаты, обсуждение","n","There was a long debate about the plan.","Был долгий спор о плане."],
["debate","обсуждать, дискутировать","v","They debated the question for hours.","Они обсуждали вопрос часами."],
["emphasize","подчёркивать","v","The teacher emphasized the importance of reading.","Учитель подчеркнул важность чтения."],
["emphasis","акцент, ударение","n","The course puts emphasis on speaking.","В курсе акцент на устной речи."],
["inform","сообщать, информировать","v","Please inform us of any changes.","Пожалуйста, сообщайте нам о любых изменениях."],
["urge","настоятельно призывать","v","Doctors urge people to exercise.","Врачи призывают людей заниматься спортом."],
["insist","настаивать","v","She insisted on paying for dinner.","Она настояла на том, чтобы заплатить за ужин."],
["interpret","толковать, интерпретировать; переводить (устно)","v","How do you interpret this poem?","Как ты толкуешь это стихотворение?"],
["reveal","раскрывать, обнаруживать","v","She revealed the secret.","Она раскрыла секрет."],
["expose","разоблачать; подвергать воздействию","v","The newspaper exposed the truth.","Газета разоблачила правду."],
["recall","вспоминать","v","I cannot recall his name.","Я не могу вспомнить его имя."],
["regard","считать, рассматривать как","v","He is regarded as the best player.","Его считают лучшим игроком."],
["regard","отношение; уважение","n","I have great regard for her.","Я очень её уважаю."],
["excuse","оправдание, отговорка","n","That is no excuse for being late.","Это не оправдание для опоздания."],
["excuse","извинять, оправдывать","v","Excuse me, where is the station?","Извините, где вокзал?"],
["appeal","призыв; обращение; привлекательность","n","The police made an appeal for witnesses.","Полиция обратилась к свидетелям."],
["appeal","обращаться с призывом; привлекать","v","The idea appeals to me.","Эта идея мне нравится."],
["broadcast","транслировать","v","The match was broadcast live.","Матч транслировали в прямом эфире."],
["broadcast","трансляция, передача","n","We watched the news broadcast.","Мы смотрели выпуск новостей."],
["publication","публикация, издание","n","The publication of the book was delayed.","Публикация книги задержалась."],
["edition","издание, выпуск","n","This is the second edition of the book.","Это второе издание книги."]
]},
{id:"b2-verbs-4", title:"Изменять и управлять", words:[
["adapt","адаптировать(ся)","v","She adapted quickly to the new school.","Она быстро адаптировалась к новой школе."],
["alter","изменять","v","We had to alter our plans.","Нам пришлось изменить планы."],
["modify","видоизменять","v","The design was modified.","Дизайн был изменён."],
["convert","преобразовывать, переделывать","v","They converted the garage into a bedroom.","Они переделали гараж в спальню."],
["transform","преображать, трансформировать","v","The new road transformed the town.","Новая дорога преобразила город."],
["transition","переход","n","The transition to the new system was slow.","Переход на новую систему был медленным."],
["transfer","переводить, переносить","v","I want to transfer money to your account.","Я хочу перевести деньги на твой счёт."],
["transfer","перевод, перемещение","n","He asked for a transfer to another office.","Он попросил перевод в другой офис."],
["extend","продлевать, расширять","v","We extended our holiday by a week.","Мы продлили отпуск на неделю."],
["extent","степень, размер","n","To what extent do you agree?","В какой степени ты согласен?"],
["enhance","улучшать, усиливать","v","Music enhances the film.","Музыка усиливает фильм."],
["decline","снижаться; отклонять","v","Sales declined last year.","Продажи снизились в прошлом году."],
["decline","снижение, упадок","n","There has been a decline in prices.","Цены снизились."],
["decrease","уменьшаться","v","The population decreased.","Население уменьшилось."],
["decrease","уменьшение","n","There was a decrease in sales.","Произошло снижение продаж."],
["reduction","сокращение, снижение","n","There was a reduction in prices.","Произошло снижение цен."],
["lower","понижать","v","They lowered the price.","Они понизили цену."],
["narrow","сужать(ся)","v","The road narrows here.","Дорога здесь сужается."],
["multiply","умножать(ся)","v","Multiply three by four.","Умножь три на четыре."],
["vary","варьироваться, различаться","v","Prices vary from shop to shop.","Цены различаются от магазина к магазину."],
["distribute","распределять, раздавать","v","The teacher distributed the papers.","Учитель раздал листы."],
["distribution","распределение, распространение","n","The distribution of food took hours.","Раздача еды заняла часы."],
["dominate","доминировать, преобладать","v","One team dominated the game.","Одна команда доминировала в игре."],
["impose","навязывать, налагать","v","The government imposed a new tax.","Правительство ввело новый налог."],
["settle","улаживать; поселяться","v","They settled the argument.","Они уладили спор."],
["resolve","разрешать (проблему)","v","We resolved the problem quickly.","Мы быстро решили проблему."],
["delay","откладывать, задерживать","v","The flight was delayed by fog.","Рейс задержали из-за тумана."],
["delay","задержка","n","There was a two-hour delay.","Была двухчасовая задержка."],
["schedule","планировать, назначать","v","The meeting is scheduled for Monday.","Встреча назначена на понедельник."]
]},
{id:"b2-verbs-5", title:"Разные глаголы", words:[
["accompany","сопровождать","v","She accompanied me to the doctor.","Она сопровождала меня к врачу."],
["encounter","сталкиваться, встречать","v","We encountered some problems.","Мы столкнулись с некоторыми проблемами."],
["encounter","встреча, столкновение","n","It was my first encounter with a bear.","Это была моя первая встреча с медведем."],
["engage","привлекать, вовлекать; заниматься","v","The teacher engaged the students in a discussion.","Учитель вовлёк учеников в обсуждение."],
["associate","связывать, ассоциировать","v","I associate summer with the sea.","Лето у меня ассоциируется с морем."],
["associated","связанный","adj","Smoking is associated with cancer.","Курение связано с раком."],
["association","ассоциация, объединение","n","She joined the teachers' association.","Она вступила в ассоциацию учителей."],
["arise","возникать","v","Problems may arise later.","Проблемы могут возникнуть позже."],
["emerge","появляться, возникать","v","The sun emerged from behind the clouds.","Солнце показалось из-за облаков."],
["inspire","вдохновлять","v","Her story inspired me.","Её история меня вдохновила."],
["satisfy","удовлетворять","v","The answer did not satisfy me.","Ответ меня не удовлетворил."],
["satisfied","удовлетворённый","adj","I am satisfied with the result.","Я доволен результатом."],
["surround","окружать","v","Trees surround the house.","Дом окружают деревья."],
["surrounding","окружающий","adj","We explored the surrounding villages.","Мы исследовали окрестные деревни."],
["select","выбирать, отбирать","v","Select the best photos.","Отбери лучшие фотографии."],
["selection","выбор, отбор","n","The shop has a good selection of wines.","В магазине хороший выбор вин."],
["submit","подавать, представлять","v","Submit your essay by Friday.","Сдай сочинение к пятнице."],
["install","устанавливать","v","We installed a new heating system.","Мы установили новую систему отопления."],
["edit","редактировать","v","She edited the film.","Она смонтировала фильм."],
["sponsor","спонсировать","v","The bank sponsors the football team.","Банк спонсирует футбольную команду."],
["sponsor","спонсор","n","We need a sponsor for the event.","Нам нужен спонсор для мероприятия."],
["grant","предоставлять, выдавать","v","The bank granted him a loan.","Банк выдал ему кредит."],
["grant","грант, субсидия","n","She received a grant to study abroad.","Она получила грант на учёбу за границей."],
["bet","держать пари, спорить","v","I bet it will rain tomorrow.","Спорим, завтра будет дождь."],
["bet","пари, ставка","n","He lost the bet.","Он проиграл пари."],
["rely","полагаться","v","You can rely on me.","Ты можешь на меня положиться."],
["rid","избавлять (get rid of)","v","Get rid of these old shoes.","Избавься от этих старых туфель."],
["desert","покидать, бросать","v","He deserted his family.","Он бросил семью."],
["bear","выносить, терпеть","v","I cannot bear the noise.","Я не выношу шум."],
["battle","бороться","v","She battled cancer for two years.","Она два года боролась с раком."]
]},
{id:"b2-nouns-1", title:"Идеи и понятия", words:[
["aspect","аспект, сторона","n","We discussed every aspect of the plan.","Мы обсудили все стороны плана."],
["perspective","точка зрения, перспектива","n","Try to see it from my perspective.","Попробуй посмотреть с моей точки зрения."],
["insight","понимание, проницательность","n","The book gives an insight into village life.","Книга даёт представление о деревенской жизни."],
["judgement","суждение, мнение; приговор","n","I trust her judgement.","Я доверяю её суждению."],
["philosophy","философия","n","He studied philosophy at university.","Он изучал философию в университете."],
["faith","вера","n","She has great faith in her doctor.","Она очень верит своему врачу."],
["soul","душа","n","Music is good for the soul.","Музыка полезна для души."],
["spiritual","духовный","adj","She is a very spiritual person.","Она очень духовный человек."],
["moral","моральный, нравственный","adj","It is a moral question.","Это вопрос морали."],
["moral","мораль (поучение)","n","The moral of the story is: be honest.","Мораль истории: будь честным."],
["ethical","этический","adj","Is it ethical to test on animals?","Этично ли проводить испытания на животных?"],
["imagination","воображение","n","Children have a rich imagination.","У детей богатое воображение."],
["vision","зрение; видение, представление","n","She has a clear vision of the future.","У неё ясное видение будущего."],
["existence","существование","n","Do you believe in the existence of ghosts?","Ты веришь в существование привидений?"],
["origin","происхождение","n","The origin of the word is Latin.","Слово латинского происхождения."],
["circumstance","обстоятельство","n","In these circumstances, we must wait.","В этих обстоятельствах мы должны подождать."],
["instance","пример, случай","n","For instance, take this word.","Например, возьмём это слово."],
["means","средство, способ","n","The car is a means of transport.","Автомобиль — средство передвижения."],
["combination","сочетание, комбинация","n","Blue and yellow is a good combination.","Синий и жёлтый — хорошее сочетание."],
["characteristic","характерная черта","n","Patience is one of her characteristics.","Терпение — одна из её черт."],
["characteristic","характерный","adj","This is a characteristic feature of the style.","Это характерная черта стиля."],
["concentration","концентрация, сосредоточенность","n","This work needs total concentration.","Эта работа требует полной сосредоточенности."],
["discipline","дисциплина","n","The school has strict discipline.","В школе строгая дисциплина."],
["commitment","приверженность, обязательство","n","She showed great commitment to the job.","Она проявила большую преданность работе."],
["expectation","ожидание","n","The film did not meet my expectations.","Фильм не оправдал моих ожиданий."],
["desire","желание","n","She has a strong desire to travel.","У неё сильное желание путешествовать."],
["desire","желать","v","He got everything he desired.","Он получил всё, чего желал."],
["fortune","состояние (богатство); удача","n","He made a fortune in business.","Он сколотил состояние в бизнесе."],
["wealth","богатство","n","The country has great natural wealth.","Страна обладает большими природными богатствами."],
["wealthy","богатый, состоятельный","adj","She comes from a wealthy family.","Она из богатой семьи."]
]},
{id:"b2-nouns-2", title:"Дело и результат", words:[
["affair","дело; роман (отношения)","n","It is a private affair.","Это личное дело."],
["failure","неудача, провал","n","The plan ended in failure.","План закончился провалом."],
["fault","вина; дефект","n","It was my fault.","Это была моя вина."],
["weakness","слабость","n","Chocolate is my weakness.","Шоколад — моя слабость."],
["relief","облегчение","n","What a relief that you are safe!","Какое облегчение, что ты в безопасности!"],
["reputation","репутация","n","The hotel has a good reputation.","У отеля хорошая репутация."],
["popularity","популярность","n","The singer's popularity is growing.","Популярность певца растёт."],
["status","статус, положение","n","What is your marital status?","Каково ваше семейное положение?"],
["presence","присутствие","n","Your presence is required at the meeting.","Ваше присутствие на собрании обязательно."],
["preparation","подготовка","n","The trip needs careful preparation.","Поездка требует тщательной подготовки."],
["examination","экзамен; осмотр","n","The examination lasted three hours.","Экзамен длился три часа."],
["enquiry","запрос, расследование","n","We received several enquiries about the job.","Мы получили несколько запросов о вакансии."],
["feedback","обратная связь, отзыв","n","The teacher gave us feedback on our essays.","Учитель дал нам отзыв на сочинения."],
["hearing","слух; слушание","n","Her hearing is not good.","У неё плохой слух."],
["demand","спрос; требование","n","There is a big demand for flats.","На квартиры большой спрос."],
["demand","требовать","v","They demanded an answer.","Они потребовали ответа."],
["division","разделение; отдел","n","The division of the money was fair.","Деньги разделили справедливо."],
["divide","разрыв, водораздел","n","There is a big divide between rich and poor.","Между богатыми и бедными большая пропасть."],
["delivery","доставка","n","Delivery takes three days.","Доставка занимает три дня."],
["decoration","украшение","n","We put up Christmas decorations.","Мы развесили рождественские украшения."],
["display","выставка, показ; экран","n","There is a display of old cars in the square.","На площади выставка старых машин."],
["display","показывать, выставлять","v","The shop displays its goods in the window.","Магазин выставляет товары в витрине."],
["draft","черновик","n","This is the first draft of my essay.","Это первый черновик моего сочинения."],
["draft","набрасывать, составлять","v","She drafted a letter to the manager.","Она набросала письмо менеджеру."],
["outline","план, набросок, очертание","n","Write an outline of your essay.","Напиши план сочинения."],
["outline","излагать в общих чертах","v","He outlined the plan.","Он изложил план в общих чертах."],
["phase","фаза, этап","n","The project is in its first phase.","Проект на первом этапе."],
["mission","миссия, задание","n","The mission was a success.","Миссия прошла успешно."],
["prospect","перспектива","n","The prospect of a holiday made her happy.","Перспектива отпуска её радовала."],
["opening","открытие; вакансия; отверстие","n","The opening of the new bridge is next week.","Открытие нового моста на следующей неделе."]
]},
{id:"b2-nouns-3", title:"Места и природа", words:[
["landscape","пейзаж, ландшафт","n","The landscape here is beautiful.","Пейзаж здесь красивый."],
["zone","зона","n","This is a no-parking zone.","Это зона, где парковка запрещена."],
["county","графство, округ","n","She lives in the county of Kent.","Она живёт в графстве Кент."],
["estate","поместье; жилой комплекс","n","They live on a housing estate.","Они живут в жилом комплексе."],
["housing","жильё","n","Housing is expensive in the capital.","Жильё в столице дорогое."],
["facility","объект, сооружение; возможности","n","The hotel has excellent sports facilities.","В отеле отличные спортивные сооружения."],
["institute","институт","n","She works at a research institute.","Она работает в исследовательском институте."],
["institution","учреждение","n","The university is an old institution.","Университет — старое учреждение."],
["venue","место проведения","n","The venue for the concert is the stadium.","Место проведения концерта — стадион."],
["resort","курорт","n","We stayed at a ski resort.","Мы остановились на горнолыжном курорте."],
["passage","проход; отрывок","n","A narrow passage leads to the garden.","Узкий проход ведёт в сад."],
["tunnel","туннель","n","The train went through a tunnel.","Поезд проехал через туннель."],
["barrier","барьер, преграда","n","Language is not a barrier for her.","Язык для неё не преграда."],
["slope","склон","n","The slope is very steep.","Склон очень крутой."],
["slope","иметь наклон","v","The road slopes down to the river.","Дорога спускается к реке."],
["stream","ручей; поток","n","We crossed a small stream.","Мы перешли маленький ручей."],
["shade","тень (прохлада); оттенок","n","Let's sit in the shade.","Давай сядем в тени."],
["shadow","тень (силуэт)","n","The tree cast a long shadow.","Дерево отбрасывало длинную тень."],
["bush","куст","n","A bird is hiding in the bush.","В кусте прячется птица."],
["root","корень","n","The roots of the tree are deep.","Корни дерева глубокие."],
["crop","урожай, сельскохозяйственная культура","n","Rice is the main crop here.","Рис — главная культура здесь."],
["tropical","тропический","adj","Bananas grow in tropical countries.","Бананы растут в тропических странах."],
["rural","сельский","adj","She loves rural life.","Она любит сельскую жизнь."],
["urban","городской","adj","Urban areas are crowded.","Городские районы переполнены."],
["domestic","домашний; внутренний (о стране)","adj","Domestic flights are cheap.","Внутренние рейсы дешёвые."],
["aircraft","воздушное судно, самолёт","n","The aircraft landed safely.","Самолёт благополучно приземлился."],
["shelter","укрытие, приют","n","We found shelter from the rain.","Мы нашли укрытие от дождя."],
["shelter","укрывать(ся)","v","We sheltered under a tree.","Мы укрылись под деревом."],
["heaven","рай, небеса","n","This place is heaven on earth.","Это место — рай на земле."],
["hell","ад","n","The traffic was hell this morning.","Пробки сегодня утром были адскими."]
]},
{id:"b2-nouns-4", title:"Измерение и форма", words:[
["angle","угол","n","Look at the picture from a different angle.","Посмотри на картину под другим углом."],
["curve","изгиб, кривая","n","There is a sharp curve in the road.","На дороге крутой поворот."],
["curve","изгибаться","v","The road curves to the left.","Дорога поворачивает налево."],
["curved","изогнутый","adj","The bridge has a curved shape.","У моста изогнутая форма."],
["depth","глубина","n","The depth of the lake is fifty metres.","Глубина озера — пятьдесят метров."],
["inch","дюйм","n","The snow was six inches deep.","Снег был глубиной шесть дюймов."],
["volume","объём; громкость","n","Turn down the volume.","Убавь громкость."],
["capacity","вместимость, мощность","n","The stadium has a capacity of fifty thousand.","Вместимость стадиона — пятьдесят тысяч."],
["scale","масштаб; шкала","n","The map has a scale of one to a thousand.","У карты масштаб один к тысяче."],
["mass","масса","n","The mass of the earth is enormous.","Масса Земли огромна."],
["mass","массовый","adj","Mass tourism changes small towns.","Массовый туризм меняет маленькие города."],
["sum","сумма","n","He paid a large sum of money.","Он заплатил большую сумму денег."],
["sum","суммировать, подводить итог","v","Let me sum up the main points.","Позвольте подвести итог основным пунктам."],
["maximum","максимум","n","The maximum is twenty people.","Максимум — двадцать человек."],
["maximum","максимальный","adj","The maximum speed is ninety.","Максимальная скорость — девяносто."],
["minimum","минимум","n","Keep the noise to a minimum.","Сведи шум к минимуму."],
["minimum","минимальный","adj","The minimum age is eighteen.","Минимальный возраст — восемнадцать."],
["majority","большинство","n","The majority of students passed.","Большинство студентов сдали."],
["minority","меньшинство","n","Only a minority voted against.","Только меньшинство проголосовало против."],
["rank","ранг, звание","n","He rose to the rank of captain.","Он дослужился до звания капитана."],
["rank","занимать место, ранжировать","v","The team is ranked third in the world.","Команда занимает третье место в мире."],
["rate","оценивать, расценивать","v","How do you rate this film?","Как ты оцениваешь этот фильм?"],
["pace","темп, скорость","n","She walks at a fast pace.","Она ходит быстрым шагом."],
["pace","шагать, ходить взад-вперёд","v","He paced the room nervously.","Он нервно ходил по комнате."],
["rhythm","ритм","n","I like the rhythm of this song.","Мне нравится ритм этой песни."],
["tone","тон","n","I did not like his tone.","Мне не понравился его тон."],
["tune","мелодия","n","She was humming a tune.","Она напевала мелодию."],
["pitch","высота (звука); поле; подача","n","The pitch of her voice rose.","Её голос стал выше."],
["genre","жанр","n","What genre of film do you like?","Какой жанр кино ты любишь?"]
]},
{id:"b2-nouns-5", title:"Разные существительные", words:[
["academic","учёный, преподаватель вуза","n","She is an academic at Oxford.","Она преподаватель в Оксфорде."],
["professional","профессионал","n","Leave it to the professionals.","Оставь это профессионалам."],
["official","чиновник, должностное лицо","n","Government officials arrived.","Прибыли государственные чиновники."],
["national","гражданин (страны)","n","Foreign nationals need a visa.","Иностранным гражданам нужна виза."],
["chief","глава, руководитель","n","The chief of police spoke to the press.","Начальник полиции обратился к прессе."],
["chief","главный","adj","Money was the chief reason.","Деньги были главной причиной."],
["aid","помощь","n","The country sent aid to the region.","Страна направила помощь в регион."],
["aid","помогать","v","The map aided us in finding the way.","Карта помогла нам найти дорогу."],
["bond","связь, узы; облигация","n","There is a strong bond between them.","Между ними крепкая связь."],
["league","лига","n","The team plays in the first league.","Команда играет в первой лиге."],
["contest","конкурс, состязание","n","She won a beauty contest.","Она выиграла конкурс красоты."],
["contest","оспаривать; бороться","v","He contested the decision.","Он оспорил решение."],
["classic","классический","adj","It is a classic film.","Это классический фильм."],
["classic","классика","n","This novel is a classic.","Этот роман — классика."],
["tale","сказка, рассказ","n","My grandmother told us tales.","Бабушка рассказывала нам сказки."],
["nightmare","кошмар","n","I had a nightmare last night.","Прошлой ночью мне снился кошмар."],
["anniversary","годовщина","n","Today is our wedding anniversary.","Сегодня годовщина нашей свадьбы."],
["flash","вспышка","n","We saw a flash of light.","Мы увидели вспышку света."],
["flash","вспыхивать, мигать","v","The lights flashed.","Огни замигали."],
["hunt","охота; поиски","n","The hunt for the thief continues.","Поиски вора продолжаются."],
["hunting","охота","n","Hunting is banned in the park.","Охота в парке запрещена."],
["hire","прокат, наём","n","Bikes are available for hire.","Велосипеды можно взять напрокат."],
["leave","отпуск","n","She is on maternity leave.","Она в декретном отпуске."],
["catch","улов; уловка","n","The fishermen brought in a good catch.","Рыбаки привезли хороший улов."],
["beat","ритм, удар","n","I like the beat of this music.","Мне нравится ритм этой музыки."],
["cry","крик, плач","n","We heard a cry for help.","Мы услышали крик о помощи."],
["fold","складка","n","The paper has a fold in the middle.","У бумаги сгиб посередине."],
["folding","складной","adj","We took folding chairs to the beach.","Мы взяли на пляж складные стулья."],
["feed","корм; подача","n","The animals need their feed.","Животным нужен корм."],
["feel","ощущение, атмосфера","n","The town has a friendly feel.","В городе дружелюбная атмосфера."]
]},
{id:"b2-adj-1", title:"Оценка и важность", words:[
["accurate","точный","adj","The clock is not accurate.","Часы неточные."],
["acceptable","приемлемый","adj","This behaviour is not acceptable.","Такое поведение неприемлемо."],
["appropriate","подходящий, уместный","adj","Wear appropriate clothes for the interview.","Надень подходящую одежду на собеседование."],
["reasonable","разумный, приемлемый","adj","The price is reasonable.","Цена разумная."],
["realistic","реалистичный","adj","Be realistic about your goals.","Смотри на свои цели реалистично."],
["relevant","относящийся к делу, актуальный","adj","Your question is not relevant.","Твой вопрос не по теме."],
["significant","значительный, важный","adj","There was a significant change.","Произошло значительное изменение."],
["crucial","решающий, ключевой","adj","This is a crucial moment.","Это решающий момент."],
["vital","жизненно важный","adj","Water is vital for life.","Вода жизненно необходима."],
["fundamental","основополагающий","adj","Trust is fundamental in a friendship.","Доверие — основа дружбы."],
["critical","критический; критикующий","adj","The patient is in a critical condition.","Пациент в критическом состоянии."],
["efficient","эффективный, экономичный","adj","The new engine is more efficient.","Новый двигатель более экономичный."],
["capable","способный","adj","She is capable of great things.","Она способна на великие дела."],
["consistent","последовательный, стабильный","adj","Her work is consistent.","Она работает стабильно."],
["logical","логичный","adj","That is a logical answer.","Это логичный ответ."],
["decent","приличный, порядочный","adj","He earns a decent salary.","Он получает приличную зарплату."],
["extraordinary","необычайный","adj","She has an extraordinary memory.","У неё необычайная память."],
["dramatic","драматический, резкий","adj","There was a dramatic change in the weather.","Погода резко изменилась."],
["intense","интенсивный, сильный","adj","The heat was intense.","Жара была невыносимой."],
["severe","суровый, серьёзный","adj","The winter was severe.","Зима была суровой."],
["massive","огромный, массивный","adj","The company made a massive profit.","Компания получила огромную прибыль."],
["vast","обширный, огромный","adj","Russia is a vast country.","Россия — огромная страна."],
["numerous","многочисленный","adj","There were numerous mistakes.","Было множество ошибок."],
["multiple","многочисленный, множественный","adj","She has multiple injuries.","У неё множественные травмы."],
["additional","дополнительный","adj","There is an additional charge for breakfast.","За завтрак взимается дополнительная плата."],
["limited","ограниченный","adj","We have limited time.","У нас ограниченное время."],
["minor","незначительный, мелкий","adj","It was a minor problem.","Это была небольшая проблема."],
["slight","небольшой, лёгкий","adj","There has been a slight increase in price.","Цена немного выросла."],
["absolute","абсолютный, полный","adj","It is an absolute disaster.","Это полная катастрофа."],
["complicated","сложный, запутанный","adj","The rules are complicated.","Правила запутанные."]
]},
{id:"b2-adj-2", title:"Состояние и вид", words:[
["stable","стабильный, устойчивый","adj","The patient is in a stable condition.","Состояние пациента стабильное."],
["steady","устойчивый, постоянный","adj","She has a steady job.","У неё постоянная работа."],
["constant","постоянный","adj","The noise was constant.","Шум был постоянным."],
["permanent","постоянный, бессрочный","adj","She has a permanent job.","У неё постоянная работа."],
["temporary","временный","adj","This is a temporary solution.","Это временное решение."],
["former","бывший","adj","He is my former teacher.","Он мой бывший учитель."],
["initial","первоначальный","adj","My initial reaction was surprise.","Моей первой реакцией было удивление."],
["prime","главный, основной","adj","Health is of prime importance.","Здоровье имеет первостепенное значение."],
["entire","целый, весь","adj","I spent the entire day at home.","Я провёл весь день дома."],
["pure","чистый","adj","This is pure gold.","Это чистое золото."],
["raw","сырой","adj","Do not eat raw meat.","Не ешь сырое мясо."],
["hollow","полый, пустой","adj","The tree is hollow inside.","Дерево внутри полое."],
["loose","свободный, незакреплённый","adj","This button is loose.","Эта пуговица болтается."],
["stiff","жёсткий, негнущийся","adj","My neck is stiff.","У меня затекла шея."],
["sticky","липкий","adj","My hands are sticky.","У меня липкие руки."],
["bent","согнутый","adj","The fork is bent.","Вилка погнута."],
["pointed","заострённый","adj","The knife has a pointed end.","У ножа заострённый конец."],
["steep","крутой","adj","The hill is very steep.","Холм очень крутой."],
["shallow","мелкий, неглубокий","adj","The water is shallow here.","Вода здесь мелкая."],
["broad","широкий","adj","He has broad shoulders.","У него широкие плечи."],
["brief","краткий","adj","She gave a brief answer.","Она дала краткий ответ."],
["neat","аккуратный, опрятный","adj","His room is always neat.","Его комната всегда опрятная."],
["plain","простой, однотонный; ясный","adj","She wore a plain white dress.","На ней было простое белое платье."],
["bitter","горький","adj","The coffee is too bitter.","Кофе слишком горький."],
["mixed","смешанный","adj","I have mixed feelings about it.","У меня смешанные чувства по этому поводу."],
["matching","подходящий, сочетающийся","adj","She wore a hat and matching gloves.","На ней были шляпа и подходящие перчатки."],
["even","ровный; чётный","adj","Two, four and six are even numbers.","Два, четыре и шесть — чётные числа."],
["holy","святой, священный","adj","This is a holy place.","Это святое место."],
["grand","грандиозный, величественный","adj","They live in a grand house.","Они живут в роскошном доме."],
["mysterious","таинственный","adj","She received a mysterious letter.","Она получила таинственное письмо."]
]},
{id:"b2-adj-3", title:"Признаки и свойства", words:[
["actual","фактический, реальный","adj","The actual price was higher.","Реальная цена была выше."],
["apparent","очевидный, кажущийся","adj","It was apparent that he was tired.","Было очевидно, что он устал."],
["deliberate","намеренный","adj","It was a deliberate mistake.","Это была намеренная ошибка."],
["intended","предназначенный, задуманный","adj","The book is intended for children.","Книга предназначена для детей."],
["concerned","обеспокоенный; имеющий отношение","adj","I am concerned about her health.","Я обеспокоен её здоровьем."],
["confusing","сбивающий с толку","adj","The instructions are confusing.","Инструкции сбивают с толку."],
["sensitive","чувствительный","adj","She has sensitive skin.","У неё чувствительная кожа."],
["flexible","гибкий","adj","We have flexible working hours.","У нас гибкий график работы."],
["artistic","художественный, артистичный","adj","She has artistic talent.","У неё художественный талант."],
["contemporary","современный","adj","We visited a museum of contemporary art.","Мы посетили музей современного искусства."],
["annual","ежегодный","adj","The annual meeting is in May.","Ежегодное собрание в мае."],
["routine","обычный, рутинный","adj","It was a routine check.","Это была плановая проверка."],
["long-term","долгосрочный","adj","We need a long-term plan.","Нам нужен долгосрочный план."],
["long-term","в долгосрочной перспективе","adv","The plan works better long-term.","В долгосрочной перспективе план работает лучше."],
["unique","уникальный","adj","Every person is unique.","Каждый человек уникален."],
["unknown","неизвестный","adj","The cause of the fire is unknown.","Причина пожара неизвестна."],
["unexpected","неожиданный","adj","We had an unexpected visitor.","У нас был неожиданный гость."],
["forward","передний, направленный вперёд","adj","The forward seats are more expensive.","Передние места дороже."],
["inner","внутренний","adj","The inner door was locked.","Внутренняя дверь была заперта."],
["outer","внешний, наружный","adj","The outer wall is made of stone.","Наружная стена сделана из камня."],
["internal","внутренний","adj","The company has internal problems.","У компании внутренние проблемы."],
["external","внешний","adj","The building needs external repairs.","Зданию нужен наружный ремонт."],
["upper","верхний","adj","The upper floors have a good view.","С верхних этажей хороший вид."],
["core","основной, центральный","adj","Reading is a core skill.","Чтение — ключевой навык."],
["core","ядро, суть; сердцевина","n","Let's get to the core of the problem.","Давайте перейдём к сути проблемы."],
["visual","зрительный, визуальный","adj","The film has great visual effects.","В фильме отличные визуальные эффекты."],
["material","материальный, вещественный","adj","Money brings material comfort.","Деньги приносят материальный комфорт."],
["regional","региональный","adj","There are many regional differences.","Есть много региональных различий."],
["subject","подверженный; подлежащий","adj","Prices are subject to change.","Цены могут меняться."],
["very","тот самый, самый","adj","This is the very book I wanted.","Это та самая книга, которую я хотел."]
]},
{id:"b2-adverbs-1", title:"Наречия и связки", words:[
["apparently","по-видимому","adv","Apparently, the shop is closed.","По-видимому, магазин закрыт."],
["basically","в основном, по сути","adv","Basically, we need more time.","По сути, нам нужно больше времени."],
["commonly","обычно, часто","adv","This word is commonly used.","Это слово часто используется."],
["constantly","постоянно","adv","He is constantly late.","Он постоянно опаздывает."],
["closely","близко, внимательно","adv","Watch closely.","Смотри внимательно."],
["deeply","глубоко","adv","I am deeply sorry.","Я глубоко сожалею."],
["deliberately","намеренно","adv","He deliberately ignored me.","Он намеренно проигнорировал меня."],
["entirely","полностью","adv","I entirely agree.","Я полностью согласен."],
["fully","полностью","adv","I fully understand.","Я полностью понимаю."],
["gradually","постепенно","adv","The weather gradually improved.","Погода постепенно улучшилась."],
["increasingly","всё больше","adv","It is becoming increasingly difficult.","Это становится всё труднее."],
["initially","изначально","adv","Initially, I did not like the idea.","Сначала мне не понравилась идея."],
["largely","в основном","adv","The success was largely due to her.","Успех был в основном благодаря ей."],
["partly","частично","adv","It was partly my fault.","Это была отчасти моя вина."],
["relatively","относительно","adv","The test was relatively easy.","Тест был относительно лёгким."],
["significantly","значительно","adv","Prices rose significantly.","Цены значительно выросли."],
["rapidly","быстро","adv","The city is growing rapidly.","Город быстро растёт."],
["rapid","быстрый","adj","There was a rapid change.","Произошло быстрое изменение."],
["somewhat","несколько, отчасти","adv","The film was somewhat boring.","Фильм был несколько скучным."],
["truly","действительно, по-настоящему","adv","It was a truly wonderful evening.","Это был поистине чудесный вечер."],
["ultimately","в конечном счёте","adv","Ultimately, the decision is yours.","В конечном счёте, решать тебе."],
["widely","широко","adv","English is widely spoken.","Английский широко распространён."],
["occasionally","изредка","adv","I occasionally eat meat.","Я изредка ем мясо."],
["afterwards","потом, впоследствии","adv","We had dinner and went for a walk afterwards.","Мы поужинали, а потом пошли гулять."],
["elsewhere","в другом месте","adv","The shop was closed, so we went elsewhere.","Магазин был закрыт, поэтому мы пошли в другое место."],
["otherwise","иначе, в противном случае","adv","Hurry up, otherwise we will be late.","Поторопись, иначе мы опоздаем."],
["thus","таким образом","adv","Thus, the problem was solved.","Таким образом, проблема была решена."],
["nevertheless","тем не менее","adv","It was raining; nevertheless, we went out.","Шёл дождь; тем не менее, мы вышли."],
["furthermore","более того","adv","The house is big. Furthermore, it has a garden.","Дом большой. Более того, при нём есть сад."],
["whereas","тогда как","conj","I like tea, whereas my brother prefers coffee.","Я люблю чай, тогда как мой брат предпочитает кофе."]
]},
{id:"b2-verbs-6", title:"Глаголы от существительных", words:[
["account","объяснять; составлять (долю)","v","Tourism accounts for half of the income.","Туризм составляет половину дохода."],
["address","обращаться к; решать (проблему)","v","The report addresses the problem of pollution.","Отчёт рассматривает проблему загрязнения."],
["alarm","тревожить, пугать","v","The news alarmed everyone.","Новость всех встревожила."],
["amount","составлять (в сумме)","v","The bill amounted to a hundred euros.","Счёт составил сто евро."],
["back","поддерживать; сдавать назад","v","Her parents backed her decision.","Родители поддержали её решение."],
["bar","запрещать, преграждать","v","They bar dogs from the beach.","Собак на пляж не пускают."],
["bill","выставлять счёт","v","The hotel billed us for the drinks.","Отель выставил нам счёт за напитки."],
["border","граничить","v","France borders Spain.","Франция граничит с Испанией."],
["chain","приковывать цепью","v","He chained the bike to the fence.","Он пристегнул велосипед цепью к забору."],
["chair","председательствовать","v","She chaired the meeting.","Она вела собрание."],
["challenge","бросать вызов, оспаривать","v","He challenged me to a game of chess.","Он вызвал меня на партию в шахматы."],
["chart","отображать, отслеживать","v","The book charts the history of the city.","Книга прослеживает историю города."],
["credit","зачислять; приписывать","v","The money was credited to my account.","Деньги были зачислены на мой счёт."],
["date","датировать; встречаться","v","The church dates from the twelfth century.","Церковь датируется двенадцатым веком."],
["detail","подробно описывать","v","The report details the changes.","В отчёте подробно описаны изменения."],
["discount","делать скидку; не принимать во внимание","v","The shop discounts old stock.","Магазин делает скидку на старый товар."],
["document","документировать","v","The film documents life in the village.","Фильм документирует жизнь деревни."],
["favour","предпочитать, благоприятствовать","v","I favour the second plan.","Я предпочитаю второй план."],
["figure","полагать; фигурировать","v","I figure we will arrive at six.","Полагаю, мы приедем в шесть."],
["file","подавать (документы); подшивать","v","She filed a complaint.","Она подала жалобу."],
["free","освобождать","v","The prisoners were freed.","Заключённых освободили."],
["fuel","заправлять; подпитывать","v","Such news only fuels anger.","Такие новости только подогревают гнев."],
["function","функционировать","v","The machine functions well.","Машина хорошо работает."],
["grade","оценивать, сортировать","v","The teacher graded the tests.","Учитель проверил тесты."],
["harm","вредить","v","Smoking harms your health.","Курение вредит здоровью."],
["harm","вред","n","The storm did a lot of harm.","Буря нанесла большой вред."],
["harmful","вредный","adj","Sugar is harmful in large amounts.","Сахар вреден в больших количествах."],
["host","принимать (гостей, мероприятие)","v","The city hosted the games.","Город принимал игры."],
["house","размещать, вмещать","v","The building houses a museum.","В здании размещается музей."],
["issue","выпускать, выдавать","v","The police issued a warning.","Полиция выпустила предупреждение."]
]},
{id:"b2-verbs-7", title:"Ещё глаголы от существительных", words:[
["launch","запускать, начинать","v","The company launched a new product.","Компания запустила новый продукт."],
["launch","запуск, начало","n","The launch of the book is next week.","Презентация книги на следующей неделе."],
["level","выравнивать","v","Level the ground before you build.","Выровняй землю, прежде чем строить."],
["line","выстраивать(ся); подкладывать","v","People lined the streets to see the parade.","Люди выстроились вдоль улиц, чтобы увидеть парад."],
["map","наносить на карту","v","Scientists map the ocean floor.","Учёные наносят на карту дно океана."],
["mistake","ошибочно принимать","v","People often mistake him for his brother.","Люди часто принимают его за брата."],
["model","моделировать; демонстрировать","v","She models clothes for a magazine.","Она демонстрирует одежду для журнала."],
["object","возражать","v","I object to this plan.","Я возражаю против этого плана."],
["package","упаковывать","v","The goods are packaged in boxes.","Товары упакованы в коробки."],
["picture","представлять себе","v","Picture yourself on a beach.","Представь себя на пляже."],
["plot","замышлять; строить график","v","They plot against the king.","Они замышляют заговор против короля."],
["pose","представлять (угрозу); позировать","v","Pollution poses a threat to health.","Загрязнение представляет угрозу здоровью."],
["position","располагать, размещать","v","Position the camera near the window.","Расположи камеру у окна."],
["power","приводить в действие","v","The car is powered by electricity.","Машина работает на электричестве."],
["price","назначать цену","v","The tickets are priced at ten euros.","Билеты стоят десять евро."],
["process","обрабатывать","v","The computer processes the data.","Компьютер обрабатывает данные."],
["progress","продвигаться, прогрессировать","v","The work is progressing well.","Работа идёт хорошо."],
["project","проецировать; прогнозировать","v","Sales are projected to rise.","Прогнозируется рост продаж."],
["range","варьироваться, колебаться","v","Prices range from ten to fifty euros.","Цены варьируются от десяти до пятидесяти евро."],
["reserve","бронировать; сохранять","v","I reserved a table for two.","Я забронировал столик на двоих."],
["reserve","запас; заповедник","n","We keep a reserve of food.","Мы держим запас еды."],
["sample","пробовать, брать образец","v","We sampled the local food.","Мы попробовали местную еду."],
["screen","показывать на экране; проверять","v","The film was screened at the festival.","Фильм показали на фестивале."],
["seat","усаживать; вмещать","v","The hall seats five hundred people.","Зал вмещает пятьсот человек."],
["sense","чувствовать, ощущать","v","I sensed that something was wrong.","Я почувствовал, что что-то не так."],
["sentence","приговаривать","v","He was sentenced to five years in prison.","Его приговорили к пяти годам тюрьмы."],
["shape","формировать","v","Childhood shapes our character.","Детство формирует наш характер."],
["shift","сдвигать(ся), перемещать","v","Shift the table to the left.","Сдвинь стол влево."],
["ship","отправлять, перевозить","v","We ship goods to Europe.","Мы отправляем товары в Европу."],
["speed","мчаться, ускорять","v","Do not speed on this road.","Не превышай скорость на этой дороге."]
]},
{id:"b2-verbs-8", title:"Последние глаголы и наречия", words:[
["spot","замечать","v","Can you spot the mistake?","Можешь заметить ошибку?"],
["stage","организовывать, устраивать","v","The students staged a play.","Студенты поставили спектакль."],
["step","шагать, ступать","v","Step back, please.","Отойди назад, пожалуйста."],
["stuff","набивать, запихивать","v","He stuffed the papers into his bag.","Он запихнул бумаги в сумку."],
["survey","проводить опрос; осматривать","v","We surveyed a hundred customers.","Мы опросили сто покупателей."],
["target","нацеливать","v","The ad targets young people.","Реклама нацелена на молодёжь."],
["term","называть, именовать","v","The style is termed «modern».","Этот стиль называют «современным»."],
["time","рассчитывать по времени, засекать","v","The teacher timed the test.","Учитель засёк время теста."],
["title","озаглавливать","v","The book is titled «Winter».","Книга озаглавлена «Зима»."],
["track","отслеживать","v","The police tracked the car.","Полиция отследила машину."],
["trip","спотыкаться","v","Be careful not to trip on the step.","Осторожно, не споткнись о ступеньку."],
["trouble","беспокоить","v","Sorry to trouble you.","Извините за беспокойство."],
["value","ценить; оценивать","v","I value your opinion.","Я ценю твоё мнение."],
["advance","продвигаться; продвигать","v","The army advanced towards the city.","Армия продвигалась к городу."],
["advance","продвижение, прогресс; аванс","n","There have been great advances in medicine.","В медицине произошёл большой прогресс."],
["advance","предварительный","adj","We need advance notice.","Нам нужно предварительное уведомление."],
["approach","приближаться; подходить (к вопросу)","v","Winter is approaching.","Приближается зима."],
["approach","подход; приближение","n","We need a new approach to the problem.","Нам нужен новый подход к проблеме."],
["collapse","рушиться, падать","v","The old bridge collapsed.","Старый мост обрушился."],
["collapse","обрушение, крах","n","The collapse of the company shocked everyone.","Крах компании всех потряс."],
["concern","беспокойство; забота, дело","n","There is growing concern about pollution.","Растёт обеспокоенность загрязнением."],
["concern","беспокоить; касаться","v","This problem concerns us all.","Эта проблема касается всех нас."],
["cast","бросать; распределять роли","v","The film was cast in a month.","Актёров для фильма подобрали за месяц."],
["cast","актёрский состав","n","The cast of the film is excellent.","Актёрский состав фильма великолепен."],
["downwards","вниз","adv","The path leads downwards to the river.","Тропа ведёт вниз к реке."],
["upwards","вверх","adv","The plane climbed upwards.","Самолёт набирал высоту."],
["overall","общий, в целом","adj","The overall cost was low.","Общая стоимость была низкой."],
["overall","в целом","adv","Overall, the trip was a success.","В целом поездка удалась."],
["way","намного, далеко","adv","The price is way too high.","Цена слишком уж высокая."],
["beyond","за пределами, вне","prep","The shop is just beyond the church.","Магазин сразу за церковью."]
]},
{id:"b2-misc", title:"Остальные слова", words:[
["beyond","дальше, вдали","adv","The road continues to the hills and beyond.","Дорога ведёт к холмам и дальше."],
["but","кроме","prep","Everyone but me was late.","Все, кроме меня, опоздали."],
["following","после, вслед за","prep","Following the meeting, we had lunch.","После собрания мы пообедали."],
["via","через","prep","We flew to Rome via Paris.","Мы летели в Рим через Париж."],
["plus","плюс (наречие/союз)","conj","She is clever, plus she works hard.","Она умна, к тому же много работает."],
["plus","положительный, плюсовой","adj","The temperature is plus five.","Температура плюс пять."],
["plus","плюс (преимущество)","n","Living near the sea is a plus.","Жить у моря — это плюс."],
["yet","но, однако","conj","It is simple, yet effective.","Это просто, но эффективно."],
["wherever","где бы ни, куда бы ни","conj","Sit wherever you like.","Садись, где хочешь."],
["whom","кого, кому","pron","To whom did you give the key?","Кому ты отдал ключ?"],
["close","конец, завершение","n","The meeting came to a close.","Собрание подошло к концу."],
["complex","комплекс","n","There is a new sports complex in town.","В городе новый спортивный комплекс."],
["current","течение; ток","n","The current in the river is strong.","Течение в реке сильное."],
["equal","равный, ровня","n","He treats everyone as an equal.","Он относится ко всем как к равным."],
["extreme","крайность","n","She goes from one extreme to the other.","Она бросается из одной крайности в другую."],
["fix","затруднительное положение; доза","n","We are in a bit of a fix.","Мы в затруднительном положении."],
["high","максимум, высшая точка","n","Prices reached a new high.","Цены достигли нового максимума."],
["low","минимум, низшая точка","n","Sales hit a new low.","Продажи упали до нового минимума."],
["hold","хватка; удержание","n","Keep a firm hold on the rope.","Крепко держи верёвку."],
["ideal","идеал","n","Peace is an ideal worth working for.","Мир — идеал, ради которого стоит работать."],
["latest","самое новое, последнее","n","Have you heard the latest?","Слышал последние новости?"],
["make","марка, модель","n","What make is your car?","Какой марки твоя машина?"],
["medium","средство, среда","n","Television is a powerful medium.","Телевидение — мощное средство коммуникации."],
["negative","отрицательный ответ; негатив","n","The answer was a negative.","Ответ был отрицательным."],
["positive","положительная сторона, плюс","n","Let's focus on the positives.","Давайте сосредоточимся на положительных сторонах."]
]},
{id:"b2-misc-2", title:"Ещё существительные", words:[
["pick","выбор","n","Take your pick.","Выбирай."],
["potential","потенциальный, возможный","adj","There is a potential problem.","Есть потенциальная проблема."],
["potential","потенциал","n","She has great potential.","У неё большой потенциал."],
["produce","продукция, продукты (сельскохозяйственные)","n","The market sells fresh local produce.","На рынке продают свежие местные продукты."],
["reach","досягаемость, пределы","n","Keep medicines out of children's reach.","Держите лекарства в недоступном для детей месте."],
["round","раунд; обход","n","He won the first round.","Он выиграл первый раунд."],
["silence","тишина, молчание","n","There was silence in the room.","В комнате стояла тишина."],
["spread","распространение","n","The spread of the disease was rapid.","Болезнь распространялась быстро."],
["stand","стенд, стойка; позиция","n","We had a stand at the exhibition.","У нас был стенд на выставке."],
["try","попытка","n","Let me have a try.","Дай мне попробовать."],
["worse","худшее","n","Things changed for the worse.","Дела изменились к худшему."],
["worst","самое худшее","n","The worst is over.","Худшее позади."],
["worth","ценность, стоимость","n","I bought ten euros' worth of fruit.","Я купил фруктов на десять евро."],
["wrong","зло, неправда","n","He does not know right from wrong.","Он не отличает добро от зла."],
["detailed","подробный","adj","She gave a detailed description.","Она дала подробное описание."]
]}
],
practice:{
"insist|v":{collocations:[["insist on","настаивать на"]],examples:[["He insists on paying for dinner.","Он настаивает на том, чтобы заплатить за ужин."]]},
"rely|v":{collocations:[["rely on","полагаться на"]],examples:[["We rely on public transport.","Мы полагаемся на общественный транспорт."]]},
"budget|n":{collocations:[["on a budget","с ограниченным бюджетом"],["a tight budget","жёсткий бюджет"]],examples:[["We are travelling on a tight budget.","Мы путешествуем с ограниченным бюджетом."]]},
"debt|n":{collocations:[["in debt","в долгах"],["pay off a debt","выплатить долг"]],examples:[["It took years to pay off the debt.","На выплату долга ушли годы."]]},
"contract|n":{collocations:[["sign a contract","подписать контракт"],["under contract","по контракту"]],examples:[["The player is under contract until June.","Игрок под контрактом до июня."]]},
"priority|n":{collocations:[["top priority","главный приоритет"],["give priority to","отдавать приоритет"]],examples:[["We give priority to safety.","Мы отдаём приоритет безопасности."]]},
"attempt|n":{collocations:[["make an attempt","предпринять попытку"],["a failed attempt","неудачная попытка"]],examples:[["He made several attempts to call her.","Он несколько раз пытался ей дозвониться."]]},
"threat|n":{collocations:[["pose a threat","представлять угрозу"],["under threat","под угрозой"]],examples:[["Many species are under threat.","Многие виды под угрозой."]]},
"conflict|n":{collocations:[["in conflict with","в конфликте с"],["resolve a conflict","разрешить конфликт"]],examples:[["The two ideas are in conflict.","Эти две идеи противоречат друг другу."]]},
"gain|v":{collocations:[["gain weight","набирать вес"],["gain experience","набираться опыта"]],examples:[["She gained a lot of experience in the job.","На этой работе она набралась большого опыта."]]},
"blame|v":{collocations:[["blame somebody for","винить кого-то за"],["blame something on","списывать на"]],examples:[["They blamed the delay on the weather.","Задержку списали на погоду."]]},
"accuse|v":{collocations:[["accuse somebody of","обвинять кого-то в"]],examples:[["She accused him of stealing.","Она обвинила его в краже."]]},
"associate|v":{collocations:[["associate with","ассоциировать с"]],examples:[["We associate red with danger.","Красный у нас ассоциируется с опасностью."]]},
"contribute|v":{collocations:[["contribute to","способствовать, вносить вклад в"]],examples:[["Stress contributes to illness.","Стресс способствует болезням."]]},
"engage|v":{collocations:[["engage in","заниматься, участвовать в"]],examples:[["She engages in many activities.","Она участвует во многих занятиях."]]},
"struggle|v":{collocations:[["struggle with","с трудом справляться с"],["struggle to do","с трудом делать"]],examples:[["Many students struggle with grammar.","Многие ученики с трудом справляются с грамматикой."]]},
"regard|v":{collocations:[["regard as","считать кем-то/чем-то"]],examples:[["She is regarded as an expert.","Её считают экспертом."]]},
"recover|v":{collocations:[["recover from","оправиться от"]],examples:[["He recovered from the illness quickly.","Он быстро оправился от болезни."]]},
"appeal|v":{collocations:[["appeal to","обращаться к; нравиться"],["appeal for","призывать к"]],examples:[["The charity appealed for help.","Благотворительная организация обратилась за помощью."]]},
"capable|adj":{collocations:[["capable of","способный на"]],examples:[["He is capable of running a marathon.","Он способен пробежать марафон."]]},
"anxious|adj":{collocations:[["anxious about","обеспокоенный чем-то"]],examples:[["Parents are anxious about the exams.","Родители беспокоятся из-за экзаменов."]]},
"ashamed|adj":{collocations:[["ashamed of","стыдящийся чего-то"]],examples:[["He is ashamed of his behaviour.","Ему стыдно за своё поведение."]]},
"concerned|adj":{collocations:[["concerned about","обеспокоенный"],["as far as I am concerned","что касается меня"]],examples:[["As far as I am concerned, the matter is closed.","Что касается меня, вопрос закрыт."]]},
"relevant|adj":{collocations:[["relevant to","относящийся к"]],examples:[["Is this relevant to the topic?","Это относится к теме?"]]},
"consistent|adj":{collocations:[["consistent with","согласующийся с"]],examples:[["His story is consistent with the facts.","Его рассказ согласуется с фактами."]]},
"willing|adj":{collocations:[["willing to","готовый сделать"]],examples:[["I am willing to wait.","Я готов подождать."]]},
"beyond|prep":{collocations:[["beyond belief","невероятно"],["beyond control","вне контроля"]],examples:[["The situation is beyond our control.","Ситуация вне нашего контроля."]]},
"via|prep":{collocations:[["via email","по электронной почте"]],examples:[["Send it to me via email.","Отправь мне это по электронной почте."]]}
},
confusables:[
["gain|v","earn|v"],["obtain|v","get|v"],["acquire|v","buy|v"],["seek|v","search|v"],["pursue|v","follow|v"],
["assure|v","ensure|v"],["maintain|v","keep|v"],["retain|v","remain|v"],["preserve|v","protect|v"],
["accurate|adj","exact|adj"],["efficient|adj","effective|adj"],["significant|adj","important|adj"],["crucial|adj","vital|adj"],["massive|adj","huge|adj"],
["temporary|adj","permanent|adj"],["former|adj","previous|adj"],["initial|adj","first|det"],["entire|adj","whole|adj"],["numerous|adj","many|det"],
["accuse|v","blame|v"],["deny|v","refuse|v"],["declare|v","announce|v"],["acknowledge|v","admit|v"],["imply|v","suggest|v"],
["criticize|v","complain|v"],["urge|v","advise|v"],["inform|v","tell|v"],["reveal|v","show|v"],["recall|v","remember|v"],
["decline|v","decrease|v"],["decline|v","refuse|v"],["lower|v","reduce|v"],["alter|v","change|v"],["convert|v","transform|v"],
["expense|n","cost|n"],["wage|n","salary|n"],["fee|n","price|n"],["debt|n","loan|n"],["income|n","profit|n"],
["failure|n","mistake|n"],["fault|n","mistake|n"],["harm|n","damage|n"],["threat|n","danger|n"],["crisis|n","problem|n"],
["anxious|adj","nervous|adj"],["ashamed|adj","embarrassed|adj"],["willing|adj","ready|adj"],["sincere|adj","honest|adj"],
["thus|adv","therefore|adv"],["nevertheless|adv","however|adv"],["furthermore|adv","also|adv"],["whereas|conj","while|conj"],["otherwise|adv","or|conj"],
["apparently|adv","obviously|adv"],["entirely|adv","completely|adv"],["largely|adv","mainly|adv"],["relatively|adv","fairly|adv"],["somewhat|adv","slightly|adv"],
["tear|n|drop","tear|n|rip"],["shade|n","shadow|n"],["stream|n","river|n"],["steep|adj","high|adj"],["shallow|adj","low|adj"]
]
};
if(typeof module!=="undefined")module.exports=OXFORD_B2;
