// Oxford 3000, уровень B1: 907 единиц (слово + часть речи) в тематических блоках. Источник списка и уровней —
// tools/oxford-3000.json; проверка: node tools/program-check.js B1. Уточнение (6-й элемент) есть только у значений,
// которые Oxford разделяет (rest|n|relax). practice — дополнительные примеры и сочетания, confusables — близкие пары.
// Формат записи: [слово, перевод, часть речи, пример, перевод примера, уточнение?]
const OXFORD_B1 = {level:"B1", blocks:[
{id:"b1-body-health", title:"Тело, здоровье и лечение", words:[
["chest","грудь, грудная клетка","n","He has a pain in his chest.","У него боль в груди."],
["throat","горло","n","I have a sore throat.","У меня болит горло."],
["tongue","язык (орган)","n","The soup burned my tongue.","Суп обжёг мне язык."],
["lip","губа","n","She bit her lip.","Она прикусила губу."],
["toe","палец ноги","n","I hurt my toe on the door.","Я ударился пальцем ноги о дверь."],
["nail","ноготь; гвоздь","n","She painted her nails red.","Она накрасила ногти красным."],
["muscle","мышца","n","Exercise makes your muscles stronger.","Упражнения укрепляют мышцы."],
["breath","дыхание, вдох","n","Take a deep breath.","Сделай глубокий вдох."],
["breathe","дышать","v","It is hard to breathe in this heat.","В такую жару трудно дышать."],
["breathing","дыхание","n","Her breathing was slow and calm.","Её дыхание было медленным и спокойным."],
["symptom","симптом","n","Fever is a symptom of flu.","Жар — симптом гриппа."],
["treat","лечить; обращаться; угощать","v","The doctor treated my injury.","Врач лечил мою травму."],
["treatment","лечение","n","The treatment lasts two weeks.","Лечение длится две недели."],
["injure","ранить, травмировать","v","He injured his leg in the game.","Он повредил ногу в игре."],
["injured","травмированный, раненый","adj","The injured man was taken to hospital.","Пострадавшего отвезли в больницу."],
["painful","болезненный","adj","The injection was painful.","Укол был болезненным."],
["suffer","страдать","v","She suffers from headaches.","Она страдает от головных болей."],
["emergency","чрезвычайная ситуация, экстренный случай","n","In an emergency, call 112.","В экстренной ситуации звоните 112."],
["mental","умственный, психический","adj","Mental health is as important as physical health.","Психическое здоровье так же важно, как и физическое."],
["fitness","физическая форма","n","Swimming is good for fitness.","Плавание полезно для физической формы."],
["weigh","весить, взвешивать","v","How much do you weigh?","Сколько ты весишь?"],
["poison","яд","n","This plant contains poison.","Это растение содержит яд."],
["poison","отравлять","v","The chemicals poisoned the river.","Химикаты отравили реку."],
["poisonous","ядовитый","adj","Some mushrooms are poisonous.","Некоторые грибы ядовиты."],
["drunk","пьяный","adj","He was drunk after the party.","После вечеринки он был пьян."],
["alcohol","алкоголь","n","She does not drink alcohol.","Она не пьёт алкоголь."],
["alcoholic","алкогольный","adj","Beer is an alcoholic drink.","Пиво — алкогольный напиток."]
]},
{id:"b1-emotions", title:"Эмоции и настроение", words:[
["emotion","эмоция","n","She showed no emotion.","Она не показала никаких эмоций."],
["mood","настроение","n","He is in a good mood today.","Сегодня он в хорошем настроении."],
["happiness","счастье","n","Money cannot buy happiness.","За деньги счастье не купишь."],
["pleasure","удовольствие","n","It is a pleasure to meet you.","Рад с вами познакомиться."],
["excitement","волнение, восторг","n","The children screamed with excitement.","Дети кричали от восторга."],
["passion","страсть, увлечение","n","Music is his passion.","Музыка — его страсть."],
["amazed","поражённый, изумлённый","adj","I was amazed by the view.","Я был поражён видом."],
["glad","рад","adj","I am glad you came.","Я рад, что ты пришёл."],
["cheerful","весёлый, жизнерадостный","adj","She is always cheerful.","Она всегда жизнерадостная."],
["calm","спокойный","adj","Stay calm and do not panic.","Сохраняй спокойствие и не паникуй."],
["calm","успокаивать","v","Music calms me.","Музыка меня успокаивает."],
["calm","спокойствие, штиль","n","After the storm came the calm.","После бури наступило затишье."],
["relaxed","расслабленный","adj","I feel relaxed after a holiday.","После отпуска я чувствую себя расслабленным."],
["relaxing","расслабляющий","adj","We had a relaxing weekend.","У нас были спокойные выходные."],
["upset","расстроенный","adj","She was upset about the news.","Она была расстроена новостью."],
["upset","расстраивать","v","The letter upset him.","Письмо его расстроило."],
["disappointed","разочарованный","adj","I was disappointed with the film.","Я был разочарован фильмом."],
["disappointing","разочаровывающий","adj","The result was disappointing.","Результат был разочаровывающим."],
["embarrassed","смущённый","adj","I was embarrassed by my mistake.","Мне было стыдно за свою ошибку."],
["embarrassing","неловкий, смущающий","adj","It was an embarrassing moment.","Это был неловкий момент."],
["annoy","раздражать","v","The noise annoys me.","Шум меня раздражает."],
["annoyed","раздражённый","adj","She was annoyed with her brother.","Она была раздражена на брата."],
["annoying","раздражающий","adj","What an annoying sound!","Какой раздражающий звук!"],
["frighten","пугать","v","The dog frightened the children.","Собака напугала детей."],
["frightened","напуганный","adj","The frightened cat ran away.","Напуганная кошка убежала."],
["frightening","пугающий","adj","It was a frightening experience.","Это был пугающий опыт."],
["lonely","одинокий","adj","He felt lonely in the big city.","В большом городе он чувствовал себя одиноким."],
["confused","растерянный, сбитый с толку","adj","I am confused by these rules.","Эти правила меня запутали."],
["confuse","путать, сбивать с толку","v","Do not confuse these two words.","Не путай эти два слова."]
]},
{id:"b1-character", title:"Характер и качества", words:[
["honest","честный","adj","Be honest with me.","Будь со мной честен."],
["brave","смелый","adj","The brave firefighter saved the child.","Смелый пожарный спас ребёнка."],
["generous","щедрый","adj","She is generous with her time.","Она щедро делится своим временем."],
["gentle","мягкий, нежный","adj","He has a gentle voice.","У него мягкий голос."],
["kind","добрый","adj","It was kind of you to help.","Было мило с твоей стороны помочь."],
["cruel","жестокий","adj","It is cruel to keep animals in small cages.","Держать животных в маленьких клетках жестоко."],
["careless","беспечный, небрежный","adj","A careless driver caused the accident.","Беспечный водитель стал причиной аварии."],
["confident","уверенный","adj","She is confident about the exam.","Она уверена насчёт экзамена."],
["shy","застенчивый","adj","He is too shy to speak in public.","Он слишком застенчив, чтобы выступать на публике."],
["proud","гордый","adj","I am proud of my daughter.","Я горжусь своей дочерью."],
["ambitious","амбициозный","adj","She is an ambitious young lawyer.","Она амбициозный молодой юрист."],
["ambition","амбиция, стремление","n","His ambition is to become a pilot.","Его мечта — стать пилотом."],
["determined","решительный, целеустремлённый","adj","She is determined to win.","Она твёрдо намерена победить."],
["keen","увлечённый, горячо желающий","adj","He is keen on football.","Он увлекается футболом."],
["sensible","разумный, благоразумный","adj","It is sensible to take an umbrella.","Разумно взять зонт."],
["silly","глупый","adj","Do not be silly!","Не глупи!"],
["mad","сумасшедший; злой","adj","Are you mad? It is dangerous!","Ты с ума сошёл? Это опасно!"],
["odd","странный; нечётный","adj","He is a bit odd.","Он немного странный."],
["smart","умный; нарядный","adj","She is a smart student.","Она умная студентка."],
["talent","талант","n","She has a talent for music.","У неё талант к музыке."],
["talented","талантливый","adj","He is a talented painter.","Он талантливый художник."],
["intelligence","ум, интеллект","n","Tests measure intelligence.","Тесты измеряют интеллект."],
["attitude","отношение, позиция","n","She has a positive attitude to work.","У неё позитивное отношение к работе."],
["grateful","благодарный","adj","I am grateful for your help.","Я благодарен за твою помощь."],
["strength","сила","n","He does not have the strength to lift it.","У него нет сил это поднять."],
["identity","личность, идентичность","n","The police checked his identity.","Полиция проверила его личность."]
]},
{id:"b1-relations", title:"Отношения и жизнь", words:[
["friendship","дружба","n","Our friendship began at school.","Наша дружба началась в школе."],
["marriage","брак, женитьба","n","They have a happy marriage.","У них счастливый брак."],
["bride","невеста","n","The bride wore a white dress.","Невеста была в белом платье."],
["engaged","помолвленный; занятый","adj","They got engaged last month.","Они обручились в прошлом месяце."],
["kiss","целовать","v","She kissed her son goodnight.","Она поцеловала сына на ночь."],
["kiss","поцелуй","n","He gave her a kiss.","Он поцеловал её."],
["childhood","детство","n","I had a happy childhood.","У меня было счастливое детство."],
["youth","молодость; молодёжь","n","In his youth he was a footballer.","В молодости он был футболистом."],
["generation","поколение","n","Every generation has its own music.","У каждого поколения своя музыка."],
["aged","в возрасте; пожилой","adj","The course is for children aged ten to twelve.","Курс для детей в возрасте от десяти до двенадцати лет."],
["age","стареть","v","He has aged a lot.","Он сильно постарел."],
["relative","родственник","n","We visited our relatives in the country.","Мы навестили родственников в деревне."],
["relative","относительный","adj","We live in relative comfort.","Мы живём в относительном комфорте."],
["relation","отношение, связь; родственник","n","Relations between the two countries are good.","Отношения между двумя странами хорошие."],
["related","связанный; родственный","adj","The two problems are related.","Эти две проблемы связаны."],
["relate","относиться, быть связанным","v","The story relates to my childhood.","Эта история связана с моим детством."],
["stranger","незнакомец","n","Do not talk to strangers.","Не разговаривай с незнакомцами."],
["gentleman","джентльмен, господин","n","He is a real gentleman.","Он настоящий джентльмен."],
["host","хозяин (принимающий гостей); ведущий","n","Our host cooked a wonderful dinner.","Хозяин приготовил чудесный ужин."],
["servant","слуга","n","The king had many servants.","У короля было много слуг."],
["neighbourhood","район, соседство","n","We live in a quiet neighbourhood.","Мы живём в тихом районе."],
["custom","обычай","n","It is a custom to give gifts at New Year.","Дарить подарки на Новый год — обычай."],
["celebration","празднование","n","The celebration lasted all night.","Празднование длилось всю ночь."],
["ceremony","церемония","n","The wedding ceremony was short.","Свадебная церемония была короткой."],
["occasion","случай, событие","n","This is a special occasion.","Это особый случай."],
["respect","уважение","n","Children should show respect to adults.","Дети должны проявлять уважение к взрослым."],
["respect","уважать","v","I respect your opinion.","Я уважаю твоё мнение."],
]},
{id:"b1-home-things", title:"Дом, вещи и материалы", words:[
["cottage","коттедж, домик","n","They have a cottage by the sea.","У них домик у моря."],
["garage","гараж","n","The car is in the garage.","Машина в гараже."],
["ceiling","потолок","n","The ceiling is painted white.","Потолок покрашен в белый."],
["curtain","штора, занавеска","n","Close the curtains, please.","Задёрни шторы, пожалуйста."],
["shelf","полка","n","The books are on the top shelf.","Книги на верхней полке."],
["fence","забор","n","There is a wooden fence around the garden.","Вокруг сада деревянный забор."],
["yard","двор","n","The children are playing in the yard.","Дети играют во дворе."],
["heating","отопление","n","The heating is not working.","Отопление не работает."],
["pan","сковорода, кастрюля","n","Heat the oil in a pan.","Разогрей масло на сковороде."],
["pot","горшок, кастрюля","n","The plant is in a big pot.","Растение в большом горшке."],
["tin","консервная банка; олово","n","Open a tin of beans.","Открой банку фасоли."],
["container","контейнер, ёмкость","n","Keep the rice in a container.","Храни рис в контейнере."],
["tube","трубка, тюбик; метро","n","I bought a tube of toothpaste.","Я купил тюбик зубной пасты."],
["pipe","труба","n","The water pipe is broken.","Водопроводная труба сломана."],
["rope","верёвка","n","Tie the boat with a rope.","Привяжи лодку верёвкой."],
["string","верёвка, бечёвка; струна","n","Tie the box with string.","Перевяжи коробку бечёвкой."],
["chain","цепь, цепочка","n","She wears a gold chain.","Она носит золотую цепочку."],
["needle","игла","n","I need a needle and thread.","Мне нужны иголка с ниткой."],
["pin","булавка","n","She fixed the paper with a pin.","Она закрепила бумагу булавкой."],
["pin","прикалывать","v","Pin the note to the board.","Приколи записку к доске."],
["frame","рама, рамка","n","The picture is in a wooden frame.","Картина в деревянной раме."],
["frame","вставлять в раму","v","I framed the photo.","Я вставил фотографию в рамку."],
["cloth","ткань; тряпка","n","Clean the table with a wet cloth.","Протри стол влажной тряпкой."],
["cotton","хлопок","n","This shirt is made of cotton.","Эта рубашка сделана из хлопка."],
["wool","шерсть","n","The sweater is made of wool.","Свитер сделан из шерсти."],
["leather","кожа (материал)","n","I bought a leather jacket.","Я купил кожаную куртку."],
["iron","железо; утюг","n","The gate is made of iron.","Ворота сделаны из железа."],
["iron","гладить (утюгом)","v","I need to iron my shirt.","Мне нужно погладить рубашку."],
["glove","перчатка","n","Wear gloves, it is cold.","Надень перчатки, холодно."],
["cap","кепка, шапка; крышка","n","He wears a baseball cap.","Он носит бейсболку."]
]},
{id:"b1-food-cooking", title:"Еда и кухня", words:[
["ingredient","ингредиент","n","Mix all the ingredients in a bowl.","Смешай все ингредиенты в миске."],
["flour","мука","n","You need flour, eggs and milk for pancakes.","Для блинов нужны мука, яйца и молоко."],
["grain","зерно","n","Bread is made from grain.","Хлеб делают из зерна."],
["powder","порошок","n","Add a spoon of baking powder.","Добавь ложку разрыхлителя."],
["liquid","жидкость","n","Water is a liquid.","Вода — жидкость."],
["liquid","жидкий","adj","Liquid soap is easy to use.","Жидким мылом удобно пользоваться."],
["spicy","острый, пряный","adj","Indian food is often spicy.","Индийская еда часто острая."],
["mild","мягкий, неострый","adj","This cheese has a mild taste.","У этого сыра мягкий вкус."],
["cream","кремовый (цвет)","adj","She wore a cream dress.","На ней было платье кремового цвета."],
["bake","печь","v","I baked a cake for her birthday.","Я испёк торт на её день рождения."],
["fry","жарить","v","Fry the eggs in butter.","Пожарь яйца на масле."],
["mix","смешивать","v","Mix the sugar and butter.","Смешай сахар и масло."],
["mix","смесь","n","This is a mix of old and new songs.","Это смесь старых и новых песен."],
["mixture","смесь","n","Pour the mixture into a pan.","Вылей смесь на сковороду."],
["pour","лить, наливать","v","Pour the milk into the glass.","Налей молоко в стакан."],
["slice","ломтик","n","Would you like a slice of cake?","Хочешь кусочек торта?"],
["slice","нарезать ломтиками","v","Slice the bread thinly.","Нарежь хлеб тонкими ломтиками."],
["bite","кусать","v","The dog bit my hand.","Собака укусила меня за руку."],
["bite","укус; кусочек","n","Can I have a bite of your sandwich?","Можно откусить от твоего бутерброда?"],
["freeze","замораживать, замерзать","v","The lake froze last night.","Прошлой ночью озеро замёрзло."],
["frozen","замороженный","adj","We bought frozen vegetables.","Мы купили замороженные овощи."],
["cool","охлаждать, остывать","v","Let the soup cool before you eat it.","Дай супу остыть, прежде чем есть."],
["warm","греть, согревать","v","Warm the milk for the baby.","Подогрей молоко для малыша."],
["consume","потреблять","v","We consume too much sugar.","Мы потребляем слишком много сахара."],
["consumer","потребитель","n","Consumers want lower prices.","Потребители хотят более низких цен."],
["receipt","чек, квитанция","n","Keep the receipt in case you want to return it.","Сохрани чек на случай возврата."]
]},
{id:"b1-money-2", title:"Деньги и экономика", words:[
["economy","экономика","n","The economy is growing.","Экономика растёт."],
["economic","экономический","adj","The country has economic problems.","У страны экономические проблемы."],
["financial","финансовый","adj","She needs financial help.","Ей нужна финансовая помощь."],
["currency","валюта","n","The euro is the currency of France.","Евро — валюта Франции."],
["coin","монета","n","I found an old coin in the garden.","Я нашёл старую монету в саду."],
["account","счёт (банковский); отчёт","n","I opened a bank account.","Я открыл счёт в банке."],
["payment","платёж, оплата","n","Payment is by card only.","Оплата только картой."],
["profit","прибыль","n","The company made a big profit.","Компания получила большую прибыль."],
["loss","потеря, убыток","n","The shop made a loss last year.","В прошлом году магазин понёс убытки."],
["invest","инвестировать, вкладывать","v","He invested his money in property.","Он вложил деньги в недвижимость."],
["afford","позволить себе","v","I cannot afford a new car.","Я не могу позволить себе новую машину."],
["discount","скидка","n","Students get a ten per cent discount.","Студентам скидка десять процентов."],
["rent","арендная плата","n","The rent is high in this area.","Аренда в этом районе дорогая."],
["rent","снимать, сдавать в аренду","v","We rented a flat near the university.","Мы сняли квартиру рядом с университетом."],
["tax","налог","n","We pay tax on everything we buy.","Мы платим налог со всех покупок."],
["tax","облагать налогом","v","The government taxes alcohol heavily.","Государство облагает алкоголь высоким налогом."],
["trade","торговля","n","Trade between the two countries is growing.","Торговля между двумя странами растёт."],
["trade","торговать","v","The company trades with China.","Компания торгует с Китаем."],
["exchange","обмен","n","We had an exchange of ideas.","Мы обменялись идеями."],
["exchange","обменивать","v","Can I exchange this shirt for a bigger one?","Можно обменять эту рубашку на больший размер?"],
["export","экспорт","n","Oil is the country's main export.","Нефть — главный экспорт страны."],
["export","экспортировать","v","Brazil exports coffee.","Бразилия экспортирует кофе."],
["import","импорт","n","The country depends on imports.","Страна зависит от импорта."],
["import","импортировать","v","We import cars from Japan.","Мы импортируем машины из Японии."],
["goods","товары","n","The shop sells electrical goods.","В магазине продают электротовары."],
["brand","бренд, марка","n","What brand of phone do you have?","Какой марки у тебя телефон?"],
["brand","называть, клеймить","v","The press branded him a liar.","Пресса заклеймила его лжецом."],
["luxury","роскошь","n","A holiday abroad is a luxury for us.","Отпуск за границей для нас роскошь."],
["property","собственность, недвижимость","n","The house is private property.","Дом — частная собственность."],
["poverty","бедность","n","Many people live in poverty.","Многие люди живут в бедности."]
]},
{id:"b1-work-2", title:"Работа и карьера", words:[
["employment","занятость, работа","n","Employment is high in the city.","В городе высокая занятость."],
["unemployment","безработица","n","Unemployment is rising.","Безработица растёт."],
["unemployed","безработный","adj","He has been unemployed for a year.","Он без работы уже год."],
["profession","профессия","n","What is your profession?","Кто вы по профессии?"],
["qualification","квалификация, диплом","n","You need a qualification for this job.","Для этой работы нужна квалификация."],
["qualified","квалифицированный","adj","She is a qualified nurse.","Она дипломированная медсестра."],
["qualify","получать квалификацию; проходить отбор","v","He qualified as a doctor last year.","В прошлом году он получил диплом врача."],
["candidate","кандидат","n","There are three candidates for the job.","На эту должность три кандидата."],
["application","заявление, заявка; приложение","n","Send your application by Friday.","Отправьте заявление к пятнице."],
["appointment","встреча, приём (назначенный)","n","I have an appointment with the dentist.","У меня приём у стоматолога."],
["hire","нанимать; брать напрокат","v","The company hired ten new workers.","Компания наняла десять новых работников."],
["retire","выходить на пенсию","v","My father retired at sixty.","Мой отец вышел на пенсию в шестьдесят."],
["retired","на пенсии","adj","My grandmother is retired.","Моя бабушка на пенсии."],
["quit","бросать, увольняться","v","She quit her job last month.","В прошлом месяце она уволилась."],
["shift","смена (рабочая); сдвиг","n","I work the night shift.","Я работаю в ночную смену."],
["staff","персонал, сотрудники","n","The hotel staff were very friendly.","Персонал отеля был очень дружелюбным."],
["client","клиент","n","The lawyer met her client.","Юрист встретилась с клиентом."],
["agent","агент","n","We booked the trip through a travel agent.","Мы забронировали поездку через турагента."],
["management","управление, руководство","n","The management decided to close the shop.","Руководство решило закрыть магазин."],
["marketing","маркетинг","n","She works in marketing.","Она работает в маркетинге."],
["market","продавать, продвигать","v","The product is marketed to young people.","Продукт продвигают среди молодёжи."],
["producer","производитель; продюсер","n","Brazil is a big coffee producer.","Бразилия — крупный производитель кофе."],
["production","производство","n","Car production has increased.","Производство автомобилей выросло."],
["commercial","коммерческий","adj","The film was a commercial success.","Фильм имел коммерческий успех."],
["commercial","рекламный ролик","n","I hate TV commercials.","Ненавижу телевизионную рекламу."],
["ad","реклама, объявление","n","I saw an ad for a new phone.","Я видел рекламу нового телефона."],
["campaign","кампания","n","The campaign was a great success.","Кампания имела большой успех."],
["campaign","вести кампанию","v","They campaigned for cleaner air.","Они боролись за чистый воздух."],
["promote","продвигать; повышать в должности","v","She was promoted to manager.","Её повысили до менеджера."]
]},
{id:"b1-education-2", title:"Образование и наука", words:[
["academic","академический, учебный","adj","The academic year starts in September.","Учебный год начинается в сентябре."],
["campus","кампус, студенческий городок","n","The library is on campus.","Библиотека находится в кампусе."],
["graduate","выпускник","n","She is a graduate of Oxford.","Она выпускница Оксфорда."],
["graduate","оканчивать учебное заведение","v","He graduated in 2020.","Он окончил университет в 2020 году."],
["educate","обучать, давать образование","v","Parents want to educate their children well.","Родители хотят дать детям хорошее образование."],
["educated","образованный","adj","She is a well-educated woman.","Она хорошо образованная женщина."],
["educational","образовательный","adj","The museum runs educational programmes.","Музей проводит образовательные программы."],
["primary","начальный; первичный","adj","My son goes to primary school.","Мой сын ходит в начальную школу."],
["secondary","средний (о школе); второстепенный","adj","She teaches at a secondary school.","Она преподаёт в средней школе."],
["assignment","задание","n","The assignment is due on Monday.","Задание нужно сдать в понедельник."],
["grade","оценка; класс (в школе)","n","She got a good grade in maths.","Она получила хорошую оценку по математике."],
["revise","повторять (перед экзаменом); пересматривать","v","I am revising for my exams.","Я повторяю материал к экзаменам."],
["summarize","кратко излагать","v","Summarize the text in three sentences.","Изложи текст в трёх предложениях."],
["summary","краткое изложение","n","Write a summary of the article.","Напиши краткое изложение статьи."],
["definition","определение","n","Look up the definition of the word.","Найди определение слова."],
["define","определять, давать определение","v","Can you define this word?","Можешь дать определение этому слову?"],
["theory","теория","n","This is only a theory.","Это только теория."],
["analyse","анализировать","v","We analysed the results.","Мы проанализировали результаты."],
["analysis","анализ","n","The analysis took two weeks.","Анализ занял две недели."],
["laboratory","лаборатория","n","The tests are done in a laboratory.","Тесты проводятся в лаборатории."],
["scientific","научный","adj","There is no scientific evidence for this.","Этому нет научных доказательств."],
["experiment","экспериментировать","v","Scientists experiment with new materials.","Учёные экспериментируют с новыми материалами."],
["chemical","химический","adj","Chemical reactions produce heat.","Химические реакции выделяют тепло."],
["chemical","химикат, химическое вещество","n","Dangerous chemicals are stored here.","Здесь хранятся опасные химикаты."],
["element","элемент","n","Gold is a chemical element.","Золото — химический элемент."],
["statistic","статистический показатель","n","The statistics show a rise in crime.","Статистика показывает рост преступности."],
["percentage","процент, доля","n","A large percentage of students work.","Большая доля студентов работает."],
["diagram","диаграмма, схема","n","The diagram shows how the engine works.","Схема показывает, как работает двигатель."],
["measure","измерять","v","Measure the length of the table.","Измерь длину стола."],
["measure","мера","n","The government took new measures.","Правительство приняло новые меры."]
]},
{id:"b1-language", title:"Язык и текст", words:[
["literature","литература","n","She studies English literature.","Она изучает английскую литературу."],
["poem","стихотворение","n","He wrote a poem for his mother.","Он написал стихотворение для мамы."],
["poet","поэт","n","Pushkin is a famous Russian poet.","Пушкин — известный русский поэт."],
["poetry","поэзия","n","I love reading poetry.","Я люблю читать поэзию."],
["narrative","повествование, рассказ","n","The narrative is told by a child.","Повествование ведётся от лица ребёнка."],
["narrative","повествовательный","adj","The book has a simple narrative style.","У книги простой повествовательный стиль."],
["plot","сюжет","n","The plot of the film is complicated.","Сюжет фильма запутанный."],
["chapter","глава","n","Read the first chapter for tomorrow.","Прочитай первую главу к завтрашнему дню."],
["clause","придаточное предложение; пункт (договора)","n","This sentence has two clauses.","В этом предложении две части."],
["quotation","цитата","n","The essay begins with a quotation.","Эссе начинается с цитаты."],
["quote","цитировать","v","She quoted a line from the poem.","Она процитировала строчку из стихотворения."],
["quote","цитата","n","This quote is from Shakespeare.","Эта цитата из Шекспира."],
["translate","переводить","v","Translate this sentence into Russian.","Переведи это предложение на русский."],
["translation","перевод","n","The translation is not exact.","Перевод неточный."],
["reference","ссылка, упоминание; рекомендация","n","The book makes reference to the war.","В книге упоминается война."],
["headline","заголовок","n","The headline was about the election.","Заголовок был о выборах."],
["editor","редактор","n","She is the editor of a magazine.","Она редактор журнала."],
["journal","журнал (научный); дневник","n","The article was published in a medical journal.","Статья была опубликована в медицинском журнале."],
["script","сценарий; шрифт","n","The actors are reading the script.","Актёры читают сценарий."],
["spoken","устный, разговорный","adj","Her spoken English is very good.","У неё очень хороший разговорный английский."],
["written","письменный","adj","You need written permission.","Нужно письменное разрешение."],
["printing","печать, печатание","n","Printing was invented in the fifteenth century.","Книгопечатание было изобретено в пятнадцатом веке."],
["type","печатать (на клавиатуре)","v","Type your name and password.","Введи имя и пароль."],
["file","файл; папка","n","Save the file on your computer.","Сохрани файл на компьютере."],
["software","программное обеспечение","n","The software is easy to use.","Программа проста в использовании."],
["click","щёлкать, нажимать","v","Click on the picture.","Нажми на картинку."],
["click","щелчок","n","One click opens the file.","Один щелчок открывает файл."],
["scan","сканировать","v","Scan the document and send it to me.","Отсканируй документ и пришли мне."],
["update","обновление","n","Install the latest update.","Установи последнее обновление."],
["update","обновлять","v","I updated the app yesterday.","Я обновил приложение вчера."]
]},
{id:"b1-society-2", title:"Государство и политика", words:[
["nation","нация, страна","n","The whole nation watched the game.","Вся страна смотрела игру."],
["politics","политика","n","I am not interested in politics.","Я не интересуюсь политикой."],
["political","политический","adj","There are three political parties.","Есть три политические партии."],
["politician","политик","n","The politician gave a long speech.","Политик произнёс длинную речь."],
["policy","политика (курс), правила","n","The company has a new policy on smoking.","У компании новые правила по курению."],
["election","выборы","n","The election is next month.","Выборы в следующем месяце."],
["vote","голосовать","v","Who did you vote for?","За кого ты голосовал?"],
["vote","голос (на выборах)","n","She got most of the votes.","Она получила большинство голосов."],
["authority","власть; авторитет","n","The local authority runs the schools.","Местные власти управляют школами."],
["official","официальный","adj","This is an official document.","Это официальный документ."],
["union","союз; профсоюз","n","The workers joined a union.","Рабочие вступили в профсоюз."],
["royal","королевский","adj","The royal family lives in the palace.","Королевская семья живёт во дворце."],
["prince","принц","n","The prince married a teacher.","Принц женился на учительнице."],
["princess","принцесса","n","The princess opened the new hospital.","Принцесса открыла новую больницу."],
["captain","капитан","n","The captain of the team is my friend.","Капитан команды — мой друг."],
["battle","битва, сражение","n","The battle lasted three days.","Битва длилась три дня."],
["enemy","враг","n","The two countries were enemies for years.","Две страны много лет были врагами."],
["weapon","оружие","n","The police found the weapon.","Полиция нашла оружие."],
["bomb","бомба","n","A bomb exploded in the city.","В городе взорвалась бомба."],
["bomb","бомбить","v","The city was bombed during the war.","Город бомбили во время войны."],
["explode","взрываться","v","The car exploded after the crash.","После аварии машина взорвалась."],
["explosion","взрыв","n","We heard a loud explosion.","Мы услышали громкий взрыв."],
["nuclear","ядерный","adj","The country has nuclear power stations.","В стране есть атомные электростанции."],
["security","безопасность, охрана","n","Security at the airport is strict.","Охрана в аэропорту строгая."],
["guard","охранник","n","A guard stands at the gate.","У ворот стоит охранник."],
["guard","охранять","v","Two dogs guard the house.","Два пса охраняют дом."],
["protest","протест","n","There was a protest against the new law.","Был протест против нового закона."],
["protest","протестовать","v","Students protested against the changes.","Студенты протестовали против изменений."],
["immigrant","иммигрант","n","Many immigrants work in the city.","В городе работает много иммигрантов."]
]},
{id:"b1-law", title:"Закон и преступление", words:[
["legal","законный, юридический","adj","Is it legal to park here?","Здесь законно парковаться?"],
["illegal","незаконный","adj","It is illegal to drive without a licence.","Водить без прав незаконно."],
["court","суд","n","He went to court for stealing.","Его судили за кражу."],
["judge","судья","n","The judge sent him to prison.","Судья отправил его в тюрьму."],
["judge","судить, оценивать","v","Do not judge a book by its cover.","Не суди книгу по обложке."],
["guilty","виновный","adj","The man was found guilty.","Мужчину признали виновным."],
["innocent","невиновный","adj","She says she is innocent.","Она говорит, что невиновна."],
["criminal","преступный, уголовный","adj","Stealing is a criminal act.","Кража — уголовное преступление."],
["arrest","арестовывать","v","The police arrested two men.","Полиция арестовала двух мужчин."],
["arrest","арест","n","The police made three arrests.","Полиция произвела три ареста."],
["prisoner","заключённый","n","The prisoners work in the garden.","Заключённые работают в саду."],
["punish","наказывать","v","The teacher punished the boy for lying.","Учитель наказал мальчика за ложь."],
["punishment","наказание","n","The punishment was too hard.","Наказание было слишком суровым."],
["murder","убийство","n","The police are investigating the murder.","Полиция расследует убийство."],
["murder","убивать","v","He was murdered in his own house.","Его убили в собственном доме."],
["killing","убийство","n","The killing shocked the town.","Убийство потрясло город."],
["victim","жертва","n","The victims of the flood need help.","Жертвам наводнения нужна помощь."],
["investigate","расследовать","v","The police are investigating the case.","Полиция расследует дело."],
["cheat","обманывать, жульничать","v","He cheated in the exam.","Он списывал на экзамене."],
["cheat","обманщик, жулик","n","He is a cheat and a liar.","Он жулик и лжец."],
["lie","лгать","v","Do not lie to me!","Не лги мне!","untruth"],
["lie","ложь","n","That is a lie!","Это ложь!"],
["truth","правда","n","Tell me the truth.","Скажи мне правду."],
["pretend","притворяться","v","He pretended to be asleep.","Он притворился спящим."],
["trick","трюк, хитрость; обман","n","It was a clever trick.","Это был хитрый трюк."],
["trick","обманывать","v","They tricked him into paying twice.","Они обманом заставили его заплатить дважды."],
["duty","долг, обязанность","n","It is my duty to help.","Помочь — мой долг."],
["ban","запрещать","v","Smoking is banned in restaurants.","Курение в ресторанах запрещено."],
["ban","запрет","n","Cars are banned here: the ban starts today.","Машины здесь запрещены: запрет начинает действовать сегодня."]
]},
{id:"b1-religion-culture", title:"Культура, вера и искусство", words:[
["religion","религия","n","People of many religions live here.","Здесь живут люди многих религий."],
["religious","религиозный","adj","She is very religious.","Она очень религиозна."],
["pray","молиться","v","They prayed for rain.","Они молились о дожде."],
["prayer","молитва","n","She said a prayer before dinner.","Она прочитала молитву перед ужином."],
["priest","священник","n","The priest spoke to the family.","Священник поговорил с семьёй."],
["spirit","дух","n","The team has a strong spirit.","У команды сильный дух."],
["belief","вера, убеждение","n","It is my belief that he is honest.","Я убеждён, что он честен."],
["ghost","привидение","n","Do you believe in ghosts?","Ты веришь в привидения?"],
["magic","магия, волшебство","n","The children love magic.","Дети любят волшебство."],
["magic","волшебный","adj","She has a magic wand.","У неё волшебная палочка."],
["mystery","тайна, загадка","n","His death is still a mystery.","Его смерть до сих пор остаётся загадкой."],
["cultural","культурный","adj","There are cultural differences between countries.","Между странами есть культурные различия."],
["historic","исторический (значимый)","adj","It was a historic day.","Это был исторический день."],
["historical","исторический","adj","She writes historical novels.","Она пишет исторические романы."],
["folk","народный","adj","I like folk music.","Мне нравится народная музыка."],
["folk","люди, народ","n","Country folk are friendly.","Сельские жители дружелюбны."],
["sculpture","скульптура","n","The sculpture is made of stone.","Скульптура сделана из камня."],
["statue","статуя","n","There is a statue in the square.","На площади стоит статуя."],
["portrait","портрет","n","This is a portrait of the queen.","Это портрет королевы."],
["exhibition","выставка","n","The exhibition opens next week.","Выставка открывается на следующей неделе."],
["photography","фотография (искусство)","n","Photography is my hobby.","Фотография — моё хобби."],
["photographer","фотограф","n","The photographer took pictures of the bride.","Фотограф сфотографировал невесту."],
["studio","студия","n","The band is recording in the studio.","Группа записывается в студии."],
["costume","костюм (театральный, национальный)","n","The dancers wore traditional costumes.","Танцоры были в традиционных костюмах."],
["performance","выступление, спектакль","n","The performance starts at seven.","Спектакль начинается в семь."],
["musical","мюзикл","n","We saw a musical in London.","Мы смотрели мюзикл в Лондоне."],
["drum","барабан","n","He plays the drums in a band.","Он играет на барабанах в группе."],
["album","альбом","n","The band released a new album.","Группа выпустила новый альбом."],
["entertain","развлекать","v","The clown entertained the children.","Клоун развлекал детей."],
["entertainment","развлечение","n","The hotel offers evening entertainment.","В отеле есть вечерние развлечения."]
]},
{id:"b1-media-3", title:"Телевидение и общение", words:[
["channel","канал","n","What is on the other channel?","Что идёт по другому каналу?"],
["episode","эпизод, серия","n","I missed the last episode.","Я пропустил последнюю серию."],
["documentary","документальный фильм","n","We watched a documentary about lions.","Мы смотрели документальный фильм о львах."],
["viewer","зритель","n","The show has millions of viewers.","У шоу миллионы зрителей."],
["horror","ужас; фильм ужасов","n","I do not like horror films.","Я не люблю фильмы ужасов."],
["romantic","романтический","adj","We had a romantic dinner.","У нас был романтический ужин."],
["theme","тема","n","The theme of the film is friendship.","Тема фильма — дружба."],
["setting","место действия; обстановка","n","The setting of the story is a small village.","Действие рассказа происходит в маленькой деревне."],
["version","версия","n","This is the new version of the app.","Это новая версия приложения."],
["communication","общение, коммуникация","n","Good communication is important at work.","Хорошее общение важно на работе."],
["connection","связь, соединение","n","The internet connection is slow.","Интернет-соединение медленное."],
["contact","контакт, связь","n","I lost contact with my old friends.","Я потерял связь со старыми друзьями."],
["contact","связываться","v","Contact me by email.","Свяжись со мной по электронной почте."],
["announce","объявлять","v","They announced the winner.","Они объявили победителя."],
["announcement","объявление","n","There was an announcement at the station.","На вокзале было объявление."],
["comment","комментировать","v","He refused to comment.","Он отказался комментировать."],
["mention","упоминание","n","There was no mention of the price.","О цене не упоминалось."],
["presentation","презентация","n","She gave a presentation about her project.","Она провела презентацию своего проекта."],
["press","пресса; нажимать","n","The press wrote about the accident.","Пресса писала об аварии."],
["press","нажимать","v","Press the red button.","Нажми на красную кнопку."],
["signal","сигнал","n","There is no phone signal here.","Здесь нет сигнала телефона."],
["signal","подавать сигнал","v","Always signal before you turn.","Всегда подавай сигнал перед поворотом."],
["highlight","выделять, подчёркивать","v","The report highlights the main problems.","В отчёте выделены основные проблемы."],
["highlight","главное событие, лучший момент","n","The concert was the highlight of the trip.","Концерт был лучшим моментом поездки."],
["apologize","извиняться","v","I apologize for being late.","Извиняюсь за опоздание."],
["appreciate","ценить, быть благодарным","v","I appreciate your help.","Я ценю твою помощь."],
["admit","признавать(ся)","v","Admit it, you were wrong.","Признай, ты был неправ."],
["admire","восхищаться","v","I admire her courage.","Я восхищаюсь её смелостью."],
["advise","советовать","v","I advise you to see a doctor.","Советую тебе обратиться к врачу."],
["persuade","убеждать, уговаривать","v","She persuaded me to come.","Она уговорила меня прийти."]
]},
{id:"b1-travel-3", title:"Путешествия и места", words:[
["accommodation","жильё, размещение","n","The price includes accommodation.","В цену входит проживание."],
["reservation","бронь, бронирование","n","I have a reservation for two nights.","У меня бронь на две ночи."],
["destination","пункт назначения","n","Paris is a popular destination.","Париж — популярное направление."],
["departure","отправление, отъезд","n","The departure time is nine o'clock.","Время отправления — девять часов."],
["arrival","прибытие","n","We were tired on arrival.","По прибытии мы были уставшими."],
["expedition","экспедиция","n","They went on an expedition to the North Pole.","Они отправились в экспедицию на Северный полюс."],
["explore","исследовать","v","We explored the old town.","Мы исследовали старый город."],
["attraction","достопримечательность; привлекательность","n","The castle is a big tourist attraction.","Замок — главная достопримечательность для туристов."],
["border","граница","n","We crossed the border into France.","Мы пересекли границу с Францией."],
["port","порт","n","The ship arrived at the port.","Корабль прибыл в порт."],
["sailor","моряк","n","The sailors were happy to see land.","Моряки были рады увидеть землю."],
["sail","парус","n","The boat has a white sail.","У лодки белый парус."],
["helicopter","вертолёт","n","A helicopter flew over the city.","Над городом пролетел вертолёт."],
["tyre","шина","n","I have a flat tyre.","У меня спустило колесо."],
["fuel","топливо","n","The car needs fuel.","Машине нужно топливо."],
["tent","палатка","n","We slept in a tent.","Мы спали в палатке."],
["path","тропинка, дорожка","n","Follow the path to the lake.","Иди по тропинке к озеру."],
["countryside","сельская местность","n","We spent the weekend in the countryside.","Мы провели выходные за городом."],
["location","местоположение","n","The hotel is in a good location.","Отель в хорошем месте."],
["locate","находить, располагать","v","The police located the missing car.","Полиция нашла пропавшую машину."],
["located","расположенный","adj","The school is located near the park.","Школа расположена рядом с парком."],
["entrance","вход","n","Wait for me at the entrance.","Жди меня у входа."],
["entry","вход; запись","n","Entry to the museum is free.","Вход в музей бесплатный."],
["mall","торговый центр","n","We went shopping at the mall.","Мы ходили за покупками в торговый центр."],
["stadium","стадион","n","The stadium holds fifty thousand people.","Стадион вмещает пятьдесят тысяч человек."],
["block","квартал; блок","n","The shop is two blocks away.","Магазин в двух кварталах отсюда."],
["block","блокировать, перегораживать","v","A lorry blocked the road.","Грузовик перегородил дорогу."],
["central","центральный","adj","We live in central London.","Мы живём в центре Лондона."],
["remote","отдалённый","adj","They live in a remote village.","Они живут в отдалённой деревне."],
["tour","совершать тур, гастролировать","v","The band is touring Europe.","Группа гастролирует по Европе."]
]},
{id:"b1-nature-3", title:"Природа и стихии", words:[
["bank","берег (реки)","n","We sat on the bank of the river.","Мы сидели на берегу реки.","river"],
["leaf","лист (растения)","n","A leaf fell from the tree.","С дерева упал лист."],
["branch","ветка; филиал","n","A bird sat on the branch.","На ветке сидела птица."],
["seed","семя","n","Plant the seeds in spring.","Посади семена весной."],
["soil","почва","n","The soil here is good for vegetables.","Почва здесь хороша для овощей."],
["mud","грязь (мокрая земля)","n","My boots are covered in mud.","Мои сапоги в грязи."],
["dust","пыль","n","The table was covered in dust.","Стол был покрыт пылью."],
["dirt","грязь","n","Wash the dirt off your hands.","Смой грязь с рук."],
["sand","песок","n","The children played in the sand.","Дети играли в песке."],
["coal","уголь","n","The house is heated with coal.","Дом отапливается углём."],
["diamond","алмаз, бриллиант","n","The ring has a small diamond.","В кольце маленький бриллиант."],
["shell","ракушка; панцирь","n","We collected shells on the beach.","Мы собирали ракушки на пляже."],
["bee","пчела","n","A bee sat on the flower.","На цветок села пчела."],
["fur","мех, шерсть","n","The cat has soft fur.","У кошки мягкая шерсть."],
["tail","хвост","n","The dog wagged its tail.","Собака виляла хвостом."],
["wing","крыло","n","The bird broke its wing.","Птица сломала крыло."],
["hunt","охотиться","v","Lions hunt at night.","Львы охотятся ночью."],
["flood","наводнение","n","The flood destroyed the bridge.","Наводнение разрушило мост."],
["flood","затоплять","v","The river flooded the village.","Река затопила деревню."],
["earthquake","землетрясение","n","The earthquake destroyed many houses.","Землетрясение разрушило много домов."],
["hurricane","ураган","n","The hurricane hit the coast last night.","Ураган обрушился на побережье прошлой ночью."],
["flow","течь","v","The river flows into the sea.","Река впадает в море."],
["flow","поток, течение","n","The flow of the river is fast.","Течение реки быстрое."],
["atmosphere","атмосфера","n","The restaurant has a friendly atmosphere.","В ресторане дружелюбная атмосфера."],
["environmental","экологический","adj","Pollution is an environmental problem.","Загрязнение — экологическая проблема."],
["global","глобальный, мировой","adj","Climate change is a global problem.","Изменение климата — глобальная проблема."],
["surface","поверхность","n","The surface of the lake was calm.","Поверхность озера была спокойной."],
["edge","край","n","Do not stand near the edge.","Не стой у края."],
["layer","слой","n","There is a thick layer of snow on the roof.","На крыше толстый слой снега."]
]},
{id:"b1-sport-3", title:"Спорт и досуг", words:[
["champion","чемпион","n","She is the world champion.","Она чемпионка мира."],
["competitor","конкурент, участник соревнований","n","There were fifty competitors in the race.","В гонке участвовало пятьдесят спортсменов."],
["competitive","конкурентный; соревновательный","adj","He is very competitive.","Он очень любит соревноваться."],
["supporter","болельщик; сторонник","n","The supporters sang all game.","Болельщики пели всю игру."],
["racing","гонки","n","He loves car racing.","Он любит автогонки."],
["race","раса","n","People of all races live here.","Здесь живут люди всех рас.","people"],
["rugby","регби","n","Rugby is popular in Wales.","Регби популярно в Уэльсе."],
["kick","пинать, бить ногой","v","He kicked the ball into the goal.","Он забил мяч в ворота."],
["kick","удар ногой","n","He gave the ball a hard kick.","Он сильно ударил по мячу."],
["shoot","стрелять; снимать (фильм)","v","Do not shoot!","Не стреляй!"],
["swim","заплыв, плавание","n","Let's go for a swim.","Пойдём поплаваем."],
["climb","подъём, восхождение","n","It is a long climb to the top.","До вершины долгий подъём."],
["win","победа","n","It was an easy win for our team.","Это была лёгкая победа нашей команды."],
["go","попытка; ход","n","Can I have a go?","Можно мне попробовать?"],
["leisure","досуг","n","What do you do in your leisure time?","Чем ты занимаешься в свободное время?"],
["coach","тренировать","v","She coaches the school team.","Она тренирует школьную команду."],
["award","награждать","v","She was awarded first prize.","Ей присудили первый приз."],
["achievement","достижение","n","Winning the cup was a great achievement.","Победа в кубке была большим достижением."],
["challenge","вызов, трудная задача","n","Climbing the mountain was a real challenge.","Подъём на гору был настоящим испытанием."],
["effort","усилие","n","Learning a language takes effort.","Изучение языка требует усилий."],
["aim","цель","n","My aim is to run a marathon.","Моя цель — пробежать марафон."],
["aim","стремиться, целиться","v","We aim to finish by June.","Мы стремимся закончить к июню."],
["balance","равновесие, баланс","n","He lost his balance and fell.","Он потерял равновесие и упал."],
["balance","балансировать, уравновешивать","v","She balanced the book on her head.","Она держала книгу на голове, сохраняя равновесие."],
["roll","катиться, катить","v","The ball rolled under the car.","Мяч закатился под машину."],
["roll","рулон, булочка","n","I bought a roll of paper.","Я купил рулон бумаги."],
["spring","прыгать, вскакивать","v","The cat springs onto the table.","Кошка вскакивает на стол."],
["hang","вешать, висеть","v","Hang your coat on the hook.","Повесь пальто на крючок."]
]},
{id:"b1-verbs-1", title:"Действия и изменения", words:[
["attach","прикреплять","v","I attached the photo to the email.","Я прикрепил фото к письму."],
["fasten","застёгивать, закреплять","v","Fasten your seat belt.","Пристегни ремень безопасности."],
["fold","складывать","v","Fold the paper in half.","Сложи бумагу пополам."],
["bend","сгибать(ся), наклоняться","v","Bend your knees.","Согни колени."],
["bend","изгиб, поворот","n","There is a sharp bend in the road.","На дороге крутой поворот."],
["bury","хоронить, закапывать","v","The dog buried the bone.","Собака закопала кость."],
["deliver","доставлять","v","The parcel was delivered this morning.","Посылку доставили сегодня утром."],
["divide","делить","v","Divide the cake into six pieces.","Раздели торт на шесть частей."],
["combine","сочетать, объединять","v","Combine the flour and eggs.","Смешай муку с яйцами."],
["separate","разделять","v","Separate the whites from the yolks.","Отдели белки от желтков."],
["spread","распространять(ся); намазывать","v","The news spread quickly.","Новость быстро распространилась."],
["expand","расширять(ся)","v","The company is expanding.","Компания расширяется."],
["gather","собирать(ся)","v","People gathered in the square.","Люди собрались на площади."],
["store","хранить","v","Store the food in a cool place.","Храни еду в прохладном месте."],
["empty","опустошать, выкладывать","v","Empty your pockets, please.","Выложи всё из карманов, пожалуйста."],
["switch","переключать, выключать","v","Switch off the light.","Выключи свет."],
["sink","тонуть, погружаться","v","Wood does not sink in water.","Дерево не тонет в воде."],
["shine","светить, сиять","v","The sun is shining.","Солнце светит."],
["escape","убегать, спасаться","v","The prisoner escaped last night.","Заключённый сбежал прошлой ночью."],
["escape","побег","n","The escape was well planned.","Побег был хорошо спланирован."],
["hurry","спешить","v","Hurry, or we will miss the train!","Поторопись, а то опоздаем на поезд!"],
["hurry","спешка","n","There is no hurry.","Спешить некуда."],
["lay","класть; накрывать (на стол)","v","Lay the plates on the table.","Расставь тарелки на столе."],
["place","помещать, ставить","v","Place the vase on the shelf.","Поставь вазу на полку."],
["hand","передавать, вручать","v","Hand me the salt, please.","Передай мне соль, пожалуйста."],
["stick","прилипать; втыкать","v","Stick the stamp on the envelope.","Приклей марку на конверт."],
["stick","палка","n","The old man walks with a stick.","Старик ходит с палкой."],
["tip","наклонять; давать чаевые","v","Tip the pan to pour the oil.","Наклони сковороду, чтобы слить масло."],
["water","поливать","v","Water the flowers every day.","Поливай цветы каждый день."],
["wave","махать","v","She waved goodbye.","Она помахала на прощание."]
]},
{id:"b1-verbs-2", title:"Мысли и оценки", words:[
["conclude","делать вывод; завершать","v","The report concludes that prices will rise.","В отчёте делается вывод, что цены вырастут."],
["conclusion","вывод, заключение","n","What conclusion did you reach?","К какому выводу ты пришёл?"],
["determine","определять, устанавливать","v","The test will determine your level.","Тест определит твой уровень."],
["confirm","подтверждать","v","Please confirm your booking.","Пожалуйста, подтвердите бронирование."],
["prove","доказывать","v","Can you prove that you were at home?","Можешь доказать, что был дома?"],
["indicate","указывать, свидетельствовать","v","The sign indicates the way to the exit.","Знак указывает путь к выходу."],
["reflect","отражать; размышлять","v","The mirror reflects the light.","Зеркало отражает свет."],
["represent","представлять","v","She represents her country at the games.","Она представляет свою страну на играх."],
["examine","осматривать, изучать","v","The doctor examined the patient.","Врач осмотрел пациента."],
["concentrate","сосредотачиваться","v","I cannot concentrate with this noise.","Я не могу сосредоточиться из-за этого шума."],
["intend","намереваться","v","I intend to study medicine.","Я намерен изучать медицину."],
["intention","намерение","n","I have no intention of leaving.","Я не намерен уходить."],
["doubt","сомнение","n","There is no doubt about it.","В этом нет никаких сомнений."],
["doubt","сомневаться","v","I doubt that he will come.","Сомневаюсь, что он придёт."],
["wonder","задаваться вопросом, интересоваться","v","I wonder where she is.","Интересно, где она."],
["wonder","чудо; удивление","n","The pyramids are a wonder of the world.","Пирамиды — чудо света."],
["ignore","игнорировать","v","She ignored my question.","Она проигнорировала мой вопрос."],
["convince","убеждать","v","He convinced me to stay.","Он убедил меня остаться."],
["encourage","поощрять, воодушевлять","v","My parents encouraged me to study.","Родители поощряли меня учиться."],
["remind","напоминать","v","Remind me to call her.","Напомни мне позвонить ей."],
["require","требовать","v","This job requires experience.","Эта работа требует опыта."],
["request","просить, запрашивать","v","She requested a window seat.","Она попросила место у окна."],
["reject","отвергать, отклонять","v","They rejected my offer.","Они отклонили моё предложение."],
["claim","утверждать; требовать","v","He claims that he is innocent.","Он утверждает, что невиновен."],
["claim","утверждение; требование, заявка","n","His claim is hard to believe.","В его утверждение трудно поверить."],
["commit","совершать (преступление); брать обязательство","v","People who commit crimes go to prison.","Люди, совершающие преступления, попадают в тюрьму."],
["dislike","не любить","v","I dislike cold weather.","Я не люблю холодную погоду."],
["dislike","неприязнь","n","She has a strong dislike of cats.","Она очень не любит кошек."],
["fear","бояться","v","Many people fear flying.","Многие люди боятся летать."],
["hate","ненависть","n","There is no place for hate here.","Здесь нет места ненависти."]
]},
{id:"b1-verbs-3", title:"Жизнь и результаты", words:[
["occur","происходить, случаться","v","The accident occurred at night.","Авария произошла ночью."],
["remain","оставаться","v","Please remain in your seats.","Пожалуйста, оставайтесь на местах."],
["survive","выживать","v","Only two people survived the crash.","В катастрофе выжили только два человека."],
["tend","иметь тенденцию, склоняться","v","I tend to get up early.","Обычно я встаю рано."],
["consist","состоять","v","The team consists of five people.","Команда состоит из пяти человек."],
["result","приводить к результату","v","The storm resulted in floods.","Буря привела к наводнениям."],
["benefit","приносить пользу","v","The new road will benefit the town.","Новая дорога принесёт пользу городу."],
["attract","привлекать","v","The park attracts many visitors.","Парк привлекает много посетителей."],
["influence","влиять","v","His friends influence him a lot.","Друзья сильно на него влияют."],
["influence","влияние","n","She has a good influence on the children.","Она хорошо влияет на детей."],
["impact","влияние, воздействие","n","The film had a big impact on me.","Фильм произвёл на меня сильное впечатление."],
["impact","влиять, воздействовать","v","The weather impacts sales.","Погода влияет на продажи."],
["damage","ущерб, повреждение","n","The storm caused a lot of damage.","Буря причинила большой ущерб."],
["damage","повреждать","v","The fire damaged the roof.","Пожар повредил крышу."],
["force","сила","n","The force of the wind broke the tree.","Сила ветра сломала дерево."],
["force","заставлять","v","They forced him to leave.","Они заставили его уйти."],
["limit","предел, ограничение","n","There is a speed limit on this road.","На этой дороге есть ограничение скорости."],
["limit","ограничивать","v","Limit your screen time.","Ограничь время у экрана."],
["risk","риск","n","There is a risk of rain.","Есть риск дождя."],
["risk","рисковать","v","He risked his life to save the child.","Он рисковал жизнью, чтобы спасти ребёнка."],
["warn","предупреждать","v","I warned you about the ice.","Я предупреждал тебя о гололёде."],
["warning","предупреждение","n","There was a storm warning on the radio.","По радио передали штормовое предупреждение."],
["bother","беспокоить, утруждать(ся)","v","Do not bother me now.","Не беспокой меня сейчас."],
["participate","участвовать","v","Everyone participated in the game.","Все участвовали в игре."],
["volunteer","волонтёр, доброволец","n","She works as a volunteer at the hospital.","Она работает волонтёром в больнице."],
["volunteer","вызываться добровольно","v","He volunteered to wash the dishes.","Он вызвался помыть посуду."],
["donate","жертвовать","v","We donated clothes to the charity.","Мы пожертвовали одежду на благотворительность."],
["assist","помогать","v","A nurse assisted the doctor.","Медсестра помогала врачу."],
["waste","тратить впустую","v","Do not waste your time.","Не трать время впустую."],
["waste","отходы; пустая трата","n","It is a waste of money.","Это пустая трата денег."]
]},
{id:"b1-nouns-1", title:"Понятия и качества", words:[
["importance","важность","n","I understand the importance of sleep.","Я понимаю важность сна."],
["value","ценность, стоимость","n","The value of the house has increased.","Стоимость дома выросла."],
["beauty","красота","n","The beauty of the mountains amazed us.","Красота гор нас поразила."],
["reality","реальность","n","His dream became reality.","Его мечта стала реальностью."],
["similarity","сходство","n","There is a similarity between the two paintings.","Между двумя картинами есть сходство."],
["comparison","сравнение","n","In comparison with last year, sales are up.","По сравнению с прошлым годом продажи выросли."],
["contrast","контраст, противоположность","n","There is a big contrast between the two cities.","Между двумя городами большой контраст."],
["contrast","противопоставлять, контрастировать","v","The film contrasts city life with village life.","Фильм противопоставляет городскую жизнь деревенской."],
["difficulty","трудность","n","I had difficulty finding the hotel.","Мне было трудно найти отель."],
["disadvantage","недостаток, минус","n","The main disadvantage is the price.","Главный недостаток — цена."],
["consequence","последствие","n","Think about the consequences of your actions.","Подумай о последствиях своих поступков."],
["issue","проблема, вопрос; выпуск","n","Money is not the issue.","Дело не в деньгах."],
["pressure","давление","n","She is under a lot of pressure at work.","На работе она под большим давлением."],
["responsibility","ответственность","n","It is your responsibility to lock the door.","Запирать дверь — твоя обязанность."],
["safety","безопасность","n","Safety comes first.","Безопасность прежде всего."],
["standard","стандарт, уровень","n","The hotel has high standards.","В отеле высокие стандарты."],
["standard","стандартный","adj","This is the standard price.","Это стандартная цена."],
["basis","основа, основание","n","We meet on a weekly basis.","Мы встречаемся раз в неделю."],
["base","основа, база","n","The company's base is in Berlin.","База компании в Берлине."],
["base","основывать, базировать","v","The film is based on a true story.","Фильм основан на реальной истории."],
["function","функция, назначение","n","The function of the heart is to pump blood.","Функция сердца — перекачивать кровь."],
["operation","операция; работа (механизма)","n","She had an operation on her knee.","Ей сделали операцию на колене."],
["category","категория","n","Which category does this book belong to?","К какой категории относится эта книга?"],
["range","диапазон, ассортимент","n","The shop sells a wide range of shoes.","В магазине широкий ассортимент обуви."],
["sample","образец, проба","n","We received a free sample of the cream.","Мы получили бесплатный образец крема."],
["resource","ресурс","n","Water is a precious resource.","Вода — ценный ресурс."],
["supply","запас, поставка","n","The town has a good water supply.","В городе хорошее водоснабжение."],
["supply","снабжать, поставлять","v","The farm supplies the shop with eggs.","Ферма поставляет в магазин яйца."],
["spending","расходы, траты","n","Government spending on schools has increased.","Государственные расходы на школы выросли."],
["development","развитие, разработка","n","The development of the city was fast.","Развитие города было быстрым."]
]},
{id:"b1-nouns-2", title:"Действия и результаты", words:[
["improvement","улучшение","n","There has been an improvement in her health.","Её здоровье улучшилось."],
["growth","рост","n","The growth of the city was rapid.","Рост города был стремительным."],
["addition","добавление, дополнение","n","In addition to English, she speaks French.","Помимо английского, она говорит по-французски."],
["access","доступ","n","Students have access to the library.","У студентов есть доступ в библиотеку."],
["access","получать доступ","v","You can access your email from any computer.","Ты можешь открыть свою почту с любого компьютера."],
["agreement","соглашение, согласие","n","The two sides signed an agreement.","Обе стороны подписали соглашение."],
["complaint","жалоба","n","We received a complaint about the noise.","Мы получили жалобу на шум."],
["recommendation","рекомендация","n","I bought the book on her recommendation.","Я купил книгу по её рекомендации."],
["prediction","предсказание, прогноз","n","His prediction was correct.","Его прогноз оказался верным."],
["reaction","реакция","n","What was her reaction to the news?","Как она отреагировала на новость?"],
["impression","впечатление","n","She made a good impression at the interview.","Она произвела хорошее впечатление на собеседовании."],
["act","поступок; акт, закон","n","It was a brave act.","Это был смелый поступок."],
["deal","сделка","n","We made a deal with the company.","Мы заключили сделку с компанией."],
["charge","плата; обвинение; заряд","n","There is no charge for children.","С детей плата не взимается."],
["charge","взимать плату; заряжать; обвинять","v","They charge ten euros for parking.","За парковку они берут десять евро."],
["collection","коллекция, сбор","n","He has a large collection of coins.","У него большая коллекция монет."],
["planning","планирование","n","Good planning saves time.","Хорошее планирование экономит время."],
["repair","ремонт","n","The car is in need of repair.","Машина нуждается в ремонте."],
["move","движение, переезд, ход","n","Our move to London was difficult.","Наш переезд в Лондон был трудным."],
["drop","капля; падение","n","There was a drop in prices.","Произошло падение цен."],
["rise","подъём, рост","n","There has been a rise in prices.","Произошёл рост цен."],
["cut","порез; сокращение","n","I have a small cut on my finger.","У меня небольшой порез на пальце."],
["pull","рывок, притяжение","n","Give the door a pull.","Потяни дверь."],
["push","толчок","n","Give the door a push.","Толкни дверь."],
["knock","стук","n","There was a knock at the door.","В дверь постучали."],
["shake","встряска, дрожь","n","Give the bottle a good shake.","Хорошенько встряхни бутылку."],
["touch","прикосновение","n","I felt a touch on my shoulder.","Я почувствовал прикосновение к плечу."],
["sight","зрение; вид, зрелище","n","She has good sight.","У неё хорошее зрение."],
["count","подсчёт","n","At the last count there were fifty people.","По последним подсчётам, было пятьдесят человек."],
["pass","пропуск; передача (мяча)","n","You need a pass to enter the building.","Чтобы войти в здание, нужен пропуск."]
]},
{id:"b1-things-2", title:"Предметы и техника", words:[
["battery","батарейка, аккумулятор","n","My phone battery is dead.","У моего телефона села батарея."],
["alarm","будильник; сигнализация, тревога","n","I set the alarm for six.","Я поставил будильник на шесть."],
["bell","колокол, звонок","n","The school bell rang.","Прозвенел школьный звонок."],
["flag","флаг","n","The flag is red and white.","Флаг красно-белый."],
["label","этикетка, ярлык","n","Read the label before you wash it.","Прочитай этикетку перед стиркой."],
["label","маркировать, наклеивать ярлык","v","Label the boxes before you move.","Подпиши коробки перед переездом."],
["net","сеть, сетка","n","The fisherman threw the net into the sea.","Рыбак забросил сеть в море."],
["tape","лента, скотч; плёнка","n","Fix the poster with tape.","Прикрепи плакат скотчем."],
["package","упаковка, посылка; пакет","n","A package arrived for you.","Для тебя пришла посылка."],
["pack","пачка, упаковка; рюкзак","n","Buy a pack of cards.","Купи колоду карт."],
["robot","робот","n","Robots build cars in this factory.","На этом заводе машины собирают роботы."],
["keyboard","клавиатура","n","My keyboard is broken.","Моя клавиатура сломана."],
["program","программировать","v","She programs computers for a living.","Она зарабатывает программированием."],
["engineering","инженерное дело, проектирование","n","He studies engineering at university.","Он изучает инженерное дело в университете."],
["technical","технический","adj","We had a technical problem with the sound.","У нас была техническая проблема со звуком."],
["technique","техника, метод","n","This is a new technique for teaching languages.","Это новая методика преподавания языков."],
["substance","вещество","n","This substance is poisonous.","Это вещество ядовито."],
["solid","твёрдый","adj","Ice is solid water.","Лёд — твёрдая вода."],
["solid","твёрдое тело","n","Ice is a solid.","Лёд — твёрдое тело."],
["bubble","пузырь","n","The children were blowing bubbles.","Дети пускали мыльные пузыри."],
["mine","шахта, рудник","n","My grandfather worked in a coal mine.","Мой дедушка работал на угольной шахте."],
["stuff","вещи, штука (разг.)","n","Put your stuff in the car.","Положи свои вещи в машину."],
["underwear","нижнее бельё","n","Pack enough underwear for a week.","Возьми достаточно белья на неделю."],
["cover","обложка; крышка, покрытие","n","The book has a red cover.","У книги красная обложка."],
["covered","покрытый","adj","The hills were covered with snow.","Холмы были покрыты снегом."],
["row","ряд","n","We sat in the front row.","Мы сидели в первом ряду."],
["spot","пятно; место","n","This is a nice spot for a picnic.","Это хорошее место для пикника."],
["clue","подсказка, улика","n","The police found a clue.","Полиция нашла улику."],
["decorate","украшать; делать ремонт","v","We decorated the room for the party.","Мы украсили комнату к вечеринке."],
["fire","стрелять; увольнять","v","He was fired for being late.","Его уволили за опоздания."]
]},
{id:"b1-time-3", title:"Время и порядок событий", words:[
["decade","десятилетие","n","The city has changed a lot in the last decade.","За последнее десятилетие город сильно изменился."],
["current","текущий, нынешний","adj","What is your current address?","Какой у тебя нынешний адрес?"],
["currently","в настоящее время","adv","She is currently working in Berlin.","В настоящее время она работает в Берлине."],
["previous","предыдущий","adj","I liked the previous version better.","Предыдущая версия нравилась мне больше."],
["previously","ранее, прежде","adv","He previously worked as a teacher.","Раньше он работал учителем."],
["latest","последний, новейший","adj","Have you seen the latest film?","Ты видел последний фильм?"],
["original","оригинал","n","This is a copy; the original is in the museum.","Это копия; оригинал в музее."],
["originally","изначально","adv","The building was originally a church.","Изначально здание было церковью."],
["immediate","немедленный, ближайший","adj","We need an immediate answer.","Нам нужен немедленный ответ."],
["sudden","внезапный","adj","There was a sudden change in the weather.","Погода внезапно изменилась."],
["eventually","в конце концов","adv","Eventually we found the hotel.","В конце концов мы нашли отель."],
["meanwhile","тем временем","adv","Meanwhile, the children were playing.","Тем временем дети играли."],
["frequently","часто","adv","I frequently visit my grandmother.","Я часто навещаю бабушку."],
["regularly","регулярно","adv","Exercise regularly to stay healthy.","Регулярно занимайся спортом, чтобы быть здоровым."],
["rarely","редко","adv","She rarely goes out.","Она редко выходит из дома."],
["daily","ежедневно","adv","The shop is open daily.","Магазин открыт ежедневно."],
["forever","навсегда","adv","I will love you forever.","Я буду любить тебя вечно."],
["continuous","непрерывный","adj","There was continuous rain all week.","Всю неделю шёл непрерывный дождь."],
["repeated","повторный, повторяющийся","adj","After repeated attempts, he passed the test.","После многократных попыток он сдал тест."],
["repeat","повтор","n","The programme is a repeat.","Эта передача — повтор."],
["following","следующее (перечисляемое)","n","You will need the following: a pen and paper.","Вам понадобится следующее: ручка и бумага."],
["next","следующий (в очереди)","n","Who is next?","Кто следующий?"],
["ahead","впереди, вперёд","adv","The road ahead is closed.","Дорога впереди закрыта."],
["backwards","назад","adv","He took a step backwards.","Он сделал шаг назад."],
["apart","отдельно, порознь","adv","They live apart now.","Теперь они живут отдельно."],
["once","как только, когда","conj","Once you finish, you can go.","Как только закончишь, можешь идти."],
["whenever","когда бы ни, всякий раз","conj","Call me whenever you need help.","Звони мне, когда бы тебе ни понадобилась помощь."],
["while","некоторое время","n","We waited for a while.","Мы подождали некоторое время."],
["till","до (тех пор пока)","prep","We waited till midnight.","Мы ждали до полуночи."],
["till","пока не","conj","Wait till I come back.","Подожди, пока я не вернусь."]
]},
{id:"b1-adj-1", title:"Оценки и свойства", words:[
["advanced","продвинутый, передовой","adj","She is in the advanced class.","Она в продвинутой группе."],
["basic","базовый, основной","adj","I know some basic Spanish.","Я знаю азы испанского."],
["complex","сложный","adj","It is a complex problem.","Это сложная проблема."],
["convenient","удобный","adj","Is Monday convenient for you?","Понедельник тебе удобен?"],
["effective","эффективный","adj","This medicine is very effective.","Это лекарство очень эффективно."],
["essential","необходимый, важнейший","adj","Water is essential for life.","Вода необходима для жизни."],
["practical","практичный, практический","adj","We need a practical solution.","Нам нужно практичное решение."],
["reliable","надёжный","adj","He is a reliable friend.","Он надёжный друг."],
["responsible","ответственный","adj","Parents are responsible for their children.","Родители несут ответственность за своих детей."],
["suitable","подходящий","adj","This film is not suitable for children.","Этот фильм не подходит для детей."],
["valuable","ценный","adj","This ring is very valuable.","Это кольцо очень ценное."],
["powerful","мощный, могущественный","adj","The car has a powerful engine.","У машины мощный двигатель."],
["impressive","впечатляющий","adj","The view was impressive.","Вид был впечатляющим."],
["fascinating","увлекательный, захватывающий","adj","The book is fascinating.","Книга захватывающая."],
["pleasant","приятный","adj","We had a pleasant evening.","Мы приятно провели вечер."],
["unpleasant","неприятный","adj","There was an unpleasant smell.","Был неприятный запах."],
["horrible","ужасный","adj","The food was horrible.","Еда была ужасной."],
["ugly","уродливый","adj","The building is old and ugly.","Здание старое и уродливое."],
["fashionable","модный","adj","Long skirts are fashionable this year.","В этом году модны длинные юбки."],
["old-fashioned","старомодный","adj","His ideas are old-fashioned.","Его идеи старомодны."],
["familiar","знакомый","adj","Her face looks familiar.","Её лицо кажется знакомым."],
["obvious","очевидный","adj","The answer is obvious.","Ответ очевиден."],
["definite","определённый, точный","adj","We need a definite answer.","Нам нужен определённый ответ."],
["proper","правильный, надлежащий","adj","Put the books in their proper place.","Положи книги на их место."],
["fixed","фиксированный, неподвижный","adj","The price is fixed.","Цена фиксированная."],
["due","ожидаемый; подлежащий оплате","adj","The train is due at nine.","Поезд должен прибыть в девять."],
["rare","редкий","adj","This is a rare bird.","Это редкая птица."],
["expected","ожидаемый","adj","The expected result was a win.","Ожидаемым результатом была победа."]
]},
{id:"b1-adj-2", title:"Внешний вид и состояние", words:[
["tiny","крошечный","adj","The baby has tiny hands.","У малыша крошечные ручки."],
["giant","гигантский","adj","A giant wave hit the boat.","Гигантская волна ударила по лодке."],
["giant","гигант, великан","n","The company is a giant in the car industry.","Компания — гигант автомобильной отрасли."],
["medium","средний","adj","I would like a medium coffee.","Я бы хотел средний кофе."],
["sharp","острый, резкий","adj","Be careful, the knife is sharp.","Осторожно, нож острый."],
["smooth","гладкий, ровный","adj","The road is smooth.","Дорога ровная."],
["rough","грубый, неровный","adj","The sea was rough.","На море было волнение."],
["tight","тесный, тугой","adj","These shoes are too tight.","Эти туфли слишком тесные."],
["shiny","блестящий","adj","She has shiny black hair.","У неё блестящие чёрные волосы."],
["pale","бледный","adj","You look pale. Are you ill?","Ты выглядишь бледным. Ты болен?"],
["coloured","цветной, окрашенный","adj","She wore a brightly coloured dress.","На ней было ярко окрашенное платье."],
["dressed","одетый","adj","She was dressed in black.","Она была одета в чёрное."],
["silent","тихий, молчаливый","adj","The room was silent.","В комнате было тихо."],
["still","неподвижный","adj","Keep still while I take the photo.","Не шевелись, пока я фотографирую."],
["peaceful","мирный, спокойный","adj","It is a peaceful village.","Это спокойная деревня."],
["violent","жестокий, насильственный","adj","It was a violent film.","Это был жестокий фильм."],
["uncomfortable","неудобный","adj","This chair is uncomfortable.","Этот стул неудобный."],
["unable","неспособный","adj","I was unable to sleep.","Я не мог уснуть."],
["unfair","несправедливый","adj","The decision was unfair.","Решение было несправедливым."],
["unlikely","маловероятный","adj","It is unlikely to rain today.","Сегодня вряд ли будет дождь."],
["unnecessary","ненужный","adj","This trip is unnecessary.","Эта поездка не нужна."],
["imaginary","воображаемый","adj","The child has an imaginary friend.","У ребёнка воображаемый друг."],
["organized","организованный","adj","She is very organized.","Она очень организованная."],
["prepared","подготовленный, готовый","adj","Be prepared for bad weather.","Будь готов к плохой погоде."],
["experienced","опытный","adj","He is an experienced driver.","Он опытный водитель."],
["involved","вовлечённый, участвующий","adj","Many people were involved in the project.","В проекте участвовало много людей."],
["worth","стоящий (чего-то)","adj","The film is worth seeing.","Фильм стоит посмотреть."],
["used","привыкший (used to)","adj","I am used to getting up early.","Я привык рано вставать.","accustomed"],
["used","подержанный","adj","He bought a used car.","Он купил подержанную машину.","second-hand"]
]},
{id:"b1-adj-3", title:"Общие определения и стороны", words:[
["alternative","альтернативный","adj","Is there an alternative route?","Есть альтернативный маршрут?"],
["equal","равный","adj","All people are equal.","Все люди равны."],
["equal","равняться","v","Two plus two equals four.","Два плюс два равно четыре."],
["total","общий, полный","adj","The total cost is fifty euros.","Общая стоимость — пятьдесят евро."],
["total","итог, общая сумма","n","The total comes to a hundred.","Итого получается сто."],
["private","частный, личный","adj","This is private property.","Это частная собственность."],
["local","местный житель","n","The locals are very friendly.","Местные жители очень дружелюбны."],
["native","родной","adj","Her native language is Spanish.","Её родной язык — испанский."],
["native","уроженец, коренной житель","n","He is a native of Rome.","Он уроженец Рима."],
["leading","ведущий","adj","She is a leading expert on climate.","Она ведущий эксперт по климату."],
["level","ровный, плоский","adj","The ground is level here.","Земля здесь ровная."],
["live","живой, прямой (об эфире)","adj","We watched a live concert.","Мы смотрели живой концерт."],
["live","вживую, в прямом эфире","adv","The match was shown live.","Матч показывали в прямом эфире."],
["living","живой, живущий","adj","He is one of the greatest living writers.","Он один из величайших ныне живущих писателей."],
["living","средства к существованию; жизнь","n","What does he do for a living?","Чем он зарабатывает на жизнь?"],
["outdoor","наружный, на открытом воздухе","adj","I love outdoor sports.","Я люблю спорт на свежем воздухе."],
["indoor","закрытый, комнатный","adj","The hotel has an indoor pool.","В отеле есть крытый бассейн."],
["eastern","восточный","adj","Eastern Europe has cold winters.","В Восточной Европе холодные зимы."],
["western","западный","adj","We visited the western coast.","Мы посетили западное побережье."],
["northern","северный","adj","Northern Italy is famous for its lakes.","Северная Италия славится озёрами."],
["southern","южный","adj","Southern Spain is very hot in summer.","На юге Испании летом очень жарко."],
["worldwide","всемирный","adj","The company has a worldwide reputation.","У компании всемирная репутация."],
["worldwide","по всему миру","adv","The film was shown worldwide.","Фильм показали по всему миру."],
["sexual","половой, сексуальный","adj","The school teaches sexual health.","В школе преподают половое здоровье."],
["sex","пол; секс","n","Write your name, age and sex.","Напишите имя, возраст и пол."],
["state","государственный","adj","She works at a state school.","Она работает в государственной школе."],
["state","заявлять, утверждать","v","Please state your name.","Пожалуйста, назовите своё имя."],
["waste","бросовый, ненужный","adj","Recycle waste paper.","Сдавай макулатуру в переработку."],
["far","дальний","adj","The shop is at the far end of the street.","Магазин в дальнем конце улицы."],
["direct","направлять; руководить","v","Can you direct me to the station?","Не подскажете, как пройти к вокзалу?"]
]},
{id:"b1-adverbs-3", title:"Наречия степени и мнения", words:[
["absolutely","абсолютно, совершенно","adv","You are absolutely right.","Ты абсолютно прав."],
["approximately","приблизительно","adv","The journey takes approximately two hours.","Дорога занимает примерно два часа."],
["fairly","довольно","adv","The test was fairly easy.","Тест был довольно лёгким."],
["slightly","слегка, немного","adv","I am slightly tired.","Я немного устал."],
["highly","очень, весьма","adv","The film is highly recommended.","Фильм очень рекомендуют."],
["heavily","сильно, тяжело","adv","It rained heavily all night.","Всю ночь шёл сильный дождь."],
["strongly","сильно, решительно","adv","I strongly disagree.","Я решительно не согласен."],
["incredibly","невероятно","adv","The hotel was incredibly expensive.","Отель был невероятно дорогим."],
["totally","полностью","adv","I totally agree with you.","Я полностью с тобой согласен."],
["hardly","едва, почти не","adv","I could hardly hear her.","Я едва её слышал."],
["deep","глубоко","adv","The divers went deep under the water.","Ныряльщики ушли глубоко под воду."],
["double","вдвое","adv","The shop charges double at night.","Ночью магазин берёт вдвое больше."],
["extra","дополнительно, особо","adv","The hotel charges extra for breakfast.","Отель берёт дополнительную плату за завтрак."],
["extra","дополнительная плата; дополнение","n","Breakfast is an extra.","Завтрак оплачивается отдельно."],
["cheap","дёшево","adv","I bought the bike cheap.","Я купил велосипед дёшево."],
["close","близко","adv","Stay close to me.","Держись ближе ко мне."],
["further","дальше","adv","The station is further down the road.","Вокзал дальше по дороге."],
["wrong","неправильно","adv","You spelled my name wrong.","Ты неправильно написал моё имя."],
["worse","хуже (наречие)","adv","He plays worse than his brother.","Он играет хуже своего брата."],
["worst","хуже всего","adv","She played worst of all.","Она сыграла хуже всех."],
["indeed","действительно, в самом деле","adv","It is indeed a beautiful place.","Это действительно красивое место."],
["surely","конечно, несомненно","adv","Surely you remember me?","Ты ведь наверняка помнишь меня?"],
["possibly","возможно","adv","I will possibly be late.","Возможно, я опоздаю."],
["obviously","очевидно","adv","Obviously, he was tired.","Очевидно, он устал."],
["naturally","естественно","adv","Naturally, she was upset.","Естественно, она расстроилась."],
["necessarily","обязательно","adv","Expensive things are not necessarily better.","Дорогие вещи не обязательно лучше."],
["personally","лично","adv","Personally, I prefer tea.","Лично я предпочитаю чай."],
["seriously","серьёзно","adv","She was seriously injured.","Она была серьёзно ранена."]
]},
{id:"b1-verbs-4", title:"Ещё глаголы", words:[
["average","составлять в среднем","v","Prices average ten euros a day.","Цены составляют в среднем десять евро в день."],
["board","садиться (на транспорт)","v","Passengers can board the plane now.","Пассажиры могут садиться в самолёт."],
["centre","сосредотачивать(ся)","v","The story centres on a young girl.","История сосредоточена на юной девушке."],
["clear","убирать, очищать","v","Clear the table, please.","Убери со стола, пожалуйста."],
["experience","испытывать, переживать","v","We experienced some problems on the trip.","В поездке мы столкнулись с некоторыми проблемами."],
["face","сталкиваться; быть обращённым к","v","We face a difficult decision.","Перед нами стоит трудное решение."],
["fancy","хотеть; воображать","v","Do you fancy a cup of tea?","Хочешь чашку чая?"],
["fancy","модный, изысканный","adj","We had dinner at a fancy restaurant.","Мы поужинали в шикарном ресторане."],
["feature","показывать, освещать; фигурировать","v","The film features a famous actor.","В фильме снимается известный актёр."],
["head","направляться; возглавлять","v","We headed for the beach.","Мы направились на пляж."],
["key","вводить (с клавиатуры)","v","Key in your password.","Введи пароль."],
["lack","нехватка","n","There is a lack of water in the region.","В регионе нехватка воды."],
["lack","не хватать, испытывать недостаток","v","He lacks experience.","Ему не хватает опыта."],
["lead","лидерство, первое место; поводок","n","Our team is in the lead.","Наша команда лидирует."],
["note","отмечать, замечать","v","Note that the shop closes early on Sundays.","Обрати внимание, что по воскресеньям магазин закрывается рано."],
["point","указывать","v","She pointed at the map.","Она указала на карту."],
["release","выпускать; освобождать","v","The band released a new song.","Группа выпустила новую песню."],
["release","выпуск; освобождение","n","The release of the film is in May.","Выход фильма — в мае."],
["rule","править, управлять","v","The queen ruled for fifty years.","Королева правила пятьдесят лет."],
["set","ставить, устанавливать","v","Set the alarm for seven.","Поставь будильник на семь."],
["set","набор, комплект","n","I bought a set of knives.","Я купил набор ножей."],
["slow","замедлять(ся)","v","The car slowed at the corner.","Машина замедлилась на повороте."],
["sort","сортировать","v","Sort the clothes by colour.","Рассортируй одежду по цвету."],
["suit","подходить, устраивать","v","Does Friday suit you?","Пятница тебя устраивает?"],
["transport","перевозить","v","The goods are transported by ship.","Товары перевозят на корабле."],
["view","рассматривать; смотреть","v","We viewed the house before buying it.","Мы осмотрели дом перед покупкой."],
["queue","очередь","n","There was a long queue at the bank.","В банке была длинная очередь."],
["queue","стоять в очереди","v","We queued for an hour.","Мы стояли в очереди час."],
["mess","беспорядок","n","Your room is a mess.","В твоей комнате беспорядок."],
["mess","устраивать беспорядок; портить","v","Do not mess with my things.","Не трогай мои вещи."]
]},
{id:"b1-nouns-3", title:"Разные существительные", words:[
["better","лучшее","n","I expected better from you.","Я ожидал от тебя лучшего."],
["content","содержание, содержимое","n","The content of the letter was a surprise.","Содержание письма стало сюрпризом."],
["favour","одолжение; поддержка","n","Can you do me a favour?","Можешь сделать мне одолжение?"],
["fighting","драка, боевые действия","n","Fighting broke out in the street.","На улице началась драка."],
["it","самое главное, «то самое»","n","This is it! We have arrived.","Вот и всё! Мы приехали."],
["length","длина, продолжительность","n","The length of the film is two hours.","Продолжительность фильма — два часа."],
["like","что-то подобное","n","I have never seen the like of it.","Я никогда не видел ничего подобного."],
["normal","норма","n","The temperature is above normal.","Температура выше нормы."],
["organizer","организатор","n","The organizers of the festival did a great job.","Организаторы фестиваля отлично поработали."],
["share","доля; акция","n","I paid my share of the bill.","Я оплатил свою долю счёта."],
["trend","тенденция, тренд","n","There is a trend towards smaller families.","Наблюдается тенденция к уменьшению семей."],
["whole","целое","n","Two halves make a whole.","Две половины составляют целое."],
["will","воля; завещание","n","She has a strong will.","У неё сильная воля."],
["worry","беспокойство, тревога","n","Money is a big worry for him.","Деньги — большая тревога для него."],
["young","молодёжь","n","The young want change.","Молодёжь хочет перемен."],
["ring","звонок (телефонный); звон","n","Give me a ring tomorrow.","Позвони мне завтра.","sound"],
["aware","осознающий, знающий","adj","I am aware of the problem.","Я знаю об этой проблеме."],
["various","различные","adj","There are various ways to learn a language.","Есть различные способы выучить язык."],
["indirect","непрямой, косвенный","adj","We took an indirect route.","Мы поехали непрямым маршрутом."],
["ours","наш (без существительного)","pron","This garden is ours.","Этот сад — наш."],
["theirs","их (без существительного)","pron","The blue car is theirs.","Синяя машина — их."],
["plenty","много, достаточно","pron","We have plenty of time.","У нас достаточно времени."],
["whatever","какой бы ни, любой","det","Take whatever books you need.","Бери любые книги, какие нужны."],
["whatever","что бы ни","pron","Do whatever you want.","Делай что хочешь."],
["need","нужно (модальный)","modal","You need not come tomorrow.","Тебе не нужно приходить завтра."],
["ought","следует, должен","modal","You ought to see a doctor.","Тебе следует сходить к врачу."]
]},
{id:"b1-linking", title:"Связки и наречия речи", words:[
["therefore","поэтому, следовательно","adv","It rained, therefore we stayed at home.","Шёл дождь, поэтому мы остались дома."],
["though","хотя","conj","Though it was late, we went out.","Хотя было поздно, мы вышли."],
["though","однако, всё же","adv","It is expensive. It is nice, though.","Это дорого. Но всё же мило."],
["unless","если не","conj","Unless we hurry, we will be late.","Если не поторопимся, опоздаем."],
["whether","ли","conj","I do not know whether he is coming.","Не знаю, придёт ли он."],
["except","кроме как (союз)","conj","I would go, except I have no money.","Я бы поехал, только денег нет."],
["nor","и не, ни","conj","He cannot swim, nor can I.","Он не умеет плавать, и я тоже."],
["nor","также не","adv","I did not see it. Nor did she.","Я этого не видел. Она тоже."],
["neither","тоже не","adv","I do not like fish. Neither do I.","Я не люблю рыбу. Я тоже."],
["now","теперь, когда; раз уж","conj","Now that you are here, we can start.","Теперь, когда ты здесь, мы можем начать."],
["despite","несмотря на","prep","We went out despite the rain.","Мы вышли, несмотря на дождь."],
["unlike","в отличие от","prep","Unlike me, she loves cats.","В отличие от меня, она любит кошек."],
["plus","плюс","prep","Two plus two is four.","Два плюс два — четыре."],
["upon","на, по (книжное)","prep","The house stands upon a hill.","Дом стоит на холме."],
["within","в пределах, в течение","prep","We will arrive within an hour.","Мы приедем в течение часа."],
["throughout","на протяжении, по всему","prep","It rained throughout the day.","Дождь шёл весь день."],
["throughout","повсюду, всё время","adv","The house was painted white throughout.","Дом был выкрашен в белый целиком."]
]},
{id:"b1-speech-adverbs", title:"Наречия речи и способа", words:[
["by","мимо; рядом","adv","Time goes by quickly.","Время проходит быстро."],
["since","с тех пор","adv","He left in May and I have not seen him since.","Он уехал в мае, и с тех пор я его не видел."],
["that","так, настолько","adv","It is not that difficult.","Это не так уж трудно."],
["this","так, настолько (о степени)","adv","I did not expect it to be this cold.","Я не ожидал, что будет настолько холодно."],
["direct","прямо, напрямую","adv","We flew direct to Rome.","Мы летели прямым рейсом в Рим."],
["directly","прямо, непосредственно","adv","She looked directly at me.","Она посмотрела прямо на меня."],
["effectively","эффективно, по сути","adv","The medicine works effectively.","Лекарство действует эффективно."],
["equally","одинаково, в равной степени","adv","Both answers are equally good.","Оба ответа одинаково хороши."],
["generally","обычно, в целом","adv","I generally get up at seven.","Обычно я встаю в семь."],
["mainly","в основном","adv","The shop sells mainly books.","Магазин продаёт в основном книги."],
["particularly","особенно","adv","I particularly like this song.","Мне особенно нравится эта песня."],
["specifically","конкретно, специально","adv","The course is designed specifically for beginners.","Курс разработан специально для начинающих."],
["typically","обычно, как правило","adv","Typically, I work from nine to five.","Как правило, я работаю с девяти до пяти."],
["similarly","аналогично, так же","adv","Similarly, the second test was easy.","Аналогично, второй тест был лёгким."],
["simply","просто","adv","Simply press the button.","Просто нажми на кнопку."],
["perfectly","прекрасно, совершенно","adv","I understand you perfectly.","Я прекрасно тебя понимаю."],
["properly","правильно, как следует","adv","Close the door properly.","Закрой дверь как следует."],
["successfully","успешно","adv","She successfully passed the exam.","Она успешно сдала экзамен."],
["indoors","в помещении","adv","Stay indoors when it rains.","Оставайся в помещении, когда идёт дождь."],
["outdoors","на открытом воздухе","adv","We had lunch outdoors.","Мы обедали на свежем воздухе."]
]}
],
practice:{
"effort|n":{collocations:[["make an effort","приложить усилие"],["worth the effort","стоит усилий"]],examples:[["She made a big effort to finish on time.","Она очень постаралась закончить вовремя."]]},
"impression|n":{collocations:[["make an impression","произвести впечатление"],["first impression","первое впечатление"]],examples:[["First impressions are important.","Первое впечатление важно."]]},
"appointment|n":{collocations:[["make an appointment","записаться на приём"],["have an appointment with","быть записанным к"]],examples:[["I made an appointment with the doctor.","Я записался к врачу."]]},
"responsibility|n":{collocations:[["take responsibility for","взять ответственность за"],["a sense of responsibility","чувство ответственности"]],examples:[["Who takes responsibility for the mistake?","Кто берёт на себя ответственность за ошибку?"]]},
"risk|n":{collocations:[["take a risk","рискнуть"],["at risk","в опасности"]],examples:[["Children are most at risk.","Дети в наибольшей опасности."]]},
"damage|n":{collocations:[["cause damage","причинить ущерб"],["serious damage","серьёзный ущерб"]],examples:[["The fire caused serious damage.","Пожар причинил серьёзный ущерб."]]},
"pressure|n":{collocations:[["under pressure","под давлением"],["put pressure on","давить на"]],examples:[["Do not put pressure on the children.","Не дави на детей."]]},
"doubt|n":{collocations:[["no doubt","без сомнения"],["in doubt","под сомнением"]],examples:[["No doubt she will win.","Без сомнения, она победит."]]},
"achievement|n":{collocations:[["a great achievement","большое достижение"],["a sense of achievement","чувство удовлетворения от достигнутого"]],examples:[["Finishing the marathon gave me a sense of achievement.","Финиш марафона дал мне чувство удовлетворения."]]},
"agreement|n":{collocations:[["reach an agreement","достичь соглашения"],["in agreement","согласны"]],examples:[["We reached an agreement after a long talk.","Мы достигли соглашения после долгого разговора."]]},
"complaint|n":{collocations:[["make a complaint","подать жалобу"],["a letter of complaint","письмо с жалобой"]],examples:[["She made a complaint to the manager.","Она подала жалобу менеджеру."]]},
"deal|n":{collocations:[["make a deal","заключить сделку"],["a good deal","выгодная сделка"],["a great deal of","много"]],examples:[["It took a great deal of time.","Это заняло много времени."]]},
"charge|n":{collocations:[["free of charge","бесплатно"],["in charge of","ответственный за"]],examples:[["Who is in charge of the project?","Кто отвечает за проект?"]]},
"queue|n":{collocations:[["stand in a queue","стоять в очереди"],["jump the queue","пролезть без очереди"]],examples:[["Do not jump the queue!","Не лезь без очереди!"]]},
"apologize|v":{collocations:[["apologize for","извиниться за"],["apologize to","извиниться перед"]],examples:[["He apologized to her for the noise.","Он извинился перед ней за шум."]]},
"remind|v":{collocations:[["remind somebody of","напоминать кому-то о"],["remind somebody to do","напомнить кому-то сделать"]],examples:[["This song reminds me of my childhood.","Эта песня напоминает мне о детстве."]]},
"warn|v":{collocations:[["warn about","предупреждать о"],["warn against","предостерегать от"]],examples:[["They warned us about the storm.","Они предупредили нас о буре."]]},
"concentrate|v":{collocations:[["concentrate on","сосредоточиться на"]],examples:[["Concentrate on your homework.","Сосредоточься на домашнем задании."]]},
"participate|v":{collocations:[["participate in","участвовать в"]],examples:[["Everyone can participate in the competition.","Все могут участвовать в соревновании."]]},
"suffer|v":{collocations:[["suffer from","страдать от"]],examples:[["He suffers from back pain.","Он страдает от боли в спине."]]},
"survive|v":{collocations:[["survive an accident","выжить в аварии"],["survive on","выживать на"]],examples:[["They survived on rice and water.","Они выживали на рисе и воде."]]},
"escape|v":{collocations:[["escape from","сбежать из"]],examples:[["The bird escaped from its cage.","Птица вырвалась из клетки."]]},
"consist|v":{collocations:[["consist of","состоять из"]],examples:[["The book consists of ten chapters.","Книга состоит из десяти глав."]]},
"belief|n":{collocations:[["a strong belief","твёрдая вера"],["religious beliefs","религиозные убеждения"]],examples:[["She has strong religious beliefs.","У неё твёрдые религиозные убеждения."]]},
"aware|adj":{collocations:[["aware of","знающий о"]],examples:[["Are you aware of the risks?","Ты знаешь о рисках?"]]},
"responsible|adj":{collocations:[["responsible for","ответственный за"]],examples:[["She is responsible for the project.","Она отвечает за проект."]]},
"familiar|adj":{collocations:[["familiar with","знакомый с"]],examples:[["I am familiar with this software.","Я знаком с этой программой."]]},
"keen|adj":{collocations:[["keen on","увлечённый чем-то"]],examples:[["She is keen on photography.","Она увлекается фотографией."]]},
"proud|adj":{collocations:[["proud of","гордящийся"]],examples:[["We are proud of our team.","Мы гордимся нашей командой."]]},
"worth|adj":{collocations:[["worth doing","стоит сделать"],["worth the money","стоит своих денег"]],examples:[["The museum is worth visiting.","Музей стоит посетить."]]},
"guilty|adj":{collocations:[["guilty of","виновный в"],["feel guilty","чувствовать вину"]],examples:[["I feel guilty about forgetting her birthday.","Мне стыдно, что я забыл о её дне рождения."]]},
"suitable|adj":{collocations:[["suitable for","подходящий для"]],examples:[["This job is suitable for students.","Эта работа подходит студентам."]]},
"despite|prep":{collocations:[["despite the fact that","несмотря на то, что"]],examples:[["Despite the rain, the match went on.","Несмотря на дождь, матч продолжался."]]},
"throughout|prep":{collocations:[["throughout the year","в течение всего года"],["throughout the world","по всему миру"]],examples:[["The shop is open throughout the year.","Магазин открыт круглый год."]]}
},
confusables:[
["historic|adj","historical|adj"],["economic|adj","economical|adj"],["sensible|adj","sensitive|adj"],["injure|v","damage|v"],["injury|n","damage|n"],
["remind|v","remember|v"],["convince|v","persuade|v"],["prove|v","test|v"],["claim|v","say|v"],["admit|v","accept|v"],
["annoyed|adj","annoying|adj"],["frightened|adj","frightening|adj"],["disappointed|adj","disappointing|adj"],["embarrassed|adj","embarrassing|adj"],["relaxed|adj","relaxing|adj"],
["lend|v","borrow|v"],["rent|v","hire|v"],["profit|n","benefit|n"],["price|n","value|n"],["salary|n","payment|n"],
["legal|adj","lawful|adj"],["guilty|adj","innocent|adj"],["punish|v","reward|v"],["steal|v","rob|v"],["thief|n","criminal|n"],
["politics|n","policy|n"],["election|n","vote|n"],["nation|n","country|n"],["region|n","area|n"],["border|n","edge|n"],
["fasten|v","tie|v"],["fold|v","bend|v"],["attach|v","connect|v"],["gather|v","collect|v"],["spread|v","expand|v"],
["occur|v","happen|v"],["remain|v","stay|v"],["survive|v","live|v"],["tend|v","usually|adv"],["intend|v","plan|v"],
["effective|adj","efficient|adj"],["essential|adj","necessary|adj"],["convenient|adj","comfortable|adj"],["reliable|adj","responsible|adj"],["valuable|adj","expensive|adj"],
["tiny|adj","small|adj"],["giant|adj","huge|adj"],["sharp|adj","strong|adj"],["rough|adj","smooth|adj"],["tight|adj","narrow|adj"],
["despite|prep","although|conj"],["unless|conj","if|conj"],["whether|conj","if|conj"],["therefore|adv","so|conj"],["though|adv","however|adv"],
["hardly|adv","hard|adv"],["highly|adv","high|adv"],["directly|adv","direct|adv"],["fairly|adv","quite|adv"],["slightly|adv","a bit|n"],
["previous|adj","last|det"],["current|adj","present|adj"],["latest|adj","last|det"],["eventually|adv","finally|adv"],["meanwhile|adv","while|conj"],
["used|adj|accustomed","used|adj|second-hand"],["lie|v|down","lie|v|untruth"],["ring|n|jewellery","ring|n|sound"],["race|n|competition","race|n|people"],["bank|n|money","bank|n|river"]
]
};
if(typeof module!=="undefined")module.exports=OXFORD_B1;
