// Интерфейс независимых тематических маршрутов и блиц-экзамена.
let thematicCurrent=null,thematicSession=null,thematicClock=null,thematicCooldownClock=null,thematicMonoBase=null,thematicMonoMode=null,thematicLessonClock=null;
const thematicMeta=id=>THEMATIC_META.find(x=>x.id===id);
const thematicWords=id=>THEMATIC_WORDS[id];
const thematicTopic=id=>LearningCore.thematicTopic(S,id);
const thematicKey=(id,i)=>thematicWords(id)[i][0];
const thematicWordIndex=(id,key)=>thematicWords(id).findIndex(w=>w[0]===key);
const thematicKnownCount=t=>Object.values(t.words).filter(r=>r.box>=3).length;
const thematicDue=id=>{const t=thematicTopic(id),day=today();return thematicWords(id).map((_,i)=>i).filter(i=>t.introduced[thematicKey(id,i)]&&t.words[thematicKey(id,i)].due<=day);};
const thematicIntroduced=id=>Object.keys(thematicTopic(id).introduced).length;
const thematicAccuracy=t=>t.stats.ok+t.stats.bad?Math.round(100*t.stats.ok/(t.stats.ok+t.stats.bad)):null;
const thematicPerf=()=>typeof performance!=="undefined"&&Number.isFinite(performance.now())?performance.now():0;
const thematicMono=()=>thematicMonoBase?thematicMonoBase.value+(thematicPerf()-thematicMonoBase.perf):thematicPerf();
async function thematicSyncMono(){const perf=thematicPerf();try{if(window.nativeExamClock&&thematicMonoMode!=="web"){const value=await Promise.race([window.nativeExamClock(),new Promise(r=>setTimeout(()=>r(NaN),350))]);if(Number.isFinite(value)){thematicMonoMode="native";thematicMonoBase={value,perf:thematicPerf()};return value;}}}catch(e){}thematicMonoMode="web";thematicMonoBase={value:perf,perf};return perf;}
function thematicDayRec(topic){const d=today();return topic.days[d]||(topic.days[d]={n:0,q:0,ok:0,bad:0});}
function thematicHomeCardHtml(){
  const root=LearningCore.thematicEnsure(S),started=Object.values(root.topics).reduce((n,t)=>n+Object.keys(t.introduced||{}).length,0),passed=Object.values(root.equipmentRewards).length;
  return `<section class="card theme-entry" id="thematicEntry"><div class="row"><span class="theme-icon">🧭</span><div class="grow"><div class="eyebrow">Отдельная программа</div><h2 style="font-size:20px;margin:3px 0 5px">Тематические маршруты</h2><p class="small muted">10 жизненных тем по 100 слов — со своим прогрессом, повторением и блиц-экзаменом.</p><div class="row" style="gap:8px;flex-wrap:wrap"><span class="chip accent">изучено ${started}/1000</span>${passed?`<span class="chip good">наборов ${passed}/10</span>`:""}</div></div><span aria-hidden="true">›</span></div></section>`;
}
function wireThematicHomeCard(){const b=$("#thematicEntry");if(b)b.onclick=()=>go("thematic");}
function renderThematicCatalog(){
  thematicCurrent=null;clearInterval(thematicCooldownClock);
  const cards=THEMATIC_META.map(m=>{const t=thematicTopic(m.id),introduced=Object.keys(t.introduced).length,due=thematicDue(m.id).length,got=!!S.thematic.equipmentRewards[m.equipmentSetId],lock=LearningCore.thematicExamCooldown(t,Date.now());return `<button class="theme-card" data-theme-id="${m.id}"><span class="theme-icon">${m.icon}</span><span><b>${esc(m.title)}</b><span class="small muted">${esc(m.description)}</span><span class="bar"><i style="width:${introduced}%"></i></span></span><span class="theme-count">${introduced}/100${due?`<br><span style="color:var(--warn)">повторить ${due}</span>`:""}${got?`<br><span style="color:var(--good)">награда ✓</span>`:lock?`<br><span class="cooldown" data-lock="${t.exam.lockedUntil}"></span>`:""}</span></button>`;}).join("");
  view().innerHTML=`<div class="row between"><div><div class="eyebrow">Самостоятельная программа</div><h1 style="font-size:27px;margin:3px 0">Тематические маршруты</h1></div><button class="icon-btn" id="themeBack" aria-label="Назад">${ICONS.close}</button></div><p class="muted">Выбирай любую тему независимо от основной программы. У каждой — собственные слова, интервалы и экзамен.</p><div class="theme-grid">${cards}</div>`;
  $("#themeBack").onclick=()=>go("home");document.querySelectorAll("[data-theme-id]").forEach(b=>b.onclick=()=>renderThematicTopic(b.dataset.themeId));thematicWireCooldowns(renderThematicCatalog);
}
function renderThematicTopic(id){
  thematicCurrent=id;clearInterval(thematicCooldownClock);const meta=thematicMeta(id),topic=thematicTopic(id),introduced=thematicIntroduced(id),known=thematicKnownCount(topic),due=thematicDue(id).length,acc=thematicAccuracy(topic),ready=LearningCore.thematicExamReady(topic),lock=LearningCore.thematicExamCooldown(topic,Date.now()),got=!!S.thematic.equipmentRewards[meta.equipmentSetId];
  if(topic.exam.passedAt&&!got){S.thematic.equipmentRewards[meta.equipmentSetId]=today();S.ach=S.ach||{};S.ach["topic_"+id]=S.ach["topic_"+id]||today();save();return renderThematicTopic(id);}
  if(topic.exam.active){thematicShowExam(id);return;}
  view().innerHTML=`<div class="row between"><button class="btn ghost small" id="themeBack">‹ Все маршруты</button><button class="btn ghost small" id="themeSettings">Настройки</button></div><section class="card"><div class="theme-head"><span class="theme-icon">${meta.icon}</span><div><div class="eyebrow">Тематический маршрут</div><h2>${esc(meta.title)}</h2><p class="small muted">${esc(meta.description)}</p></div></div><div class="theme-stat-grid"><div class="theme-stat"><b>${introduced}/100</b><span>пройдено впервые</span></div><div class="theme-stat"><b>${known}/100</b><span>в статусе «знаю»</span></div><div class="theme-stat"><b>${acc===null?"—":acc+"%"}</b><span>точность ответов</span></div></div></section><div class="theme-actions"><button class="btn block huge" id="themeLearn" ${introduced>=100?"disabled":""}>${introduced>=100?"Все слова просмотрены":"Изучить новые · "+Math.min(S.thematic.settings.batchSize,100-introduced)}</button><button class="btn secondary block" id="themeReview" ${due?"":"disabled"}>Повторить${due?` · ${due}`:""}</button><button class="btn secondary block" id="themeList">Список 100 слов</button></div><section class="theme-reward ${got?"got":""}"><div class="row between"><div><div class="eyebrow">Блиц-экзамен</div><b>${got?"Награда получена":esc(meta.reward)}</b></div><span style="font-size:28px">${got?"🏆":"🎁"}</span></div><p class="small muted">100 слов без повторов · 6 секунд на ответ · максимум 4 ошибки.</p>${lock?`<button class="btn secondary block" disabled>Новая попытка через <span class="cooldown" data-lock="${topic.exam.lockedUntil}"></span></button>`:`<button class="btn block" id="themeExam" ${ready?"":"disabled"}>${ready?"Начать блиц":"Сначала пройти все слова · "+introduced+"/100"}</button>`}</section><button class="btn ghost block" id="themeReset" style="color:var(--bad)">Сбросить прогресс маршрута</button>`;
  $("#themeBack").onclick=renderThematicCatalog;$("#themeSettings").onclick=thematicSettingsSheet;$("#themeLearn").onclick=()=>thematicStartLearn(id);$("#themeReview").onclick=()=>thematicStartQuiz(id,sample(thematicDue(id),S.thematic.settings.reviewSize),"Повторение");$("#themeList").onclick=()=>thematicWordList(id);if($("#themeExam"))$("#themeExam").onclick=()=>thematicExamWarning(id);$("#themeReset").onclick=()=>thematicResetPrompt(id);thematicWireCooldowns(()=>renderThematicTopic(id));
}
// Cancels only callbacks belonging to a discarded lesson screen. Never pauses the exam.
function thematicCancelLesson(){clearTimeout(thematicLessonClock);thematicLessonClock=null;thematicSession=null;}
function thematicLevelHtml(w){const info=WordLevels.lookup(w[0],w[2]);return info?`<span title="${esc(WordLevels.sources[info.source].title)} · ориентир для слова и части речи">${esc(info.level)}</span> · `:"";}
function thematicStartLearn(id){
  thematicCancelLesson();
  const topic=thematicTopic(id),size=S.thematic.settings.batchSize,items=thematicWords(id).map((_,i)=>i).filter(i=>!topic.introduced[thematicKey(id,i)]).slice(0,size);if(!items.length){renderThematicTopic(id);return;}inSession=true;thematicSession={kind:"learn",id,items,k:0,shown:[]};thematicLearnStep();
}
function thematicLearnStep(){
  clearTimeout(thematicLessonClock);
  const s=thematicSession,id=s.id;if(s.k>=s.items.length){thematicStartQuiz(id,s.shown,"Проверка порции");return;}const i=s.items[s.k],w=thematicWords(id)[i];
  view().innerHTML=`<div class="sess-top"><button class="icon-btn" id="themeExit" aria-label="Выйти">${ICONS.close}</button><div class="bar"><i style="width:${s.k/s.items.length*100}%"></i></div><span class="small muted num">${s.k+1}/${s.items.length}</span></div><section class="card" style="text-align:center;padding:34px 18px"><div class="theme-stage">${thematicLevelHtml(w)}${POS[w[2]]||w[2]}</div><div class="word" style="margin:18px 0 8px">${esc(w[0])}</div><div class="ru">${esc(w[1])}</div><p class="ex">${esc(w[3])}</p><p class="ex-ru">${esc(w[4])}</p><button class="speak" id="themeSpeak" aria-label="Озвучить">${ICONS.sound}</button></section><button class="btn block huge" id="themeNext">Дальше</button>`;
  $("#themeExit").onclick=()=>thematicLeaveLesson(id);$("#themeSpeak").onclick=()=>speak(w[0]);$("#themeNext").onclick=()=>{const topic=thematicTopic(id),key=w[0],fresh=!topic.introduced[key];LearningCore.thematicIntroduce(topic,key,today());if(fresh)thematicDayRec(topic).n++;s.shown.push(i);s.k++;save();thematicLearnStep();};if(S.thematic.settings.autoSpeak)thematicLessonClock=setTimeout(()=>{if(thematicSession===s&&inSession)speak(w[0]);},120);
}
function thematicStartQuiz(id,items,title){thematicCancelLesson();if(!items.length){inSession=false;renderThematicTopic(id);return;}inSession=true;thematicSession={kind:"quiz",id,items,k:0,title,res:[]};thematicQuizStep();}
function thematicQuizOptions(id,i){const words=thematicWords(id),right=words[i][1],other=shuffle(words.map((w,n)=>({n,ru:w[1]})).filter(x=>x.n!==i&&x.ru!==right)).filter((x,n,a)=>a.findIndex(y=>y.ru===x.ru)===n).slice(0,3).map(x=>x.ru);return shuffle([right,...other]);}
function thematicQuizStep(){
  const s=thematicSession;if(!s||s.kind!=="quiz"||!inSession)return;if(s.k>=s.items.length){inSession=false;const ok=s.res.filter(Boolean).length;view().innerHTML=`<section class="card" style="text-align:center"><div style="font-size:42px">${ok===s.res.length?"✨":"🦊"}</div><h2>${esc(s.title)} завершена</h2><p class="muted">Верно ${ok} из ${s.res.length}. Интервалы тематического маршрута обновлены отдельно.</p><button class="btn block" id="themeDone">Вернуться к маршруту</button></section>`;$("#themeDone").onclick=()=>renderThematicTopic(s.id);return;}const id=s.id,i=s.items[s.k],w=thematicWords(id)[i],opts=thematicQuizOptions(id,i);
  view().innerHTML=`<div class="sess-top"><button class="icon-btn" id="themeExit" aria-label="Выйти">${ICONS.close}</button><div class="bar"><i style="width:${s.k/s.items.length*100}%"></i></div><span class="small muted num">${s.k+1}/${s.items.length}</span></div><section class="card blitz-question"><div class="theme-stage">${esc(s.title)}</div><div class="word">${esc(w[0])}</div><button class="speak" id="themeSpeak">${ICONS.sound}</button></section><div class="opts">${opts.map((x,n)=>`<button class="opt" data-answer="${esc(x)}"><span class="k">${n+1}</span><span>${esc(x)}</span></button>`).join("")}</div>`;
  $("#themeExit").onclick=()=>thematicLeaveLesson(id);$("#themeSpeak").onclick=()=>speak(w[0]);document.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>{const ok=b.dataset.answer===w[1];document.querySelectorAll("[data-answer]").forEach(x=>{x.disabled=true;if(x.dataset.answer===w[1])x.classList.add("ok");});if(!ok)b.classList.add("no");const topic=thematicTopic(id),rec=thematicDayRec(topic);LearningCore.thematicGrade(topic,w[0],ok,today(),addDays);rec.q++;ok?rec.ok++:rec.bad++;s.res.push(ok);s.k++;save();thematicLessonClock=setTimeout(()=>{if(thematicSession===s&&inSession)thematicQuizStep();},480);});
}
function thematicLeaveLesson(id){confirmSheet("Прервать занятие?","Пройденные карточки и ответы уже сохранены.","Прервать",()=>{inSession=false;thematicCancelLesson();renderThematicTopic(id);});}
function thematicWordList(id){
  const topic=thematicTopic(id),rows=thematicWords(id).map((w,i)=>{const r=topic.words[w[0]],status=!topic.introduced[w[0]]?0:r.box>=6?3:r.box>=3?2:1;return `<button class="wrow" data-theme-word="${i}"><i class="dot s${status}"></i><span class="en">${esc(w[0])}</span><span class="tr">${esc(w[1])}</span></button>`;}).join("");sheet(`<div class="row between"><div><div class="eyebrow">${esc(thematicMeta(id).title)}</div><h2>Список 100 слов</h2></div><button class="icon-btn" data-close>${ICONS.close}</button></div><div class="lvl theme-word-list">${rows}</div>`);document.querySelectorAll("[data-theme-word]").forEach(b=>b.onclick=()=>thematicWordSheet(id,+b.dataset.themeWord));
}
function thematicWordSheet(id,i){const w=thematicWords(id)[i],topic=thematicTopic(id),r=topic.words[w[0]];sheet(`<div class="row between"><span class="theme-stage">${thematicLevelHtml(w)}${POS[w[2]]||w[2]}</span><button class="icon-btn" data-close>${ICONS.close}</button></div><div class="word md">${esc(w[0])}</div><div class="ru">${esc(w[1])}</div><p class="ex">${esc(w[3])}</p><p class="ex-ru">${esc(w[4])}</p>${r?`<p class="small muted">Верно ${r.ok} · ошибок ${r.bad} · ячейка ${r.box}/6</p><button class="btn secondary block" id="themeWordReset">Сбросить это слово</button>`:""}`);if($("#themeWordReset"))$("#themeWordReset").onclick=()=>{delete topic.words[w[0]];delete topic.introduced[w[0]];save();thematicWordList(id);toast("Слово возвращено в новые");};}
function thematicSettingsSheet(){const set=S.thematic.settings;sheet(`<div class="row between"><h2>Настройки маршрутов</h2><button class="icon-btn" data-close>${ICONS.close}</button></div><div class="set-row"><span>Новых слов в порции</span><div class="seg" id="themeBatch">${[5,10].map(n=>`<button data-n="${n}" class="${set.batchSize===n?"on":""}">${n}</button>`).join("")}</div></div><div class="set-row"><span>Слов в повторении</span><div class="seg" id="themeReviewSize">${[10,15,20].map(n=>`<button data-n="${n}" class="${set.reviewSize===n?"on":""}">${n}</button>`).join("")}</div></div><div class="set-row"><span>Автоозвучка новых слов</span><button class="toggle ${set.autoSpeak?"on":""}" id="themeAuto"></button></div><p class="small muted">Эти настройки действуют только в тематических маршрутах.</p>`);$("#themeBatch").querySelectorAll("button").forEach(b=>b.onclick=()=>{set.batchSize=+b.dataset.n;save();thematicSettingsSheet();});$("#themeReviewSize").querySelectorAll("button").forEach(b=>b.onclick=()=>{set.reviewSize=+b.dataset.n;save();thematicSettingsSheet();});$("#themeAuto").onclick=()=>{set.autoSpeak=!set.autoSpeak;save();thematicSettingsSheet();};}
function thematicResetPrompt(id){const topic=thematicTopic(id),passed=topic.exam.passedAt;confirmSheet(`Сбросить маршрут «${thematicMeta(id).title}»?`,"Слова и статистика начнутся заново. Уже полученные достижение и комплект сохранятся.","Сбросить",()=>{delete S.thematic.topics[id];const fresh=thematicTopic(id);fresh.exam.passedAt=passed;save();renderThematicTopic(id);toast("Маршрут сброшен");},true);}
function thematicExamWarning(id){sheet(`<div class="row between"><h2>Блиц: ${esc(thematicMeta(id).title)}</h2><button class="icon-btn" data-close>${ICONS.close}</button></div><p>В экзамене все 100 слов идут в случайном порядке без повторений.</p><ul class="steps"><li><b>6 секунд на каждый ответ</b><p class="small muted">Пропущенное слово считается ошибкой.</p></li><li><b>Пятая ошибка завершает попытку</b><p class="small muted">Любой провал блокирует новую попытку на 30 минут.</p></li><li><b>Паузы нет</b><p class="small muted">При сворачивании и закрытии приложения время продолжает идти.</p></li></ul><div class="grid2"><button class="btn secondary" data-close>Вернуться</button><button class="btn" id="themeExamStart">Начать блиц</button></div>`);$("#themeExamStart").onclick=async()=>{const start=$("#themeExamStart");start.disabled=true;const mono=await thematicSyncMono();closeSheet();const words=thematicWords(id).map(w=>w[0]);try{LearningCore.thematicExamStart(thematicTopic(id),words,Date.now(),mono);save();thematicShowExam(id);}catch(e){toast(e.message);renderThematicTopic(id);}};}
function thematicExamRunning(){return !!(thematicCurrent&&thematicTopic(thematicCurrent).exam.active);}
async function thematicShowExam(id){
  thematicCurrent=id;inSession=true;clearInterval(thematicClock);await thematicSyncMono();const topic=thematicTopic(id),tick=LearningCore.thematicExamTick(topic,Date.now(),thematicMono());if(tick.status!=="active"){save();thematicExamResult(id,tick);return;}const active=topic.exam.active,key=active.order[active.index],i=thematicWordIndex(id,key),w=thematicWords(id)[i],opts=thematicQuizOptions(id,i);
  view().innerHTML=`<div class="sess-top"><button class="icon-btn" id="themeExamExit" aria-label="Выйти">${ICONS.close}</button><div class="bar blitz-bar"><i id="blitzFill" style="width:100%"></i></div><span class="blitz-clock" id="blitzClock">6.0</span></div><div class="row between"><span class="small muted num">${active.index+1}/100</span><span class="blitz-errors" aria-label="Ошибки">${Array.from({length:5},(_,n)=>`<i class="${n<active.errors?"on":""}"></i>`).join("")}</span></div><section class="card blitz-question"><div class="theme-stage">Выбери перевод</div><div class="word">${esc(w[0])}</div></section><div class="opts">${opts.map((x,n)=>`<button class="opt" data-blitz-answer="${esc(x)}"><span class="k">${n+1}</span><span>${esc(x)}</span></button>`).join("")}</div>`;
  $("#themeExamExit").onclick=()=>thematicRequestExamExit("thematic");document.querySelectorAll("[data-blitz-answer]").forEach(b=>b.onclick=async()=>{clearInterval(thematicClock);document.querySelectorAll("[data-blitz-answer]").forEach(x=>x.disabled=true);await thematicSyncMono();const result=LearningCore.thematicExamAnswer(topic,b.dataset.blitzAnswer===w[1],Date.now(),thematicMono());save();if(result.status==="active")thematicShowExam(id);else thematicExamResult(id,result);});thematicClock=setInterval(()=>thematicExamPulse(id),100);
}
function thematicExamPulse(id){const topic=thematicTopic(id),result=LearningCore.thematicExamTick(topic,Date.now(),thematicMono());if(result.status!=="active"||result.missed){save();clearInterval(thematicClock);if(result.status==="active")thematicShowExam(id);else thematicExamResult(id,result);return;}const ms=Math.max(0,result.remaining),clock=$("#blitzClock"),fill=$("#blitzFill");if(clock)clock.textContent=(ms/1000).toFixed(1);if(fill)fill.style.width=(ms/LearningCore.THEMATIC_QUESTION_MS*100)+"%";}
function thematicExamResult(id,result){
  clearInterval(thematicClock);inSession=false;const meta=thematicMeta(id),passed=result.status==="passed"||thematicTopic(id).exam.lastResult?.passed;if(passed){S.thematic.equipmentRewards[meta.equipmentSetId]=S.thematic.equipmentRewards[meta.equipmentSetId]||today();save();if(typeof unlock==="function")unlock("topic_"+id);}const errors=thematicTopic(id).exam.lastResult?.errors||0;
  view().innerHTML=`<section class="card" style="text-align:center"><div style="font-size:48px">${passed?"🏆":"⏳"}</div><h2>${passed?"Блиц пройден":"Попытка завершена"}</h2><p class="muted">${passed?`${esc(meta.reward)} открыт. Ошибок: ${errors}.`:`Новая попытка откроется через 30 минут. Ошибок: ${errors}.`}</p>${passed?`<div class="theme-reward got">Получено достижение «${esc(meta.title)}» и комплект <b>${esc(meta.reward)}</b>.</div>`:`<p class="cooldown" data-lock="${thematicTopic(id).exam.lockedUntil}"></p>`}<button class="btn block" id="themeResultBack">Вернуться к маршруту</button></section>`;$("#themeResultBack").onclick=()=>renderThematicTopic(id);thematicWireCooldowns(()=>renderThematicTopic(id));
}
function thematicRequestExamExit(target){confirmSheet("Завершить блиц?","Попытка будет провалена, а новая заблокируется на 30 минут.","Завершить",()=>{const id=thematicCurrent;clearInterval(thematicClock);const result=LearningCore.thematicExamAbort(thematicTopic(id),Date.now());save();inSession=false;if(target==="thematic")thematicExamResult(id,result);else go(target);},true);}
function thematicWireCooldowns(onDone){
  clearInterval(thematicCooldownClock);
  const locks=[...document.querySelectorAll("[data-lock]")];if(!locks.length)return;
  const connected=()=>locks.some(x=>x.isConnected);
  const paint=()=>{
    // A hidden app keeps its deadline; a detached screen must not reopen itself.
    if(!connected()){clearInterval(thematicCooldownClock);return;}
    let active=false;
    locks.forEach(x=>{const ms=Math.max(0,+x.dataset.lock-Date.now());if(ms){active=true;const total=Math.ceil(ms/1000),m=Math.floor(total/60),s=total%60;x.textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;}else x.textContent="00:00";});
    if(!active){clearInterval(thematicCooldownClock);if(onDone)setTimeout(()=>{if(connected())onDone();},0);}
  };
  paint();if(connected()&&locks.some(x=>+x.dataset.lock>Date.now()))thematicCooldownClock=setInterval(paint,1000);
}
function thematicOnVisible(){if(document.visibilityState==="visible"&&thematicExamRunning())thematicShowExam(thematicCurrent);}
