// Слова 1–500, уровень B1–B2. Формат: [английское, перевод, часть речи, пример]
const WORDS_A = [
// Уровень 1 — мнение и мышление
["assume","предполагать, допускать","v","I assume you have read the report."],
["consider","рассматривать, считать","v","We should consider all the options."],
["doubt","сомневаться; сомнение","v","I doubt that he will come on time."],
["estimate","оценивать (приблизительно)","v","Experts estimate the cost at two million."],
["imply","подразумевать, намекать","v","Are you implying that I was wrong?"],
["insist","настаивать","v","She insisted on paying for dinner."],
["judge","судить, оценивать","v","Do not judge people by their clothes."],
["recall","вспоминать","v","I cannot recall his name."],
["recognize","узнавать, признавать","v","I did not recognize her at first."],
["regard","считать, рассматривать как","v","He is regarded as the best player."],
["suppose","полагать, предполагать","v","I suppose you are right."],
["conclude","делать вывод, заключать","v","The report concludes that sales will grow."],
["convince","убеждать","v","He convinced me to stay."],
["deny","отрицать","v","She denied taking the money."],
["determine","определять, устанавливать","v","The test will determine your level."],
["emphasize","подчёркивать","v","The teacher emphasized the importance of practice."],
["evaluate","оценивать","v","We need to evaluate the results."],
["expect","ожидать","v","I expect the meeting to end by six."],
["hesitate","колебаться","v","Do not hesitate to ask."],
["identify","определять, выявлять","v","Can you identify the problem?"],
["intend","намереваться","v","I intend to finish this today."],
["interpret","толковать, интерпретировать","v","How do you interpret these results?"],
["observe","наблюдать, замечать","v","We observed a change in behaviour."],
["perceive","воспринимать","v","The plan was perceived as risky."],
["predict","предсказывать","v","Nobody can predict the future."],
["realize","осознавать","v","I realized I had made a mistake."],
["reflect","размышлять; отражать","v","Take time to reflect on your decision."],
["refuse","отказываться","v","He refused to sign the contract."],
["reject","отвергать","v","The board rejected the proposal."],
["rely","полагаться","v","You can rely on me."],
["remind","напоминать","v","Remind me to call him."],
["suspect","подозревать","v","I suspect he is lying."],
["tend","иметь склонность","v","I tend to wake up early."],
["underestimate","недооценивать","v","Never underestimate your opponent."],
["acknowledge","признавать","v","She acknowledged her mistake."],
["claim","утверждать; претендовать","v","He claims he was at home."],
["confirm","подтверждать","v","Please confirm your booking."],
["assess","оценивать, определять","v","The doctor assessed the damage."],
["presume","предполагать, полагать","v","I presume the meeting is cancelled."],
["conceive","представлять себе, задумывать","v","I cannot conceive of life without music."],
["reckon","считать, полагать (разг.)","v","I reckon it will rain."],
["ponder","обдумывать","v","She pondered the question for a while."],
["justify","оправдывать, обосновывать","v","How do you justify this decision?"],
["contemplate","обдумывать, созерцать","v","He is contemplating a career change."],
["deduce","делать вывод","v","We deduced the answer from the facts."],
["anticipate","предвидеть, ожидать","v","We anticipate a rise in prices."],
["comprehend","понимать, постигать","v","I cannot comprehend his behaviour."],
["misunderstand","неправильно понимать","v","Do not misunderstand me."],
["overlook","упускать из виду","v","He overlooked an important detail."],
["speculate","строить догадки","v","It is useless to speculate about the result."],
// Уровень 2 — работа и карьера
["apply","подавать заявление; применять","v","I applied for the job last week."],
["applicant","соискатель, кандидат","n","We received fifty applicants for the position."],
["appointment","назначенная встреча, приём","n","I have an appointment at ten."],
["assignment","задание","n","The assignment is due on Monday."],
["candidate","кандидат","n","She is the best candidate for the job."],
["deadline","крайний срок","n","The deadline is Friday."],
["department","отдел","n","He works in the sales department."],
["employ","нанимать, использовать","v","The company employs two hundred people."],
["employee","сотрудник","n","Every employee gets a bonus."],
["employer","работодатель","n","My employer pays for my training."],
["employment","занятость, трудоустройство","n","Employment rates are rising."],
["promotion","повышение (по службе)","n","She got a promotion last month."],
["resign","уходить в отставку, увольняться","v","He resigned after the scandal."],
["retire","выходить на пенсию","v","My father retired at sixty."],
["recruit","набирать (персонал)","v","We are recruiting new engineers."],
["shift","смена; сдвиг","n","I work the night shift."],
["staff","персонал","n","The staff are very friendly."],
["supervisor","руководитель, начальник","n","Ask your supervisor first."],
["workload","рабочая нагрузка","n","My workload has doubled."],
["wage","заработная плата (почасовая)","n","The minimum wage went up."],
["unemployed","безработный","adj","He has been unemployed for a year."],
["qualification","квалификация","n","What qualifications do you need?"],
["requirement","требование","n","A degree is a requirement for this job."],
["responsibility","ответственность, обязанность","n","It is my responsibility to check the reports."],
["schedule","расписание, график","n","My schedule is full this week."],
["overtime","сверхурочная работа","n","I did a lot of overtime last month."],
["negotiate","вести переговоры","v","We negotiated a better salary."],
["quit","бросать, увольняться","v","She quit her job to travel."],
["freelance","внештатный, фриланс","adj","He works as a freelance designer."],
["internship","стажировка","n","I did an internship at a bank."],
["position","должность; положение","n","The position is still open."],
["vacancy","вакансия","n","There is a vacancy in our team."],
["workplace","рабочее место","n","Safety at the workplace is important."],
["achievement","достижение","n","Winning the contract was a great achievement."],
["ambition","амбиция, стремление","n","Her ambition is to run a company."],
["challenge","вызов, сложная задача","n","This project is a real challenge."],
["commute","ездить на работу","v","I commute by train every day."],
["cooperate","сотрудничать","v","The two teams cooperated well."],
["expertise","компетенция, опыт","n","We need your expertise."],
["feedback","обратная связь, отзыв","n","Give me some feedback on my work."],
["income","доход","n","Their income has grown."],
["labour","труд, рабочая сила","n","The labour market is changing."],
["dismiss","увольнять; отклонять","v","He was dismissed for being late."],
["reference","рекомендация; ссылка","n","Can you give me a reference?"],
["résumé","резюме","n","Send your résumé by email."],
["probation","испытательный срок","n","The first three months are probation."],
["colleague","коллега","n","I had lunch with a colleague."],
["appraisal","аттестация, оценка работы","n","My annual appraisal is next week."],
["temporary","временный","adj","It is a temporary job."],
["permanent","постоянный","adj","She got a permanent contract."],
// Уровень 3 — бизнес и финансы
["budget","бюджет","n","We have a limited budget."],
["invest","инвестировать","v","They invested in new equipment."],
["investment","инвестиция","n","It was a good investment."],
["profit","прибыль","n","The company made a profit this year."],
["loss","убыток, потеря","n","The firm reported a loss."],
["revenue","выручка, доход","n","Revenue grew by ten percent."],
["expense","расход","n","Travel expenses are paid by the company."],
["debt","долг","n","He is in debt."],
["loan","кредит, заём","n","I took out a loan to buy a car."],
["mortgage","ипотека","n","We pay the mortgage every month."],
["interest","процент (по кредиту); интерес","n","The interest rate is five percent."],
["tax","налог","n","Taxes went up this year."],
["insurance","страхование, страховка","n","Do you have car insurance?"],
["invoice","счёт-фактура","n","Please send the invoice by Friday."],
["purchase","покупка; покупать","n","Keep the receipt for your purchase."],
["supplier","поставщик","n","Our supplier delivers every Monday."],
["demand","спрос; требовать","n","Demand for housing is high."],
["supply","предложение, поставка","n","The supply of oil is limited."],
["competitor","конкурент","n","Our main competitor cut prices."],
["launch","запускать (продукт)","v","They launched a new phone."],
["agreement","соглашение","n","We reached an agreement."],
["deal","сделка","n","It was a good deal."],
["shareholder","акционер","n","Shareholders receive dividends."],
["share","акция; доля; делиться","n","I bought shares in the company."],
["economy","экономика","n","The economy is growing."],
["inflation","инфляция","n","Inflation is rising."],
["recession","спад, рецессия","n","The country is in recession."],
["growth","рост","n","Economic growth slowed down."],
["wealth","богатство","n","He built his wealth in real estate."],
["afford","позволить себе","v","We cannot afford a new car."],
["bargain","выгодная покупка; торговаться","n","This jacket was a bargain."],
["charge","взимать плату; плата","v","They charge ten dollars an hour."],
["fee","плата, гонорар","n","The lawyer charges a high fee."],
["fund","финансировать; фонд","v","The project is funded by the government."],
["refund","возврат денег","n","I asked for a refund."],
["deposit","депозит, залог, вклад","n","You pay a deposit when you book."],
["withdraw","снимать (деньги); отзывать","v","I withdrew cash from the ATM."],
["account","счёт (банковский); отчёт","n","Open a bank account."],
["balance","баланс, остаток","n","Check your account balance."],
["currency","валюта","n","What currency do they use?"],
["exchange rate","обменный курс","n","The exchange rate changed."],
["transaction","транзакция, операция","n","The transaction was declined."],
["bankrupt","банкрот","adj","The company went bankrupt."],
["turnover","оборот","n","Annual turnover is five million."],
["asset","актив","n","The building is our main asset."],
["liability","обязательство, ответственность","n","The firm has large liabilities."],
["stock","запас, товар на складе; акции","n","We have plenty of stock."],
["enterprise","предприятие","n","She runs a small enterprise."],
["merger","слияние","n","The merger created a giant company."],
["forecast","прогноз","n","The sales forecast looks good."],
// Уровень 4 — образование и наука
["academic","академический, учебный","adj","The academic year starts in September."],
["analyse","анализировать","v","We analysed the data carefully."],
["research","исследование","n","She does research on climate."],
["theory","теория","n","The theory was proved in 1905."],
["experiment","эксперимент","n","The experiment failed."],
["evidence","доказательство, свидетельство","n","There is no evidence of fraud."],
["hypothesis","гипотеза","n","The results support our hypothesis."],
["conclusion","вывод, заключение","n","What is your conclusion?"],
["data","данные","n","The data are stored on a server."],
["method","метод","n","This method is faster."],
["approach","подход","n","We need a new approach."],
["degree","учёная степень; градус","n","She has a degree in law."],
["graduate","выпускник; оканчивать","v","I graduated from university in 2015."],
["lecture","лекция","n","The lecture lasted two hours."],
["seminar","семинар","n","We discussed the topic at the seminar."],
["tutor","репетитор, наставник","n","My tutor helps me with maths."],
["curriculum","учебная программа","n","The curriculum includes coding."],
["scholarship","стипендия","n","She won a scholarship to Oxford."],
["thesis","диссертация, тезис","n","He is writing his thesis."],
["essay","эссе, сочинение","n","Write an essay about your city."],
["assessment","оценка, оценивание","n","The assessment is based on tests."],
["discipline","дисциплина","n","Discipline is important in learning."],
["subject","предмет, тема","n","My favourite subject is history."],
["term","семестр; срок; термин","n","The term ends in June."],
["laboratory","лаборатория","n","The samples are in the laboratory."],
["formula","формула","n","Learn the formula by heart."],
["calculate","вычислять","v","Calculate the total cost."],
["measure","измерять; мера","v","Measure the length of the table."],
["accurate","точный","adj","The figures are accurate."],
["precise","точный, чёткий","adj","Give me precise instructions."],
["prove","доказывать","v","Can you prove it?"],
["discover","обнаруживать, открывать","v","They discovered a new planet."],
["discovery","открытие","n","It was an important discovery."],
["invent","изобретать","v","Who invented the telephone?"],
["invention","изобретение","n","The wheel is a great invention."],
["innovation","инновация, нововведение","n","Innovation drives the economy."],
["technique","методика, техника","n","She learned a new technique."],
["principle","принцип","n","It is a basic principle of physics."],
["concept","понятие, концепция","n","The concept is hard to explain."],
["define","определять, давать определение","v","Define the term clearly."],
["definition","определение","n","Look up the definition."],
["category","категория","n","Which category does it belong to?"],
["literature","литература","n","She studies English literature."],
["phenomenon","явление","n","It is a rare phenomenon."],
["sample","образец, выборка","n","We tested a sample of the water."],
["variable","переменная","n","Temperature is an important variable."],
["outcome","результат, исход","n","The outcome was unexpected."],
["revise","повторять (перед экзаменом); пересматривать","v","I need to revise for the exam."],
["memorize","заучивать","v","Memorize these twenty words."],
["fluent","беглый (о речи)","adj","She is fluent in three languages."],
// Уровень 5 — технологии и интернет
["software","программное обеспечение","n","Install the latest software."],
["hardware","аппаратное обеспечение","n","The hardware is outdated."],
["update","обновление; обновлять","n","There is a new update available."],
["upgrade","улучшать, модернизировать","v","I upgraded my phone."],
["install","устанавливать","v","Install the app on your phone."],
["settings","настройки","n","Change it in the settings."],
["browser","браузер","n","Which browser do you use?"],
["search engine","поисковая система","n","Type your question into the search engine."],
["link","ссылка","n","Click the link to open the page."],
["attachment","вложение (в письме)","n","See the attachment for details."],
["spam","спам","n","The email went to the spam folder."],
["hack","взламывать","v","Someone hacked my account."],
["backup","резервная копия","n","Make a backup of your files."],
["storage","хранилище, память","n","My phone is out of storage."],
["cloud","облако (хранилище)","n","The photos are saved in the cloud."],
["server","сервер","n","The server is down."],
["database","база данных","n","The database contains a million records."],
["developer","разработчик","n","She works as a software developer."],
["bug","ошибка (в программе), баг","n","The app has a bug."],
["crash","сбой; падать (о программе)","v","My computer crashed again."],
["freeze","зависать; замерзать","v","The screen froze."],
["reboot","перезагружать","v","Reboot your computer."],
["wireless","беспроводной","adj","I use wireless headphones."],
["stream","транслировать, смотреть онлайн","v","We streamed the concert live."],
["subscribe","подписываться","v","Subscribe to our channel."],
["subscription","подписка","n","My subscription ends in May."],
["notification","уведомление","n","Turn off notifications at night."],
["privacy","конфиденциальность, частная жизнь","n","Read the privacy policy."],
["encrypt","шифровать","v","All messages are encrypted."],
["artificial intelligence","искусственный интеллект","n","Artificial intelligence is changing work."],
["algorithm","алгоритм","n","The algorithm sorts the data."],
["automate","автоматизировать","v","We automated the reports."],
["digital","цифровой","adj","We live in a digital world."],
["virtual","виртуальный","adj","It was a virtual meeting."],
["interface","интерфейс","n","The interface is easy to use."],
["feature","функция, особенность","n","The new feature saves time."],
["tool","инструмент","n","This is a useful tool."],
["gadget","гаджет","n","He loves new gadgets."],
["touchscreen","сенсорный экран","n","The touchscreen does not respond."],
["access","доступ; получать доступ","n","I do not have access to the file."],
["log in","входить (в систему)","v","Log in with your email."],
["username","имя пользователя","n","Enter your username."],
["default","по умолчанию","n","Keep the default settings."],
["bandwidth","пропускная способность","n","Video calls need more bandwidth."],
["troubleshoot","устранять неполадки","v","The engineer will troubleshoot the problem."],
["compatible","совместимый","adj","Is this app compatible with my phone?"],
["outdated","устаревший","adj","The software is outdated."],
["user-friendly","удобный для пользователя","adj","The app is very user-friendly."],
["glitch","сбой, неполадка","n","There was a glitch in the system."],
["firmware","прошивка","n","Update the firmware of the device."],
// Уровень 6 — общество и право
["government","правительство","n","The government announced new taxes."],
["election","выборы","n","The election is in May."],
["vote","голосовать; голос","v","Who did you vote for?"],
["campaign","кампания","n","The campaign starts next week."],
["policy","политика (курс), правила","n","The company has a strict policy."],
["politician","политик","n","The politician gave a speech."],
["parliament","парламент","n","Parliament passed the law."],
["legal","законный, юридический","adj","Is it legal to park here?"],
["illegal","незаконный","adj","It is illegal to drive without a licence."],
["citizen","гражданин","n","She became a citizen last year."],
["immigration","иммиграция","n","Immigration rules have changed."],
["refugee","беженец","n","The refugees needed shelter."],
["protest","протест; протестовать","n","There was a protest in the square."],
["democracy","демократия","n","Democracy depends on free elections."],
["justice","справедливость, правосудие","n","They demanded justice."],
["court","суд","n","The case went to court."],
["trial","судебный процесс; испытание","n","The trial lasted three weeks."],
["crime","преступление","n","Crime rates have fallen."],
["criminal","преступник; преступный","n","The criminal was caught."],
["punishment","наказание","n","The punishment was too severe."],
["prison","тюрьма","n","He spent five years in prison."],
["guilty","виновный","adj","The jury found him guilty."],
["innocent","невиновный, невинный","adj","She is innocent."],
["witness","свидетель","n","The witness saw everything."],
["victim","жертва","n","The victim was taken to hospital."],
["arrest","арестовывать","v","The police arrested two men."],
["fine","штраф; штрафовать","n","I got a fine for speeding."],
["welfare","благосостояние; соцобеспечение","n","The state provides welfare."],
["charity","благотворительность","n","She works for a charity."],
["volunteer","волонтёр; вызываться","n","Volunteers helped after the flood."],
["community","сообщество, община","n","The local community supported the plan."],
["population","население","n","The population is growing."],
["majority","большинство","n","The majority voted yes."],
["minority","меньшинство","n","A small minority disagreed."],
["equality","равенство","n","They fight for equality."],
["discrimination","дискриминация","n","Discrimination is illegal."],
["poverty","бедность","n","Many people live in poverty."],
["corruption","коррупция","n","Corruption is a serious problem."],
["authority","власть, орган власти","n","The local authority closed the road."],
["official","чиновник; официальный","n","An official signed the document."],
["regulation","правило, регулирование","n","New regulations came into force."],
["ban","запрещать; запрет","v","Smoking is banned in restaurants."],
["permit","разрешение; разрешать","n","You need a permit to work here."],
["lawsuit","судебный иск","n","They filed a lawsuit against the company."],
["sue","подавать в суд","v","She sued the hospital."],
["testify","давать показания","v","He testified in court."],
["jury","присяжные","n","The jury reached a verdict."],
["sentence","приговор; приговаривать","n","He received a ten-year sentence."],
["appeal","апелляция; обращаться","n","The lawyer filed an appeal."],
["bribe","взятка","n","The official took a bribe."],
// Уровень 7 — здоровье и медицина
["symptom","симптом","n","Fever is a common symptom."],
["diagnosis","диагноз","n","The diagnosis was correct."],
["treatment","лечение","n","The treatment lasts six weeks."],
["treat","лечить; обращаться","v","Doctors treated him for burns."],
["cure","лекарство; вылечивать","n","There is no cure for this disease."],
["recover","выздоравливать, восстанавливаться","v","She recovered quickly."],
["recovery","выздоровление","n","He made a full recovery."],
["injury","травма","n","He had a serious injury."],
["injured","травмированный","adj","Three people were injured."],
["wound","рана","n","The wound is healing."],
["bruise","синяк","n","She had a bruise on her arm."],
["allergy","аллергия","n","I have an allergy to nuts."],
["allergic","аллергический","adj","He is allergic to cats."],
["infection","инфекция","n","The infection spread quickly."],
["vaccine","вакцина","n","The vaccine is safe."],
["prescription","рецепт (врача)","n","You need a prescription for this medicine."],
["surgery","операция, хирургия","n","She had surgery on her knee."],
["surgeon","хирург","n","The surgeon operated for four hours."],
["patient","пациент","n","The patient is sleeping."],
["emergency","чрезвычайная ситуация","n","Call this number in an emergency."],
["ambulance","скорая помощь","n","The ambulance arrived in five minutes."],
["blood pressure","кровяное давление","n","His blood pressure is high."],
["stress","стресс","n","Stress affects your sleep."],
["anxiety","тревога, тревожность","n","She suffers from anxiety."],
["depression","депрессия","n","Depression is a serious illness."],
["mental","психический, умственный","adj","Mental health matters."],
["physical","физический","adj","Physical exercise is important."],
["diet","диета, рацион","n","A healthy diet includes vegetables."],
["nutrition","питание","n","Good nutrition helps children grow."],
["obesity","ожирение","n","Obesity is increasing."],
["overweight","с избыточным весом","adj","He is slightly overweight."],
["fitness","физическая форма","n","Running improves your fitness."],
["workout","тренировка","n","I do a workout every morning."],
["muscle","мышца","n","My muscles hurt after the gym."],
["bone","кость","n","He broke a bone in his hand."],
["joint","сустав","n","My joints ache in cold weather."],
["lung","лёгкое","n","Smoking damages the lungs."],
["liver","печень","n","Alcohol harms the liver."],
["kidney","почка","n","He needs a kidney transplant."],
["brain","мозг","n","The brain needs sleep."],
["nerve","нерв","n","The nerve was damaged."],
["immune","иммунный","adj","The immune system fights infection."],
["chronic","хронический","adj","She has chronic back pain."],
["severe","тяжёлый, серьёзный","adj","The injury was severe."],
["mild","лёгкий, слабый","adj","He has a mild cold."],
["painkiller","обезболивающее","n","Take a painkiller if it hurts."],
["dose","доза","n","Do not exceed the dose."],
["side effect","побочный эффект","n","The drug has side effects."],
["disease","болезнь","n","Heart disease is common."],
["therapy","терапия","n","Physical therapy helped him walk again."],
// Уровень 8 — окружающая среда
["environment","окружающая среда","n","We must protect the environment."],
["pollution","загрязнение","n","Air pollution is a big problem."],
["pollute","загрязнять","v","Factories pollute the river."],
["climate","климат","n","The climate is changing."],
["global warming","глобальное потепление","n","Global warming melts the ice."],
["carbon","углерод","n","Cars produce carbon dioxide."],
["emission","выброс","n","Emissions must be cut."],
["fossil fuel","ископаемое топливо","n","Coal is a fossil fuel."],
["renewable","возобновляемый","adj","Solar power is renewable."],
["solar","солнечный","adj","They installed solar panels."],
["recycle","перерабатывать","v","We recycle paper and glass."],
["waste","отходы; тратить впустую","n","Reduce food waste."],
["rubbish","мусор","n","Put the rubbish in the bin."],
["landfill","свалка","n","Most waste goes to landfill."],
["sustainable","экологически устойчивый","adj","We need sustainable energy."],
["species","вид (биологический)","n","Many species are disappearing."],
["extinct","вымерший","adj","Dinosaurs are extinct."],
["endangered","находящийся под угрозой","adj","Tigers are an endangered species."],
["habitat","среда обитания","n","Forests are the habitat of many animals."],
["wildlife","дикая природа","n","The park protects wildlife."],
["conservation","охрана природы","n","She works in wildlife conservation."],
["destroy","разрушать","v","The storm destroyed the bridge."],
["destruction","разрушение","n","The fire caused great destruction."],
["disaster","катастрофа, бедствие","n","The flood was a disaster."],
["flood","наводнение","n","The flood damaged many homes."],
["drought","засуха","n","The drought ruined the crops."],
["earthquake","землетрясение","n","The earthquake hit at night."],
["hurricane","ураган","n","The hurricane reached the coast."],
["wildfire","лесной пожар","n","Wildfires spread quickly in summer."],
["resource","ресурс","n","Water is a precious resource."],
["energy","энергия","n","Save energy at home."],
["consumption","потребление","n","Energy consumption is rising."],
["consume","потреблять","v","We consume too much plastic."],
["greenhouse","парниковый; теплица","n","Greenhouse gases warm the planet."],
["atmosphere","атмосфера","n","The atmosphere protects the Earth."],
["ecosystem","экосистема","n","The ecosystem is fragile."],
["biodiversity","биоразнообразие","n","Biodiversity is declining."],
["deforestation","вырубка лесов","n","Deforestation destroys habitats."],
["organic","органический","adj","We buy organic vegetables."],
["pesticide","пестицид","n","Pesticides harm bees."],
["harvest","урожай; собирать урожай","n","The harvest was poor this year."],
["crop","сельскохозяйственная культура","n","Wheat is the main crop here."],
["soil","почва","n","The soil is very dry."],
["agriculture","сельское хозяйство","n","Agriculture employs many people."],
["rural","сельский","adj","They live in a rural area."],
["urban","городской","adj","Urban areas are growing."],
["contaminate","заражать, загрязнять","v","The water was contaminated."],
["preserve","сохранять","v","We must preserve the forest."],
["shortage","нехватка","n","There is a water shortage."],
["ozone layer","озоновый слой","n","The ozone layer is recovering."],
// Уровень 9 — характер и отношения
["ambitious","амбициозный","adj","She is very ambitious."],
["arrogant","высокомерный","adj","He is arrogant and rude."],
["cautious","осторожный","adj","Be cautious with strangers."],
["cheerful","жизнерадостный","adj","She is always cheerful."],
["considerate","внимательный к другим","adj","He is a considerate neighbour."],
["curious","любопытный","adj","Children are naturally curious."],
["determined","решительный, целеустремлённый","adj","She is determined to win."],
["easygoing","спокойный, покладистый","adj","My boss is easygoing."],
["gentle","мягкий, нежный","adj","He is gentle with animals."],
["impatient","нетерпеливый","adj","Do not be so impatient."],
["independent","независимый","adj","She is an independent woman."],
["insecure","неуверенный в себе","adj","He feels insecure about his English."],
["loyal","верный, преданный","adj","A dog is a loyal friend."],
["mature","зрелый","adj","He is very mature for his age."],
["modest","скромный","adj","She is modest about her success."],
["moody","с переменчивым настроением","adj","Teenagers can be moody."],
["optimistic","оптимистичный","adj","I am optimistic about the future."],
["pessimistic","пессимистичный","adj","Do not be so pessimistic."],
["outgoing","общительный","adj","She is outgoing and friendly."],
["reliable","надёжный","adj","He is a reliable worker."],
["reserved","сдержанный","adj","He is reserved with strangers."],
["responsible","ответственный","adj","She is responsible for the budget."],
["sensible","разумный","adj","That is a sensible decision."],
["sensitive","чувствительный","adj","He is sensitive to criticism."],
["sociable","общительный","adj","She is sociable and likes parties."],
["stubborn","упрямый","adj","He is too stubborn to apologize."],
["sympathetic","сочувствующий","adj","She was very sympathetic."],
["talkative","разговорчивый","adj","My aunt is very talkative."],
["thoughtful","заботливый, вдумчивый","adj","What a thoughtful gift!"],
["tolerant","терпимый","adj","Be tolerant of other opinions."],
["witty","остроумный","adj","He is a witty speaker."],
["relationship","отношения","n","They have a good relationship."],
["acquaintance","знакомый","n","He is an acquaintance, not a friend."],
["partner","партнёр","n","She lives with her partner."],
["apologize","извиняться","v","I apologize for the delay."],
["forgive","прощать","v","I will never forgive him."],
["admire","восхищаться","v","I admire her courage."],
["respect","уважать; уважение","v","Respect your elders."],
["envy","завидовать; зависть","v","I envy your patience."],
["jealous","ревнивый, завистливый","adj","He is jealous of his brother."],
["grateful","благодарный","adj","I am grateful for your help."],
["embarrassed","смущённый","adj","I was embarrassed by the mistake."],
["ashamed","пристыженный","adj","He was ashamed of his behaviour."],
["relieved","почувствовавший облегчение","adj","I was relieved to hear the news."],
["frustrated","разочарованный, раздражённый","adj","I feel frustrated with the delays."],
["anxious","тревожный, обеспокоенный","adj","She is anxious about the exam."],
["confident","уверенный","adj","He is confident in his skills."],
["generous","щедрый","adj","He is generous with his time."],
["honest","честный","adj","Give me an honest answer."],
["selfish","эгоистичный","adj","Do not be selfish."],
// Уровень 10 — общение и аргументация
["persuade","убеждать, уговаривать","v","She persuaded me to join."],
["debate","дебаты; обсуждать","n","The debate lasted two hours."],
["interrupt","перебивать","v","Do not interrupt me."],
["mention","упоминать","v","He mentioned your name."],
["express","выражать","v","She expressed her opinion."],
["hint","намёк; намекать","n","Give me a hint."],
["exaggerate","преувеличивать","v","Do not exaggerate the problem."],
["confess","признаваться","v","He confessed to the crime."],
["whisper","шептать","v","She whispered the answer."],
["mutter","бормотать","v","He muttered something and left."],
["gossip","сплетни; сплетничать","n","I do not listen to gossip."],
["rumour","слух","n","There is a rumour about the merger."],
["compliment","комплимент","n","She paid me a compliment."],
["criticize","критиковать","v","He criticized the plan."],
["criticism","критика","n","She accepts criticism well."],
["praise","хвалить; похвала","v","The teacher praised his work."],
["blame","винить; вина","v","Do not blame me."],
["accuse","обвинять","v","They accused him of theft."],
["excuse","оправдание; извинять","n","That is no excuse."],
["threaten","угрожать","v","He threatened to leave."],
["warn","предупреждать","v","I warned you about the risk."],
["announce","объявлять","v","They announced the results."],
["declare","заявлять, объявлять","v","He declared his support."],
["statement","заявление","n","The company issued a statement."],
["remark","замечание; замечать","n","He made a rude remark."],
["comment","комментарий; комментировать","n","She made a helpful comment."],
["respond","отвечать, реагировать","v","He did not respond to my email."],
["response","ответ, реакция","n","We got a quick response."],
["request","просьба, запрос","n","I have a small request."],
["recommend","рекомендовать","v","I recommend this book."],
["advise","советовать","v","I advise you to wait."],
["advice","совет","n","Thanks for the advice."],
["attitude","отношение, позиция","n","He has a positive attitude."],
["point of view","точка зрения","n","From my point of view, it is fair."],
["argument","спор; аргумент","n","They had an argument about money."],
["disagree","не соглашаться","v","I disagree with you."],
["clarify","прояснять","v","Can you clarify this point?"],
["summarize","подводить итог","v","Summarize the article in three sentences."],
["assure","уверять","v","I assure you it is safe."],
["object","возражать; объект","v","Nobody objected to the plan."],
["convey","передавать (мысль)","v","Words cannot convey my feelings."],
["persuasive","убедительный","adj","He gave a persuasive speech."],
["contradict","противоречить","v","The facts contradict his story."],
["consult","консультироваться","v","Consult a doctor before taking it."],
["deliberate","намеренный","adj","It was a deliberate mistake."],
["misleading","вводящий в заблуждение","adj","The advert is misleading."],
["flattery","лесть","n","Flattery will get you nowhere."],
["sarcasm","сарказм","n","I could hear the sarcasm in his voice."],
["negotiation","переговоры","n","The negotiations failed."],
["consensus","консенсус, единое мнение","n","We reached a consensus."],
];
