// Дополнительный словарь: 482 слов прежнего курса вне Oxford 3000 (слово и часть речи).
// Файл собирается tools/build-extra-words.js из words-a.js, words-b.js, ex-ru.js; вручную не править.
// Формат записи: [слово, перевод, часть речи, пример, перевод примера]
const WORDS_EXTRA = {level:"extra", blocks:[
{id:"x-01", title:"Мнение и мышление", words:[
["perceive","воспринимать","v","The plan was perceived as risky.","План восприняли как рискованный."],
["underestimate","недооценивать","v","Never underestimate your opponent.","Никогда не недооценивай соперника."],
["presume","предполагать, полагать","v","I presume the meeting is cancelled.","Полагаю, встреча отменена."],
["conceive","представлять себе, задумывать","v","I cannot conceive of life without music.","Не могу представить жизнь без музыки."],
["reckon","считать, полагать (разг.)","v","I reckon it will rain.","Думаю, будет дождь."],
["ponder","обдумывать","v","She pondered the question for a while.","Она некоторое время обдумывала вопрос."],
["contemplate","обдумывать, созерцать","v","He is contemplating a career change.","Он подумывает о смене карьеры."],
["deduce","делать вывод","v","We deduced the answer from the facts.","Мы вывели ответ из фактов."],
["anticipate","предвидеть, ожидать","v","We anticipate a rise in prices.","Мы ожидаем роста цен."],
["comprehend","понимать, постигать","v","I cannot comprehend his behaviour.","Не могу понять его поведение."],
["misunderstand","неправильно понимать","v","Do not misunderstand me.","Не пойми меня неправильно."],
["overlook","упускать из виду","v","He overlooked an important detail.","Он упустил важную деталь."],
["speculate","строить догадки","v","It is useless to speculate about the result.","Бесполезно строить догадки о результате."]
]},
{id:"x-02", title:"Работа и карьера", words:[
["applicant","соискатель, кандидат","n","We received fifty applicants for the position.","На эту должность мы получили пятьдесят кандидатов."],
["deadline","крайний срок","n","The deadline is Friday.","Крайний срок — пятница."],
["promotion","повышение (по службе)","n","She got a promotion last month.","В прошлом месяце она получила повышение."],
["resign","уходить в отставку, увольняться","v","He resigned after the scandal.","После скандала он ушёл в отставку."],
["recruit","набирать (персонал)","v","We are recruiting new engineers.","Мы набираем новых инженеров."],
["supervisor","руководитель, начальник","n","Ask your supervisor first.","Сначала спроси у своего руководителя."],
["workload","рабочая нагрузка","n","My workload has doubled.","Моя нагрузка удвоилась."],
["overtime","сверхурочная работа","n","I did a lot of overtime last month.","В прошлом месяце я много работал сверхурочно."],
["negotiate","вести переговоры","v","We negotiated a better salary.","Мы договорились о более высокой зарплате."],
["freelance","внештатный, фриланс","adj","He works as a freelance designer.","Он работает дизайнером на фрилансе."],
["internship","стажировка","n","I did an internship at a bank.","Я проходил стажировку в банке."],
["vacancy","вакансия","n","There is a vacancy in our team.","В нашей команде есть вакансия."],
["workplace","рабочее место","n","Safety at the workplace is important.","Безопасность на рабочем месте важна."],
["commute","ездить на работу","v","I commute by train every day.","Я каждый день езжу на работу на поезде."],
["cooperate","сотрудничать","v","The two teams cooperated well.","Две команды хорошо сотрудничали."],
["expertise","компетенция, опыт","n","We need your expertise.","Нам нужна твоя компетенция."],
["résumé","резюме","n","Send your résumé by email.","Пришлите резюме по электронной почте."],
["probation","испытательный срок","n","The first three months are probation.","Первые три месяца — испытательный срок."],
["appraisal","аттестация, оценка работы","n","My annual appraisal is next week.","Моя годовая аттестация на следующей неделе."]
]},
{id:"x-03", title:"Бизнес и финансы", words:[
["revenue","выручка, доход","n","Revenue grew by ten percent.","Выручка выросла на десять процентов."],
["mortgage","ипотека","n","We pay the mortgage every month.","Мы платим ипотеку каждый месяц."],
["invoice","счёт-фактура","n","Please send the invoice by Friday.","Пожалуйста, пришлите счёт до пятницы."],
["supplier","поставщик","n","Our supplier delivers every Monday.","Наш поставщик доставляет каждый понедельник."],
["shareholder","акционер","n","Shareholders receive dividends.","Акционеры получают дивиденды."],
["inflation","инфляция","n","Inflation is rising.","Инфляция растёт."],
["recession","спад, рецессия","n","The country is in recession.","Страна в рецессии."],
["bargain","выгодная покупка; торговаться","n","This jacket was a bargain.","Эта куртка была выгодной покупкой."],
["refund","возврат денег","n","I asked for a refund.","Я попросил вернуть деньги."],
["deposit","депозит, залог, вклад","n","You pay a deposit when you book.","При бронировании вносится залог."],
["withdraw","снимать (деньги); отзывать","v","I withdrew cash from the ATM.","Я снял наличные в банкомате."],
["exchange rate","обменный курс","n","The exchange rate changed.","Обменный курс изменился."],
["transaction","транзакция, операция","n","The transaction was declined.","Операция отклонена."],
["bankrupt","банкрот","adj","The company went bankrupt.","Компания обанкротилась."],
["turnover","оборот","n","Annual turnover is five million.","Годовой оборот — пять миллионов."],
["asset","актив","n","The building is our main asset.","Здание — наш главный актив."],
["liability","обязательство, ответственность","n","The firm has large liabilities.","У фирмы большие обязательства."],
["enterprise","предприятие","n","She runs a small enterprise.","Она руководит небольшим предприятием."],
["merger","слияние","n","The merger created a giant company.","Слияние создало компанию-гиганта."],
["forecast","прогноз","n","The sales forecast looks good.","Прогноз продаж выглядит хорошо."]
]},
{id:"x-04", title:"Образование и наука", words:[
["hypothesis","гипотеза","n","The results support our hypothesis.","Результаты подтверждают нашу гипотезу."],
["seminar","семинар","n","We discussed the topic at the seminar.","Мы обсудили тему на семинаре."],
["tutor","репетитор, наставник","n","My tutor helps me with maths.","Мой репетитор помогает мне с математикой."],
["curriculum","учебная программа","n","The curriculum includes coding.","В программу входит программирование."],
["scholarship","стипендия","n","She won a scholarship to Oxford.","Она получила стипендию в Оксфорд."],
["thesis","диссертация, тезис","n","He is writing his thesis.","Он пишет диссертацию."],
["formula","формула","n","Learn the formula by heart.","Выучи формулу наизусть."],
["precise","точный, чёткий","adj","Give me precise instructions.","Дай мне точные инструкции."],
["innovation","инновация, нововведение","n","Innovation drives the economy.","Инновации двигают экономику."],
["variable","переменная","n","Temperature is an important variable.","Температура — важная переменная."],
["memorize","заучивать","v","Memorize these twenty words.","Заучи эти двадцать слов."],
["fluent","беглый (о речи)","adj","She is fluent in three languages.","Она свободно говорит на трёх языках."]
]},
{id:"x-05", title:"Технологии", words:[
["hardware","аппаратное обеспечение","n","The hardware is outdated.","Оборудование устарело."],
["upgrade","улучшать, модернизировать","v","I upgraded my phone.","Я обновил телефон на новый."],
["settings","настройки","n","Change it in the settings.","Измени это в настройках."],
["browser","браузер","n","Which browser do you use?","Каким браузером ты пользуешься?"],
["search engine","поисковая система","n","Type your question into the search engine.","Введи вопрос в поисковую систему."],
["attachment","вложение (в письме)","n","See the attachment for details.","Подробности во вложении."],
["spam","спам","n","The email went to the spam folder.","Письмо попало в папку «Спам»."],
["hack","взламывать","v","Someone hacked my account.","Кто-то взломал мой аккаунт."],
["backup","резервная копия","n","Make a backup of your files.","Сделай резервную копию файлов."],
["storage","хранилище, память","n","My phone is out of storage.","В моём телефоне закончилась память."],
["server","сервер","n","The server is down.","Сервер не работает."],
["database","база данных","n","The database contains a million records.","База данных содержит миллион записей."],
["developer","разработчик","n","She works as a software developer.","Она работает разработчиком программ."],
["bug","ошибка (в программе), баг","n","The app has a bug.","В приложении есть ошибка."],
["reboot","перезагружать","v","Reboot your computer.","Перезагрузи компьютер."],
["wireless","беспроводной","adj","I use wireless headphones.","Я пользуюсь беспроводными наушниками."],
["stream","транслировать, смотреть онлайн","v","We streamed the concert live.","Мы транслировали концерт в прямом эфире."],
["subscribe","подписываться","v","Subscribe to our channel.","Подпишись на наш канал."],
["subscription","подписка","n","My subscription ends in May.","Моя подписка заканчивается в мае."],
["notification","уведомление","n","Turn off notifications at night.","Отключай уведомления на ночь."],
["encrypt","шифровать","v","All messages are encrypted.","Все сообщения зашифрованы."],
["artificial intelligence","искусственный интеллект","n","Artificial intelligence is changing work.","Искусственный интеллект меняет работу."],
["algorithm","алгоритм","n","The algorithm sorts the data.","Алгоритм сортирует данные."],
["automate","автоматизировать","v","We automated the reports.","Мы автоматизировали отчёты."],
["interface","интерфейс","n","The interface is easy to use.","Интерфейс простой в использовании."],
["gadget","гаджет","n","He loves new gadgets.","Он обожает новые гаджеты."],
["touchscreen","сенсорный экран","n","The touchscreen does not respond.","Сенсорный экран не реагирует."],
["log in","входить (в систему)","v","Log in with your email.","Войди с помощью электронной почты."],
["username","имя пользователя","n","Enter your username.","Введи имя пользователя."],
["default","по умолчанию","n","Keep the default settings.","Оставь настройки по умолчанию."],
["bandwidth","пропускная способность","n","Video calls need more bandwidth.","Видеозвонкам нужна большая пропускная способность."],
["troubleshoot","устранять неполадки","v","The engineer will troubleshoot the problem.","Инженер найдёт и устранит неполадку."],
["compatible","совместимый","adj","Is this app compatible with my phone?","Это приложение совместимо с моим телефоном?"],
["outdated","устаревший","adj","The software is outdated.","Программа устарела."],
["user-friendly","удобный для пользователя","adj","The app is very user-friendly.","Приложение очень удобное."],
["glitch","сбой, неполадка","n","There was a glitch in the system.","В системе произошёл сбой."],
["firmware","прошивка","n","Update the firmware of the device.","Обнови прошивку устройства."]
]},
{id:"x-06", title:"Общество и право", words:[
["immigration","иммиграция","n","Immigration rules have changed.","Правила иммиграции изменились."],
["refugee","беженец","n","The refugees needed shelter.","Беженцам нужно было укрытие."],
["democracy","демократия","n","Democracy depends on free elections.","Демократия зависит от свободных выборов."],
["fine","штраф; штрафовать","n","I got a fine for speeding.","Я получил штраф за превышение скорости."],
["welfare","благосостояние; соцобеспечение","n","The state provides welfare.","Государство обеспечивает соцподдержку."],
["equality","равенство","n","They fight for equality.","Они борются за равенство."],
["discrimination","дискриминация","n","Discrimination is illegal.","Дискриминация незаконна."],
["corruption","коррупция","n","Corruption is a serious problem.","Коррупция — серьёзная проблема."],
["lawsuit","судебный иск","n","They filed a lawsuit against the company.","Они подали иск против компании."],
["sue","подавать в суд","v","She sued the hospital.","Она подала в суд на больницу."],
["testify","давать показания","v","He testified in court.","Он дал показания в суде."],
["jury","присяжные","n","The jury reached a verdict.","Присяжные вынесли вердикт."],
["bribe","взятка","n","The official took a bribe.","Чиновник взял взятку."]
]},
{id:"x-07", title:"Здоровье и медицина", words:[
["diagnosis","диагноз","n","The diagnosis was correct.","Диагноз оказался верным."],
["recovery","выздоровление","n","He made a full recovery.","Он полностью выздоровел."],
["bruise","синяк","n","She had a bruise on her arm.","У неё был синяк на руке."],
["allergy","аллергия","n","I have an allergy to nuts.","У меня аллергия на орехи."],
["allergic","аллергический","adj","He is allergic to cats.","У него аллергия на кошек."],
["vaccine","вакцина","n","The vaccine is safe.","Вакцина безопасна."],
["prescription","рецепт (врача)","n","You need a prescription for this medicine.","На это лекарство нужен рецепт."],
["surgeon","хирург","n","The surgeon operated for four hours.","Хирург оперировал четыре часа."],
["ambulance","скорая помощь","n","The ambulance arrived in five minutes.","Скорая приехала через пять минут."],
["blood pressure","кровяное давление","n","His blood pressure is high.","У него высокое давление."],
["anxiety","тревога, тревожность","n","She suffers from anxiety.","Она страдает от тревожности."],
["depression","депрессия","n","Depression is a serious illness.","Депрессия — серьёзная болезнь."],
["nutrition","питание","n","Good nutrition helps children grow.","Хорошее питание помогает детям расти."],
["obesity","ожирение","n","Obesity is increasing.","Ожирение растёт."],
["overweight","с избыточным весом","adj","He is slightly overweight.","У него небольшой лишний вес."],
["workout","тренировка","n","I do a workout every morning.","Я тренируюсь каждое утро."],
["joint","сустав","n","My joints ache in cold weather.","В холод у меня ноют суставы."],
["liver","печень","n","Alcohol harms the liver.","Алкоголь вредит печени."],
["kidney","почка","n","He needs a kidney transplant.","Ему нужна пересадка почки."],
["immune","иммунный","adj","The immune system fights infection.","Иммунная система борется с инфекцией."],
["chronic","хронический","adj","She has chronic back pain.","У неё хроническая боль в спине."],
["painkiller","обезболивающее","n","Take a painkiller if it hurts.","Если болит, прими обезболивающее."],
["dose","доза","n","Do not exceed the dose.","Не превышай дозу."],
["side effect","побочный эффект","n","The drug has side effects.","У лекарства есть побочные эффекты."]
]},
{id:"x-08", title:"Окружающая среда", words:[
["pollute","загрязнять","v","Factories pollute the river.","Заводы загрязняют реку."],
["global warming","глобальное потепление","n","Global warming melts the ice.","Глобальное потепление растапливает лёд."],
["carbon","углерод","n","Cars produce carbon dioxide.","Машины выделяют углекислый газ."],
["emission","выброс","n","Emissions must be cut.","Выбросы нужно сократить."],
["fossil fuel","ископаемое топливо","n","Coal is a fossil fuel.","Уголь — ископаемое топливо."],
["renewable","возобновляемый","adj","Solar power is renewable.","Солнечная энергия возобновляема."],
["landfill","свалка","n","Most waste goes to landfill.","Большинство отходов идёт на свалку."],
["sustainable","экологически устойчивый","adj","We need sustainable energy.","Нам нужна экологичная энергия."],
["extinct","вымерший","adj","Dinosaurs are extinct.","Динозавры вымерли."],
["endangered","находящийся под угрозой","adj","Tigers are an endangered species.","Тигры — вид под угрозой исчезновения."],
["habitat","среда обитания","n","Forests are the habitat of many animals.","Леса — среда обитания многих животных."],
["conservation","охрана природы","n","She works in wildlife conservation.","Она работает в охране дикой природы."],
["destruction","разрушение","n","The fire caused great destruction.","Пожар причинил большие разрушения."],
["drought","засуха","n","The drought ruined the crops.","Засуха погубила урожай."],
["wildfire","лесной пожар","n","Wildfires spread quickly in summer.","Летом лесные пожары распространяются быстро."],
["consumption","потребление","n","Energy consumption is rising.","Потребление энергии растёт."],
["greenhouse","парниковый; теплица","n","Greenhouse gases warm the planet.","Парниковые газы нагревают планету."],
["ecosystem","экосистема","n","The ecosystem is fragile.","Экосистема хрупкая."],
["biodiversity","биоразнообразие","n","Biodiversity is declining.","Биоразнообразие сокращается."],
["deforestation","вырубка лесов","n","Deforestation destroys habitats.","Вырубка лесов уничтожает места обитания."],
["organic","органический","adj","We buy organic vegetables.","Мы покупаем органические овощи."],
["pesticide","пестицид","n","Pesticides harm bees.","Пестициды вредят пчёлам."],
["harvest","урожай; собирать урожай","n","The harvest was poor this year.","В этом году урожай был плохой."],
["agriculture","сельское хозяйство","n","Agriculture employs many people.","В сельском хозяйстве занято много людей."],
["contaminate","заражать, загрязнять","v","The water was contaminated.","Вода была заражена."],
["shortage","нехватка","n","There is a water shortage.","Не хватает воды."],
["ozone layer","озоновый слой","n","The ozone layer is recovering.","Озоновый слой восстанавливается."]
]},
{id:"x-09", title:"Характер и отношения", words:[
["arrogant","высокомерный","adj","He is arrogant and rude.","Он высокомерный и грубый."],
["cautious","осторожный","adj","Be cautious with strangers.","Будь осторожен с незнакомцами."],
["considerate","внимательный к другим","adj","He is a considerate neighbour.","Он внимательный сосед."],
["curious","любопытный","adj","Children are naturally curious.","Дети от природы любопытны."],
["easygoing","спокойный, покладистый","adj","My boss is easygoing.","Мой начальник — спокойный человек."],
["insecure","неуверенный в себе","adj","He feels insecure about his English.","Он не уверен в своём английском."],
["loyal","верный, преданный","adj","A dog is a loyal friend.","Собака — верный друг."],
["mature","зрелый","adj","He is very mature for his age.","Он очень зрел для своего возраста."],
["modest","скромный","adj","She is modest about her success.","Она скромно говорит о своём успехе."],
["moody","с переменчивым настроением","adj","Teenagers can be moody.","Подростки бывают с переменчивым настроением."],
["optimistic","оптимистичный","adj","I am optimistic about the future.","Я с оптимизмом смотрю в будущее."],
["pessimistic","пессимистичный","adj","Do not be so pessimistic.","Не будь таким пессимистом."],
["outgoing","общительный","adj","She is outgoing and friendly.","Она общительная и дружелюбная."],
["reserved","сдержанный","adj","He is reserved with strangers.","С незнакомыми он сдержан."],
["sociable","общительный","adj","She is sociable and likes parties.","Она общительная и любит вечеринки."],
["stubborn","упрямый","adj","He is too stubborn to apologize.","Он слишком упрям, чтобы извиниться."],
["sympathetic","сочувствующий","adj","She was very sympathetic.","Она очень сочувствовала."],
["talkative","разговорчивый","adj","My aunt is very talkative.","Моя тётя очень разговорчивая."],
["thoughtful","заботливый, вдумчивый","adj","What a thoughtful gift!","Какой заботливый подарок!"],
["tolerant","терпимый","adj","Be tolerant of other opinions.","Будь терпим к чужому мнению."],
["witty","остроумный","adj","He is a witty speaker.","Он остроумный оратор."],
["acquaintance","знакомый","n","He is an acquaintance, not a friend.","Он знакомый, а не друг."],
["envy","завидовать; зависть","v","I envy your patience.","Завидую твоему терпению."],
["jealous","ревнивый, завистливый","adj","He is jealous of his brother.","Он ревнует к брату."],
["relieved","почувствовавший облегчение","adj","I was relieved to hear the news.","Я с облегчением услышал новость."],
["frustrated","разочарованный, раздражённый","adj","I feel frustrated with the delays.","Задержки меня выводят из себя."],
["selfish","эгоистичный","adj","Do not be selfish.","Не будь эгоистом."]
]},
{id:"x-10", title:"Общение и аргументация", words:[
["hint","намёк; намекать","n","Give me a hint.","Дай мне подсказку."],
["exaggerate","преувеличивать","v","Do not exaggerate the problem.","Не преувеличивай проблему."],
["confess","признаваться","v","He confessed to the crime.","Он признался в преступлении."],
["mutter","бормотать","v","He muttered something and left.","Он что-то пробормотал и ушёл."],
["gossip","сплетни; сплетничать","n","I do not listen to gossip.","Я не слушаю сплетни."],
["rumour","слух","n","There is a rumour about the merger.","Ходит слух о слиянии."],
["compliment","комплимент","n","She paid me a compliment.","Она сделала мне комплимент."],
["point of view","точка зрения","n","From my point of view, it is fair.","С моей точки зрения, это справедливо."],
["clarify","прояснять","v","Can you clarify this point?","Можешь прояснить этот момент?"],
["assure","уверять","v","I assure you it is safe.","Уверяю тебя, это безопасно."],
["convey","передавать (мысль)","v","Words cannot convey my feelings.","Словами не передать мои чувства."],
["persuasive","убедительный","adj","He gave a persuasive speech.","Он произнёс убедительную речь."],
["contradict","противоречить","v","The facts contradict his story.","Факты противоречат его рассказу."],
["consult","консультироваться","v","Consult a doctor before taking it.","Перед приёмом проконсультируйся с врачом."],
["misleading","вводящий в заблуждение","adj","The advert is misleading.","Реклама вводит в заблуждение."],
["flattery","лесть","n","Flattery will get you nowhere.","Лесть тебе не поможет."],
["sarcasm","сарказм","n","I could hear the sarcasm in his voice.","Я слышал сарказм в его голосе."],
["negotiation","переговоры","n","The negotiations failed.","Переговоры провалились."],
["consensus","консенсус, единое мнение","n","We reached a consensus.","Мы пришли к единому мнению."]
]},
{id:"x-11", title:"Путешествия и транспорт", words:[
["itinerary","маршрут, план поездки","n","Our itinerary includes three cities.","Наш маршрут включает три города."],
["boarding pass","посадочный талон","n","Show your boarding pass at the gate.","Покажи посадочный талон у выхода."],
["aisle","проход (между рядами)","n","I prefer an aisle seat.","Я предпочитаю место у прохода."],
["customs","таможня","n","We waited an hour at customs.","Мы час ждали на таможне."],
["embassy","посольство","n","Contact the embassy if you lose your passport.","Если потеряешь паспорт, обратись в посольство."],
["sightseeing","осмотр достопримечательностей","n","We went sightseeing in Rome.","Мы осматривали достопримечательности Рима."],
["landmark","достопримечательность, ориентир","n","The tower is a famous landmark.","Башня — известная достопримечательность."],
["souvenir","сувенир","n","I bought a souvenir for my mother.","Я купил сувенир для мамы."],
["cruise","круиз","n","They went on a cruise.","Они отправились в круиз."],
["ferry","паром","n","The ferry crosses the river every hour.","Паром пересекает реку каждый час."],
["motorway","автомагистраль","n","Take the motorway to save time.","Чтобы сэкономить время, езжай по автомагистрали."],
["lane","полоса (дороги); переулок","n","Stay in the left lane.","Держись левой полосы."],
["junction","перекрёсток, развязка","n","Turn right at the next junction.","На следующем перекрёстке поверни направо."],
["roundabout","круговой перекрёсток","n","Take the second exit at the roundabout.","На кольце — второй съезд."],
["detour","объезд","n","We had to make a detour.","Нам пришлось сделать объезд."],
["traffic jam","пробка","n","We were stuck in a traffic jam.","Мы застряли в пробке."],
["rush hour","час пик","n","Avoid driving in rush hour.","Избегай поездок в час пик."],
["fare","плата за проезд","n","The bus fare is two dollars.","Проезд на автобусе стоит два доллара."],
["breakdown","поломка","n","We had a breakdown on the motorway.","У нас была поломка на трассе."],
["puncture","прокол (шины)","n","I got a puncture on the way home.","По дороге домой я проколол колесо."],
["brake","тормоз; тормозить","n","The brakes do not work.","Тормоза не работают."],
["overtake","обгонять","v","Do not overtake on a bend.","Не обгоняй на повороте."],
["speed limit","ограничение скорости","n","The speed limit here is fifty.","Ограничение скорости здесь — пятьдесят."],
["pedestrian","пешеход","n","Pedestrians must use the crossing.","Пешеходы должны пользоваться переходом."],
["crossing","переход, переезд","n","Wait at the crossing.","Подожди у перехода."],
["timetable","расписание","n","Check the train timetable.","Посмотри расписание поездов."],
["seat belt","ремень безопасности","n","Fasten your seat belt.","Пристегни ремень безопасности."],
["turbulence","турбулентность","n","We hit some turbulence over the ocean.","Над океаном мы попали в турбулентность."],
["jet lag","джетлаг","n","I had terrible jet lag after the flight.","После перелёта у меня был ужасный джетлаг."],
["layover","пересадка (в аэропорту)","n","We had a two-hour layover in Dubai.","У нас была двухчасовая пересадка в Дубае."],
["backpacker","путешественник с рюкзаком","n","The hostel is full of backpackers.","Хостел полон туристов с рюкзаками."],
["excursion","экскурсия","n","We took an excursion to the island.","Мы съездили на экскурсию на остров."],
["voyage","морское путешествие","n","The voyage lasted two weeks.","Плавание длилось две недели."],
["scenery","пейзаж","n","The scenery in the mountains is amazing.","Пейзажи в горах потрясающие."],
["picturesque","живописный","adj","It is a picturesque old town.","Это живописный старый город."],
["vibrant","яркий, оживлённый","adj","The city has a vibrant nightlife.","В городе яркая ночная жизнь."]
]},
{id:"x-12", title:"Дом и быт", words:[
["landlord","арендодатель","n","The landlord raised the rent.","Арендодатель поднял плату."],
["tenant","арендатор, жилец","n","The tenant pays on the first of the month.","Жилец платит первого числа каждого месяца."],
["lease","договор аренды","n","We signed a one-year lease.","Мы подписали договор аренды на год."],
["suburb","пригород","n","They moved to the suburbs.","Они переехали в пригород."],
["estate agent","агент по недвижимости","n","The estate agent showed us the flat.","Агент по недвижимости показал нам квартиру."],
["furnish","обставлять мебелью","v","The flat is fully furnished.","Квартира полностью обставлена мебелью."],
["appliance","бытовой прибор","n","The kitchen has modern appliances.","На кухне современная техника."],
["utilities","коммунальные услуги","n","Utilities are included in the rent.","Коммунальные услуги включены в аренду."],
["plumber","сантехник","n","Call a plumber about the leak.","Вызови сантехника из-за протечки."],
["electrician","электрик","n","The electrician fixed the wiring.","Электрик починил проводку."],
["leak","протечка; протекать","n","There is a leak under the sink.","Под раковиной протечка."],
["maintenance","обслуживание, содержание","n","The lift is closed for maintenance.","Лифт закрыт на обслуживание."],
["renovate","реконструировать","v","They renovated the old house.","Они реконструировали старый дом."],
["basement","подвал","n","The washing machine is in the basement.","Стиральная машина в подвале."],
["attic","чердак","n","Old boxes are in the attic.","Старые коробки на чердаке."],
["lawn","газон","n","He mows the lawn every Saturday.","Он стрижёт газон каждую субботу."],
["chore","работа по дому","n","Washing up is my least favourite chore.","Мытьё посуды — моя самая нелюбимая домашняя работа."],
["laundry","стирка, бельё","n","I do the laundry on Sundays.","Я стираю по воскресеньям."],
["vacuum","пылесосить; пылесос","v","Vacuum the carpet, please.","Пропылесось ковёр, пожалуйста."],
["clutter","хлам, беспорядок","n","There is too much clutter on the desk.","На столе слишком много хлама."],
["drawer","выдвижной ящик","n","The keys are in the top drawer.","Ключи в верхнем ящике."],
["blanket","одеяло","n","Bring me a blanket.","Принеси мне одеяло."],
["pillow","подушка","n","This pillow is too soft.","Эта подушка слишком мягкая."],
["mattress","матрас","n","We bought a new mattress.","Мы купили новый матрас."],
["tap","кран","n","The tap is dripping.","Кран капает."],
["sink","раковина","n","The dishes are in the sink.","Посуда в раковине."],
["microwave","микроволновка","n","Heat it in the microwave.","Разогрей это в микроволновке."],
["freezer","морозильник","n","Put the meat in the freezer.","Положи мясо в морозилку."],
["kettle","чайник","n","Put the kettle on.","Поставь чайник."],
["socket","розетка","n","Is there a socket near the desk?","Есть розетка рядом со столом?"],
["mortgage rate","ставка по ипотеке","n","Mortgage rates have fallen.","Ставки по ипотеке снизились."],
["insulation","теплоизоляция","n","Good insulation saves energy.","Хорошая теплоизоляция экономит энергию."]
]},
{id:"x-13", title:"Еда и кухня", words:[
["portion","порция","n","The portions are huge.","Порции огромные."],
["starter","закуска","n","We ordered soup as a starter.","На закуску мы заказали суп."],
["dessert","десерт","n","What is for dessert?","Что на десерт?"],
["cuisine","кухня (национальная)","n","I love Italian cuisine.","Я люблю итальянскую кухню."],
["flavour","вкус, аромат","n","The sauce has a strong flavour.","У соуса насыщенный вкус."],
["bland","пресный","adj","The soup is a bit bland.","Суп немного пресный."],
["sour","кислый","adj","The lemon is sour.","Лимон кислый."],
["savoury","несладкий, солёный","adj","I prefer savoury snacks.","Я предпочитаю солёные закуски."],
["crispy","хрустящий","adj","The chips are crispy.","Чипсы хрустящие."],
["tender","нежный, мягкий (о мясе)","adj","The meat is tender.","Мясо нежное."],
["ripe","спелый","adj","The bananas are ripe.","Бананы спелые."],
["rotten","гнилой","adj","The apples are rotten.","Яблоки гнилые."],
["stale","чёрствый","adj","The bread is stale.","Хлеб чёрствый."],
["grill","жарить на гриле","v","We grilled some fish.","Мы приготовили рыбу на гриле."],
["roast","запекать","v","Roast the chicken for an hour.","Запекай курицу час."],
["steam","готовить на пару; пар","v","Steam the vegetables.","Приготовь овощи на пару."],
["chop","рубить, нарезать","v","Chop the onion finely.","Мелко нарежь лук."],
["peel","чистить (овощи); кожура","v","Peel the potatoes.","Почисти картошку."],
["grate","тереть на тёрке","v","Grate the cheese.","Натри сыр."],
["stir","помешивать","v","Stir the sauce.","Помешивай соус."],
["whisk","взбивать; венчик","v","Whisk the eggs.","Взбей яйца."],
["dough","тесто","n","Leave the dough to rise.","Оставь тесто подниматься."],
["seasoning","приправа","n","Add some seasoning.","Добавь приправы."],
["herb","трава (пряная)","n","Fresh herbs improve the taste.","Свежие травы улучшают вкус."],
["spice","специя","n","Indian food uses many spices.","В индийской кухне много специй."],
["garlic","чеснок","n","Add two cloves of garlic.","Добавь два зубчика чеснока."],
["dairy","молочные продукты","n","She does not eat dairy.","Она не ест молочное."],
["vegetarian","вегетарианец; вегетарианский","n","My sister is a vegetarian.","Моя сестра — вегетарианка."],
["vegan","веган","n","The restaurant has vegan dishes.","В ресторане есть веганские блюда."],
["nutritious","питательный","adj","Nuts are nutritious.","Орехи питательны."],
["calorie","калория","n","This drink has zero calories.","В этом напитке ноль калорий."],
["appetite","аппетит","n","I have lost my appetite.","Я потерял аппетит."],
["leftovers","остатки еды","n","We had the leftovers for lunch.","На обед мы доели остатки."],
["takeaway","еда навынос","n","Let us order a takeaway.","Давай закажем еду навынос."],
["gourmet","гурман; изысканный","adj","It is a gourmet restaurant.","Это ресторан для гурманов."]
]},
{id:"x-14", title:"Покупки и услуги", words:[
["warranty","гарантия","n","The phone has a two-year warranty.","На телефон гарантия два года."],
["in stock","в наличии","adv","The item is in stock.","Товар в наличии."],
["out of stock","нет в наличии","adv","Sorry, it is out of stock.","Извините, товара нет в наличии."],
["retail","розничная торговля","n","She works in retail.","Она работает в розничной торговле."],
["wholesale","оптовая торговля","n","They sell wholesale.","Они продают оптом."],
["voucher","ваучер, купон","n","I have a voucher for ten percent off.","У меня купон на скидку десять процентов."],
["loyalty card","карта лояльности","n","Do you have a loyalty card?","У вас есть карта лояльности?"],
["checkout","касса (в магазине)","n","Pay at the checkout.","Оплатите на кассе."],
["trolley","тележка","n","Grab a trolley.","Возьми тележку."],
["basket","корзина","n","Put it in the basket.","Положи в корзину."],
["cashier","кассир","n","The cashier gave me the change.","Кассир дал мне сдачу."],
["browse","просматривать, рассматривать","v","I was just browsing.","Я просто смотрю."],
["try on","примерять","v","Can I try on this jacket?","Можно примерить эту куртку?"],
["trendy","модный, трендовый","adj","She wears trendy clothes.","Она носит модную одежду."],
["casual","повседневный","adj","The dress code is casual.","Дресс-код — повседневный."],
["second-hand","подержанный","adj","I bought a second-hand bike.","Я купил подержанный велосипед."],
["affordable","доступный по цене","adj","The prices are affordable.","Цены доступные."],
["overpriced","слишком дорогой","adj","The cafe is overpriced.","Кафе слишком дорогое."],
["expiry date","срок годности","n","Check the expiry date.","Проверь срок годности."],
["counterfeit","поддельный","adj","They sold counterfeit watches.","Они продавали поддельные часы."],
["manufacturer","производитель","n","Contact the manufacturer.","Свяжись с производителем."],
["packaging","упаковка","n","The packaging was damaged.","Упаковка была повреждена."],
["dispatch","отправлять (товар)","v","Your order has been dispatched.","Ваш заказ отправлен."],
["tracking","отслеживание","n","Here is your tracking number.","Вот ваш номер для отслеживания."],
["return policy","условия возврата","n","Read the return policy.","Прочитай условия возврата."],
["faulty","неисправный","adj","The product is faulty.","Товар неисправен."],
["durable","прочный, долговечный","adj","These boots are durable.","Эти ботинки прочные."],
["thrifty","бережливый","adj","My grandmother is very thrifty.","Моя бабушка очень бережливая."],
["haggle","торговаться","v","He haggled over the price.","Он торговался о цене."],
["catalogue","каталог","n","Choose from the catalogue.","Выбери из каталога."],
["merchandise","товары","n","The shop sells sports merchandise.","Магазин продаёт спортивные товары."],
["auction","аукцион","n","The painting was sold at auction.","Картину продали на аукционе."],
["instalment","платёж в рассрочку","n","You can pay in instalments.","Можно платить в рассрочку."],
["subscription box","подписка на коробку","n","She gets a subscription box every month.","Каждый месяц она получает коробку по подписке."],
["outlet","магазин распродаж, аутлет","n","We shop at the outlet.","Мы покупаем одежду в аутлете."],
["flea market","блошиный рынок","n","I found it at a flea market.","Я нашёл это на блошином рынке."],
["cash register","кассовый аппарат","n","The cash register is broken.","Кассовый аппарат сломан."]
]},
{id:"x-15", title:"Искусство и медиа", words:[
["rehearse","репетировать","v","They rehearsed for weeks.","Они репетировали неделями."],
["rehearsal","репетиция","n","The rehearsal starts at six.","Репетиция начинается в шесть."],
["masterpiece","шедевр","n","The novel is a masterpiece.","Роман — шедевр."],
["publisher","издатель","n","The publisher rejected the manuscript.","Издатель отклонил рукопись."],
["soundtrack","саундтрек","n","The soundtrack is beautiful.","Саундтрек прекрасен."],
["lyrics","текст песни","n","I do not know the lyrics.","Я не знаю слов песни."],
["orchestra","оркестр","n","The orchestra played Mozart.","Оркестр играл Моцарта."],
["choir","хор","n","She sings in a choir.","Она поёт в хоре."],
["inspiration","вдохновение","n","Nature is my inspiration.","Природа — моё вдохновение."],
["premiere","премьера","n","The premiere is on Friday.","Премьера в пятницу."]
]},
{id:"x-16", title:"Прилагательные", words:[
["adequate","достаточный, адекватный","adj","The salary is adequate.","Зарплата достаточная."],
["ambiguous","двусмысленный","adj","The instructions were ambiguous.","Инструкции были двусмысленными."],
["considerable","значительный","adj","It took considerable effort.","Это потребовало значительных усилий."],
["controversial","спорный","adj","It is a controversial topic.","Это спорная тема."],
["distinct","отчётливый, отдельный","adj","There are two distinct groups.","Есть две отдельные группы."],
["dull","скучный, тусклый","adj","The lecture was dull.","Лекция была скучной."],
["eventual","окончательный, конечный","adj","The eventual winner was Spain.","В итоге победила Испания."],
["evident","очевидный","adj","It is evident that he lied.","Очевидно, что он солгал."],
["exhausting","изматывающий","adj","It was an exhausting day.","День был изматывающим."],
["frequent","частый","adj","He is a frequent visitor.","Он частый гость."],
["genuine","подлинный, искренний","adj","It is a genuine diamond.","Это настоящий бриллиант."],
["gradual","постепенный","adj","There was a gradual improvement.","Наступило постепенное улучшение."],
["harsh","суровый, резкий","adj","The winter was harsh.","Зима была суровой."],
["inevitable","неизбежный","adj","Change is inevitable.","Перемены неизбежны."],
["remarkable","замечательный, выдающийся","adj","It was a remarkable success.","Это был выдающийся успех."],
["reluctant","неохотный","adj","He was reluctant to help.","Он неохотно помогал."],
["sufficient","достаточный","adj","We have sufficient time.","У нас достаточно времени."],
["vague","неясный, расплывчатый","adj","His answer was vague.","Его ответ был расплывчатым."],
["urgent","срочный","adj","It is an urgent matter.","Это срочный вопрос."],
["thorough","тщательный","adj","The doctor did a thorough check.","Врач провёл тщательный осмотр."],
["peculiar","своеобразный, странный","adj","The cheese has a peculiar smell.","У сыра своеобразный запах."],
["subtle","тонкий, едва заметный","adj","There is a subtle difference.","Есть тонкое различие."]
]},
{id:"x-17", title:"Глаголы", words:[
["accomplish","достигать, выполнять","v","We accomplished our goal.","Мы достигли цели."],
["adjust","регулировать, приспосабливаться","v","Adjust the mirror before driving.","Перед поездкой отрегулируй зеркало."],
["cope","справляться","v","How do you cope with stress?","Как ты справляешься со стрессом?"],
["exceed","превышать","v","Do not exceed the speed limit.","Не превышай ограничение скорости."],
["overcome","преодолевать","v","She overcame her fear.","Она преодолела свой страх."],
["postpone","откладывать","v","The meeting was postponed.","Встречу отложили."],
["tackle","решать (проблему)","v","We need to tackle the issue.","Нам нужно решить эту проблему."],
["undergo","подвергаться, проходить","v","She underwent surgery.","Она перенесла операцию."],
["distinguish","различать","v","Can you distinguish the two sounds?","Ты можешь различить эти два звука?"],
["fulfil","выполнять, осуществлять","v","She fulfilled her dream.","Она осуществила свою мечту."],
["neglect","пренебрегать","v","Do not neglect your health.","Не пренебрегай здоровьем."]
]},
{id:"x-18", title:"Фразовые глаголы", words:[
["bring up","воспитывать; поднимать (тему)","v","She brought up three children.","Она воспитала троих детей."],
["break down","ломаться; расплакаться","v","The car broke down on the way.","По дороге машина сломалась."],
["call off","отменять","v","They called off the match.","Они отменили матч."],
["carry on","продолжать","v","Carry on with your work.","Продолжай работу."],
["carry out","выполнять, проводить","v","We carried out a survey.","Мы провели опрос."],
["catch up","догонять, нагонять","v","I need to catch up on my emails.","Мне нужно разобраться с накопившейся почтой."],
["come across","случайно встретить, натолкнуться","v","I came across an old photo.","Я случайно нашёл старую фотографию."],
["come up with","придумать","v","She came up with a great idea.","Она придумала отличную идею."],
["cut down","сокращать","v","I am trying to cut down on coffee.","Я пытаюсь пить меньше кофе."],
["deal with","иметь дело, справляться","v","I will deal with the complaint.","Я разберусь с жалобой."],
["figure out","понять, разобраться","v","I cannot figure out this puzzle.","Не могу разгадать эту головоломку."],
["find out","выяснять","v","Find out when the shop opens.","Выясни, когда открывается магазин."],
["get along","ладить","v","I get along well with my colleagues.","Я хорошо лажу с коллегами."],
["get over","пережить, оправиться","v","It took him a year to get over the divorce.","Ему понадобился год, чтобы пережить развод."],
["give up","сдаваться, бросать","v","Never give up.","Никогда не сдавайся."],
["go on","продолжаться, происходить","v","What is going on here?","Что здесь происходит?"],
["hold on","подождать","v","Hold on, I will check.","Подожди, я проверю."],
["keep up","не отставать","v","I cannot keep up with him.","Я не поспеваю за ним."],
["look after","присматривать","v","Who will look after the dog?","Кто присмотрит за собакой?"],
["look forward to","ждать с нетерпением","v","I look forward to your reply.","С нетерпением жду вашего ответа."],
["look into","изучать, расследовать","v","We will look into the problem.","Мы изучим проблему."],
["look up","искать (в словаре)","v","Look up the word in a dictionary.","Посмотри слово в словаре."],
["make up","выдумывать; мириться","v","He made up an excuse.","Он выдумал оправдание."],
["pick up","забирать; подхватывать","v","I will pick up the kids at five.","Я заберу детей в пять."],
["point out","указывать, отмечать","v","She pointed out a mistake.","Она указала на ошибку."],
["put off","откладывать","v","Do not put off the decision.","Не откладывай решение."],
["put up with","мириться, терпеть","v","I cannot put up with the noise.","Я не могу терпеть этот шум."],
["run out of","заканчиваться (о запасах)","v","We ran out of milk.","У нас закончилось молоко."],
["set up","учреждать, устанавливать","v","They set up a new company.","Они основали новую компанию."],
["show up","появляться, приходить","v","He did not show up.","Он не появился."],
["sort out","разобраться, уладить","v","Let us sort out the problem.","Давай уладим проблему."],
["take off","взлетать; снимать","v","The plane took off on time.","Самолёт взлетел вовремя."],
["take over","брать под контроль","v","A bigger firm took over the company.","Более крупная фирма поглотила компанию."],
["take up","начать заниматься","v","I took up yoga last year.","В прошлом году я занялся йогой."],
["turn down","отклонять; убавлять","v","She turned down the offer.","Она отклонила предложение."],
["turn up","появляться; прибавлять","v","He turned up late.","Он явился с опозданием."],
["work out","тренироваться; решать","v","I work out three times a week.","Я тренируюсь три раза в неделю."],
["back up","делать резервную копию; поддерживать","v","Back up your files.","Сделай резервную копию файлов."],
["check out","проверять; выезжать из отеля","v","Check out this website.","Взгляни на этот сайт."],
["count on","рассчитывать на","v","You can count on me.","Ты можешь на меня рассчитывать."],
["end up","оказаться в итоге","v","We ended up staying home.","В итоге мы остались дома."],
["fill in","заполнять","v","Fill in this form.","Заполни эту форму."],
["go through","проходить через, просматривать","v","She went through a hard time.","Она прошла через трудное время."],
["hand in","сдавать (работу)","v","Hand in your essay by Friday.","Сдай эссе до пятницы."],
["let down","подводить","v","Do not let me down.","Не подведи меня."],
["rely on","полагаться на","v","I rely on public transport.","Я полагаюсь на общественный транспорт."],
["stand for","означать; отстаивать","v","What does BBC stand for?","Что означает BBC?"],
["drop out","бросать (учёбу)","v","He dropped out of college.","Он бросил колледж."],
["run into","случайно встретить","v","I ran into an old friend.","Я случайно встретил старого друга."],
["wear out","изнашивать(ся); выматывать","v","My shoes wore out.","Мои ботинки износились."]
]},
{id:"x-19", title:"Наречия и связки", words:[
["accordingly","соответственно","adv","Plan accordingly.","Планируй соответственно."],
["additionally","дополнительно, кроме того","adv","Additionally, we need a budget.","Кроме того, нам нужен бюджет."],
["alternatively","в качестве альтернативы","adv","Alternatively, we could go by train.","Как вариант, мы могли бы поехать на поезде."],
["barely","едва","adv","I barely slept last night.","Прошлой ночью я почти не спал."],
["consequently","следовательно","adv","He was late; consequently, he missed the train.","Он опоздал; следовательно, пропустил поезд."],
["formerly","ранее, прежде","adv","The hotel was formerly a hospital.","Раньше отель был больницей."],
["frankly","откровенно говоря","adv","Frankly, I do not care.","Честно говоря, мне всё равно."],
["hence","следовательно","adv","It rained; hence the delay.","Шёл дождь — отсюда задержка."],
["inevitably","неизбежно","adv","Prices will inevitably rise.","Цены неизбежно вырастут."],
["likewise","аналогично","adv","She smiled, and he did likewise.","Она улыбнулась, и он сделал так же."],
["merely","просто, всего лишь","adv","It is merely a suggestion.","Это всего лишь предложение."],
["moreover","более того","adv","Moreover, it is cheap.","Более того, это дёшево."],
["nonetheless","тем не менее","adv","The plan is risky; nonetheless, we will try.","План рискованный; тем не менее мы попробуем."],
["notably","в особенности","adv","Many countries, notably Japan, agreed.","Многие страны, в особенности Япония, согласились."],
["presumably","предположительно","adv","Presumably, she knows.","Предположительно, она знает."],
["primarily","главным образом","adv","The course is primarily for beginners.","Курс в первую очередь для начинающих."],
["regardless","несмотря ни на что","adv","We will go regardless of the weather.","Мы поедем независимо от погоды."],
["roughly","примерно, грубо","adv","There were roughly a hundred people.","Было примерно сто человек."],
["seldom","редко","adv","He seldom complains.","Он редко жалуется."],
["subsequently","впоследствии","adv","He subsequently moved to Spain.","Впоследствии он переехал в Испанию."],
["virtually","практически, фактически","adv","The city was virtually empty.","Город был практически пуст."]
]},
{id:"x-20", title:"Абстрактные понятия", words:[
["assumption","предположение","n","That is a dangerous assumption.","Это опасное предположение."],
["awareness","осведомлённость","n","The campaign raised awareness.","Кампания повысила осведомлённость."],
["criteria","критерии","n","What are the selection criteria?","Каковы критерии отбора?"],
["exception","исключение","n","There is one exception.","Есть одно исключение."],
["implication","последствие, подтекст","n","What are the implications?","Каковы последствия?"],
["likelihood","вероятность","n","There is a high likelihood of rain.","Высока вероятность дождя."],
["obstacle","препятствие","n","Money is the main obstacle.","Деньги — главное препятствие."],
["proportion","доля, соотношение","n","A large proportion of people agreed.","Большая доля людей согласилась."],
["scope","масштаб, рамки","n","This is beyond the scope of the report.","Это выходит за рамки отчёта."],
["tendency","тенденция, склонность","n","He has a tendency to exaggerate.","У него склонность преувеличивать."],
["dilemma","дилемма","n","We face a dilemma.","Мы стоим перед дилеммой."],
["compromise","компромисс","n","We reached a compromise.","Мы пришли к компромиссу."],
["consistency","последовательность","n","Consistency is the key to learning.","Регулярность — ключ к обучению."],
["flexibility","гибкость","n","The job offers flexibility.","Работа даёт гибкость."],
["motivation","мотивация","n","Motivation is important for learning.","Мотивация важна для учёбы."],
["stability","стабильность","n","People want stability.","Люди хотят стабильности."],
["uncertainty","неопределённость","n","There is a lot of uncertainty.","Много неопределённости."]
]}
]};
if(typeof module!=="undefined")module.exports=WORDS_EXTRA;
