// Слова 501–1000, уровень B1–B2. Формат: [английское, перевод, часть речи, пример]
const WORDS_B = [
// Уровень 11 — путешествия и транспорт
["accommodation","жильё, размещение","n","The price includes accommodation."],
["destination","пункт назначения","n","Paris is a popular destination."],
["itinerary","маршрут, план поездки","n","Our itinerary includes three cities."],
["departure","отправление, вылет","n","Departure is at seven."],
["arrival","прибытие","n","Arrival time is nine thirty."],
["board","садиться (на транспорт)","v","We boarded the plane at noon."],
["boarding pass","посадочный талон","n","Show your boarding pass at the gate."],
["gate","выход на посадку; ворота","n","The flight leaves from gate twelve."],
["aisle","проход (между рядами)","n","I prefer an aisle seat."],
["customs","таможня","n","We waited an hour at customs."],
["embassy","посольство","n","Contact the embassy if you lose your passport."],
["sightseeing","осмотр достопримечательностей","n","We went sightseeing in Rome."],
["landmark","достопримечательность, ориентир","n","The tower is a famous landmark."],
["souvenir","сувенир","n","I bought a souvenir for my mother."],
["resort","курорт","n","We stayed at a beach resort."],
["cruise","круиз","n","They went on a cruise."],
["ferry","паром","n","The ferry crosses the river every hour."],
["motorway","автомагистраль","n","Take the motorway to save time."],
["lane","полоса (дороги); переулок","n","Stay in the left lane."],
["junction","перекрёсток, развязка","n","Turn right at the next junction."],
["roundabout","круговой перекрёсток","n","Take the second exit at the roundabout."],
["detour","объезд","n","We had to make a detour."],
["traffic jam","пробка","n","We were stuck in a traffic jam."],
["rush hour","час пик","n","Avoid driving in rush hour."],
["fare","плата за проезд","n","The bus fare is two dollars."],
["vehicle","транспортное средство","n","No vehicles are allowed here."],
["licence","лицензия, права","n","He lost his driving licence."],
["breakdown","поломка","n","We had a breakdown on the motorway."],
["puncture","прокол (шины)","n","I got a puncture on the way home."],
["fuel","топливо","n","We are running out of fuel."],
["petrol","бензин","n","Petrol prices went up."],
["brake","тормоз; тормозить","n","The brakes do not work."],
["overtake","обгонять","v","Do not overtake on a bend."],
["speed limit","ограничение скорости","n","The speed limit here is fifty."],
["pedestrian","пешеход","n","Pedestrians must use the crossing."],
["crossing","переход, переезд","n","Wait at the crossing."],
["timetable","расписание","n","Check the train timetable."],
["platform","платформа","n","The train leaves from platform four."],
["seat belt","ремень безопасности","n","Fasten your seat belt."],
["turbulence","турбулентность","n","We hit some turbulence over the ocean."],
["jet lag","джетлаг","n","I had terrible jet lag after the flight."],
["layover","пересадка (в аэропорту)","n","We had a two-hour layover in Dubai."],
["backpacker","путешественник с рюкзаком","n","The hostel is full of backpackers."],
["excursion","экскурсия","n","We took an excursion to the island."],
["voyage","морское путешествие","n","The voyage lasted two weeks."],
["expedition","экспедиция","n","They joined an expedition to the Arctic."],
["scenery","пейзаж","n","The scenery in the mountains is amazing."],
["remote","отдалённый","adj","They live in a remote village."],
["picturesque","живописный","adj","It is a picturesque old town."],
["vibrant","яркий, оживлённый","adj","The city has a vibrant nightlife."],
// Уровень 12 — дом и быт
["landlord","арендодатель","n","The landlord raised the rent."],
["tenant","арендатор, жилец","n","The tenant pays on the first of the month."],
["rent","арендная плата; снимать","n","The rent is too high."],
["lease","договор аренды","n","We signed a one-year lease."],
["neighbourhood","район, окрестности","n","It is a quiet neighbourhood."],
["suburb","пригород","n","They moved to the suburbs."],
["property","недвижимость, имущество","n","Property prices are rising."],
["estate agent","агент по недвижимости","n","The estate agent showed us the flat."],
["furnish","обставлять мебелью","v","The flat is fully furnished."],
["furniture","мебель","n","We need new furniture."],
["appliance","бытовой прибор","n","The kitchen has modern appliances."],
["utilities","коммунальные услуги","n","Utilities are included in the rent."],
["plumber","сантехник","n","Call a plumber about the leak."],
["electrician","электрик","n","The electrician fixed the wiring."],
["leak","протечка; протекать","n","There is a leak under the sink."],
["repair","ремонтировать; ремонт","v","We need to repair the roof."],
["maintenance","обслуживание, содержание","n","The lift is closed for maintenance."],
["decorate","делать ремонт, украшать","v","We decorated the living room."],
["renovate","реконструировать","v","They renovated the old house."],
["ceiling","потолок","n","The ceiling is very high."],
["basement","подвал","n","The washing machine is in the basement."],
["attic","чердак","n","Old boxes are in the attic."],
["garage","гараж","n","The car is in the garage."],
["fence","забор","n","The dog jumped over the fence."],
["lawn","газон","n","He mows the lawn every Saturday."],
["chore","работа по дому","n","Washing up is my least favourite chore."],
["laundry","стирка, бельё","n","I do the laundry on Sundays."],
["iron","гладить; утюг","v","I need to iron my shirt."],
["vacuum","пылесосить; пылесос","v","Vacuum the carpet, please."],
["tidy","прибирать; опрятный","v","Tidy your room."],
["mess","беспорядок","n","What a mess!"],
["clutter","хлам, беспорядок","n","There is too much clutter on the desk."],
["shelf","полка","n","Put the books on the shelf."],
["drawer","выдвижной ящик","n","The keys are in the top drawer."],
["cupboard","шкаф","n","The cups are in the cupboard."],
["curtain","штора","n","Close the curtains."],
["blanket","одеяло","n","Bring me a blanket."],
["pillow","подушка","n","This pillow is too soft."],
["mattress","матрас","n","We bought a new mattress."],
["tap","кран","n","The tap is dripping."],
["sink","раковина","n","The dishes are in the sink."],
["oven","духовка","n","Preheat the oven."],
["microwave","микроволновка","n","Heat it in the microwave."],
["fridge","холодильник","n","The milk is in the fridge."],
["freezer","морозильник","n","Put the meat in the freezer."],
["kettle","чайник","n","Put the kettle on."],
["socket","розетка","n","Is there a socket near the desk?"],
["mortgage rate","ставка по ипотеке","n","Mortgage rates have fallen."],
["insulation","теплоизоляция","n","Good insulation saves energy."],
["household","домохозяйство; домашний","n","The average household has two cars."],
// Уровень 13 — еда и кухня
["ingredient","ингредиент","n","Mix all the ingredients."],
["recipe","рецепт","n","This recipe is easy."],
["portion","порция","n","The portions are huge."],
["dish","блюдо","n","This is a traditional dish."],
["course","блюдо (в порядке подачи); курс","n","The meal had three courses."],
["starter","закуска","n","We ordered soup as a starter."],
["dessert","десерт","n","What is for dessert?"],
["cuisine","кухня (национальная)","n","I love Italian cuisine."],
["flavour","вкус, аромат","n","The sauce has a strong flavour."],
["spicy","острый (о еде)","adj","The curry is too spicy."],
["bland","пресный","adj","The soup is a bit bland."],
["sour","кислый","adj","The lemon is sour."],
["bitter","горький","adj","The coffee is bitter."],
["savoury","несладкий, солёный","adj","I prefer savoury snacks."],
["crispy","хрустящий","adj","The chips are crispy."],
["tender","нежный, мягкий (о мясе)","adj","The meat is tender."],
["raw","сырой","adj","Do not eat raw chicken."],
["ripe","спелый","adj","The bananas are ripe."],
["rotten","гнилой","adj","The apples are rotten."],
["stale","чёрствый","adj","The bread is stale."],
["boil","варить, кипятить","v","Boil the water first."],
["fry","жарить","v","Fry the onions in oil."],
["grill","жарить на гриле","v","We grilled some fish."],
["roast","запекать","v","Roast the chicken for an hour."],
["bake","печь","v","I baked a cake."],
["steam","готовить на пару; пар","v","Steam the vegetables."],
["chop","рубить, нарезать","v","Chop the onion finely."],
["slice","нарезать ломтиками; ломтик","v","Slice the bread."],
["peel","чистить (овощи); кожура","v","Peel the potatoes."],
["grate","тереть на тёрке","v","Grate the cheese."],
["stir","помешивать","v","Stir the sauce."],
["whisk","взбивать; венчик","v","Whisk the eggs."],
["pour","наливать","v","Pour the milk into the bowl."],
["spread","намазывать; распространяться","v","Spread butter on the toast."],
["dough","тесто","n","Leave the dough to rise."],
["sauce","соус","n","The sauce is delicious."],
["seasoning","приправа","n","Add some seasoning."],
["herb","трава (пряная)","n","Fresh herbs improve the taste."],
["spice","специя","n","Indian food uses many spices."],
["garlic","чеснок","n","Add two cloves of garlic."],
["dairy","молочные продукты","n","She does not eat dairy."],
["vegetarian","вегетарианец; вегетарианский","n","My sister is a vegetarian."],
["vegan","веган","n","The restaurant has vegan dishes."],
["nutritious","питательный","adj","Nuts are nutritious."],
["calorie","калория","n","This drink has zero calories."],
["appetite","аппетит","n","I have lost my appetite."],
["tip","чаевые; совет","n","We left a tip for the waiter."],
["leftovers","остатки еды","n","We had the leftovers for lunch."],
["takeaway","еда навынос","n","Let us order a takeaway."],
["gourmet","гурман; изысканный","adj","It is a gourmet restaurant."],
// Уровень 14 — покупки и услуги
["label","этикетка","n","Read the label before washing."],
["warranty","гарантия","n","The phone has a two-year warranty."],
["guarantee","гарантировать; гарантия","v","We guarantee delivery in two days."],
["complaint","жалоба","n","I want to make a complaint."],
["delivery","доставка","n","Delivery is free."],
["in stock","в наличии","adv","The item is in stock."],
["out of stock","нет в наличии","adv","Sorry, it is out of stock."],
["retail","розничная торговля","n","She works in retail."],
["wholesale","оптовая торговля","n","They sell wholesale."],
["voucher","ваучер, купон","n","I have a voucher for ten percent off."],
["loyalty card","карта лояльности","n","Do you have a loyalty card?"],
["checkout","касса (в магазине)","n","Pay at the checkout."],
["trolley","тележка","n","Grab a trolley."],
["basket","корзина","n","Put it in the basket."],
["cashier","кассир","n","The cashier gave me the change."],
["queue","очередь; стоять в очереди","n","There was a long queue."],
["browse","просматривать, рассматривать","v","I was just browsing."],
["try on","примерять","v","Can I try on this jacket?"],
["suit","подходить, идти (об одежде); костюм","v","That colour suits you."],
["match","сочетаться; матч","v","The shoes match the bag."],
["fashionable","модный","adj","This style is fashionable now."],
["trendy","модный, трендовый","adj","She wears trendy clothes."],
["casual","повседневный","adj","The dress code is casual."],
["formal","официальный","adj","It is a formal event."],
["second-hand","подержанный","adj","I bought a second-hand bike."],
["luxury","роскошь","n","They live in luxury."],
["affordable","доступный по цене","adj","The prices are affordable."],
["overpriced","слишком дорогой","adj","The cafe is overpriced."],
["reasonable","разумный, приемлемый","adj","The price is reasonable."],
["quantity","количество","n","We ordered a large quantity."],
["expiry date","срок годности","n","Check the expiry date."],
["counterfeit","поддельный","adj","They sold counterfeit watches."],
["manufacturer","производитель","n","Contact the manufacturer."],
["packaging","упаковка","n","The packaging was damaged."],
["dispatch","отправлять (товар)","v","Your order has been dispatched."],
["tracking","отслеживание","n","Here is your tracking number."],
["return policy","условия возврата","n","Read the return policy."],
["faulty","неисправный","adj","The product is faulty."],
["durable","прочный, долговечный","adj","These boots are durable."],
["thrifty","бережливый","adj","My grandmother is very thrifty."],
["haggle","торговаться","v","He haggled over the price."],
["catalogue","каталог","n","Choose from the catalogue."],
["merchandise","товары","n","The shop sells sports merchandise."],
["consumer","потребитель","n","Consumers want lower prices."],
["auction","аукцион","n","The painting was sold at auction."],
["instalment","платёж в рассрочку","n","You can pay in instalments."],
["subscription box","подписка на коробку","n","She gets a subscription box every month."],
["outlet","магазин распродаж, аутлет","n","We shop at the outlet."],
["flea market","блошиный рынок","n","I found it at a flea market."],
["cash register","кассовый аппарат","n","The cash register is broken."],
// Уровень 15 — искусство и медиа
["audience","аудитория, публика","n","The audience applauded."],
["performance","выступление, представление","n","The performance was excellent."],
["perform","выступать, исполнять","v","The band performed live."],
["rehearse","репетировать","v","They rehearsed for weeks."],
["rehearsal","репетиция","n","The rehearsal starts at six."],
["stage","сцена; этап","n","The actors walked onto the stage."],
["scene","сцена (эпизод)","n","The final scene is very sad."],
["plot","сюжет","n","The plot is hard to follow."],
["cast","актёрский состав","n","The cast was excellent."],
["director","режиссёр; директор","n","The director won an award."],
["script","сценарий","n","She wrote the script."],
["review","рецензия, отзыв","n","The film got good reviews."],
["critic","критик","n","The critics loved the play."],
["exhibition","выставка","n","There is an exhibition of modern art."],
["gallery","галерея","n","The gallery is free on Sundays."],
["sculpture","скульптура","n","The sculpture is made of bronze."],
["portrait","портрет","n","She painted his portrait."],
["landscape","пейзаж","n","He paints landscapes."],
["masterpiece","шедевр","n","The novel is a masterpiece."],
["genre","жанр","n","What genre do you like?"],
["novel","роман","n","She is reading a novel."],
["fiction","художественная литература","n","I prefer fiction to biographies."],
["poetry","поэзия","n","He writes poetry."],
["poem","стихотворение","n","She read a poem aloud."],
["chapter","глава","n","Read the first chapter."],
["author","автор","n","Who is the author?"],
["publish","публиковать, издавать","v","The book was published in 2020."],
["publisher","издатель","n","The publisher rejected the manuscript."],
["edition","издание","n","This is the second edition."],
["headline","заголовок","n","The headline was shocking."],
["journalist","журналист","n","The journalist asked a question."],
["editor","редактор","n","The editor cut the article."],
["broadcast","транслировать; трансляция","v","The match was broadcast live."],
["channel","канал","n","Which channel is the news on?"],
["episode","эпизод, серия","n","The last episode was great."],
["series","сериал; серия","n","I am watching a new series."],
["documentary","документальный фильм","n","We watched a documentary about whales."],
["soundtrack","саундтрек","n","The soundtrack is beautiful."],
["lyrics","текст песни","n","I do not know the lyrics."],
["rhythm","ритм","n","The song has a great rhythm."],
["orchestra","оркестр","n","The orchestra played Mozart."],
["choir","хор","n","She sings in a choir."],
["instrument","инструмент (музыкальный)","n","Do you play an instrument?"],
["talent","талант","n","He has a talent for music."],
["creative","творческий","adj","She is very creative."],
["inspire","вдохновлять","v","Her story inspired me."],
["inspiration","вдохновение","n","Nature is my inspiration."],
["imagination","воображение","n","Use your imagination."],
["celebrity","знаменитость","n","The celebrity signed autographs."],
["premiere","премьера","n","The premiere is on Friday."],
// Уровень 16 — прилагательные B1–B2
["adequate","достаточный, адекватный","adj","The salary is adequate."],
["ambiguous","двусмысленный","adj","The instructions were ambiguous."],
["apparent","очевидный, кажущийся","adj","It was apparent that he was tired."],
["appropriate","подходящий, уместный","adj","Wear appropriate clothes."],
["aware","осведомлённый, осознающий","adj","I am aware of the risk."],
["capable","способный","adj","She is capable of great things."],
["complicated","сложный","adj","The rules are complicated."],
["confusing","сбивающий с толку","adj","The map is confusing."],
["consistent","последовательный, стабильный","adj","His work is consistent."],
["considerable","значительный","adj","It took considerable effort."],
["controversial","спорный","adj","It is a controversial topic."],
["convenient","удобный","adj","Is ten o'clock convenient?"],
["crucial","решающий, ключевой","adj","This is a crucial decision."],
["current","текущий","adj","What is your current address?"],
["decent","приличный, достойный","adj","He earns a decent salary."],
["distinct","отчётливый, отдельный","adj","There are two distinct groups."],
["dull","скучный, тусклый","adj","The lecture was dull."],
["efficient","эффективный","adj","The new system is efficient."],
["enormous","огромный","adj","They have an enormous house."],
["essential","необходимый, важнейший","adj","Water is essential for life."],
["eventual","окончательный, конечный","adj","The eventual winner was Spain."],
["evident","очевидный","adj","It is evident that he lied."],
["exhausting","изматывающий","adj","It was an exhausting day."],
["familiar","знакомый","adj","Her face looks familiar."],
["frequent","частый","adj","He is a frequent visitor."],
["fundamental","основополагающий","adj","This is a fundamental question."],
["genuine","подлинный, искренний","adj","It is a genuine diamond."],
["gradual","постепенный","adj","There was a gradual improvement."],
["harsh","суровый, резкий","adj","The winter was harsh."],
["inevitable","неизбежный","adj","Change is inevitable."],
["initial","первоначальный","adj","My initial reaction was surprise."],
["keen","увлечённый, заинтересованный","adj","She is keen on sports."],
["massive","огромный","adj","The building is massive."],
["obvious","очевидный","adj","The answer is obvious."],
["odd","странный; нечётный","adj","That is an odd question."],
["plain","простой, ясный","adj","Use plain language."],
["previous","предыдущий","adj","See the previous page."],
["rapid","быстрый, стремительный","adj","There was rapid growth."],
["relevant","относящийся к делу","adj","Is this information relevant?"],
["remarkable","замечательный, выдающийся","adj","It was a remarkable success."],
["reluctant","неохотный","adj","He was reluctant to help."],
["significant","значительный","adj","There was a significant change."],
["sufficient","достаточный","adj","We have sufficient time."],
["suitable","подходящий","adj","The film is not suitable for children."],
["vague","неясный, расплывчатый","adj","His answer was vague."],
["vast","обширный, огромный","adj","Russia is a vast country."],
["urgent","срочный","adj","It is an urgent matter."],
["thorough","тщательный","adj","The doctor did a thorough check."],
["peculiar","своеобразный, странный","adj","The cheese has a peculiar smell."],
["subtle","тонкий, едва заметный","adj","There is a subtle difference."],
// Уровень 17 — глаголы B1–B2
["accomplish","достигать, выполнять","v","We accomplished our goal."],
["adapt","адаптироваться","v","Children adapt quickly."],
["adjust","регулировать, приспосабливаться","v","Adjust the mirror before driving."],
["arrange","организовывать, договариваться","v","I arranged a meeting for Monday."],
["attempt","пытаться; попытка","v","He attempted to climb the mountain."],
["avoid","избегать","v","Avoid sugar if you can."],
["bother","беспокоить","v","Sorry to bother you."],
["cope","справляться","v","How do you cope with stress?"],
["demonstrate","демонстрировать","v","The results demonstrate the effect."],
["deserve","заслуживать","v","You deserve a break."],
["encourage","поощрять, воодушевлять","v","My parents encouraged me to study."],
["ensure","обеспечивать, гарантировать","v","Ensure the door is locked."],
["establish","основывать, устанавливать","v","The company was established in 1990."],
["exceed","превышать","v","Do not exceed the speed limit."],
["expand","расширять(ся)","v","The business is expanding."],
["gain","получать, приобретать","v","He gained experience abroad."],
["gather","собирать(ся)","v","We gathered in the hall."],
["handle","справляться, обращаться","v","She handled the situation well."],
["ignore","игнорировать","v","Ignore his comments."],
["indicate","указывать, свидетельствовать","v","The data indicate a problem."],
["involve","включать, вовлекать","v","The job involves travel."],
["maintain","поддерживать, сохранять","v","Maintain a healthy diet."],
["obtain","получать","v","You must obtain a visa."],
["occur","происходить","v","The accident occurred at night."],
["overcome","преодолевать","v","She overcame her fear."],
["participate","участвовать","v","Everyone participated in the game."],
["possess","обладать","v","He possesses great talent."],
["postpone","откладывать","v","The meeting was postponed."],
["prevent","предотвращать","v","Vaccines prevent disease."],
["pursue","преследовать (цель), заниматься","v","She pursued a career in law."],
["reduce","сокращать","v","We must reduce costs."],
["remain","оставаться","v","The situation remains difficult."],
["require","требовать","v","The job requires experience."],
["resist","сопротивляться","v","I cannot resist chocolate."],
["retain","сохранять, удерживать","v","The company retained its staff."],
["reveal","раскрывать, обнаруживать","v","The report revealed the truth."],
["seek","искать, стремиться","v","They are seeking a solution."],
["struggle","бороться, с трудом справляться","v","He struggled with maths."],
["survive","выживать","v","Only two people survived."],
["tackle","решать (проблему)","v","We need to tackle the issue."],
["undergo","подвергаться, проходить","v","She underwent surgery."],
["abandon","покидать, отказываться","v","They abandoned the plan."],
["accompany","сопровождать","v","I will accompany you to the station."],
["acquire","приобретать","v","He acquired a new skill."],
["contribute","вносить вклад","v","Everyone contributed to the project."],
["distinguish","различать","v","Can you distinguish the two sounds?"],
["emerge","появляться, возникать","v","New problems emerged."],
["enhance","улучшать, усиливать","v","Music enhances the mood."],
["fulfil","выполнять, осуществлять","v","She fulfilled her dream."],
["neglect","пренебрегать","v","Do not neglect your health."],
// Уровень 18 — фразовые глаголы
["bring up","воспитывать; поднимать (тему)","v","She brought up three children."],
["break down","ломаться; расплакаться","v","The car broke down on the way."],
["call off","отменять","v","They called off the match."],
["carry on","продолжать","v","Carry on with your work."],
["carry out","выполнять, проводить","v","We carried out a survey."],
["catch up","догонять, нагонять","v","I need to catch up on my emails."],
["come across","случайно встретить, натолкнуться","v","I came across an old photo."],
["come up with","придумать","v","She came up with a great idea."],
["cut down","сокращать","v","I am trying to cut down on coffee."],
["deal with","иметь дело, справляться","v","I will deal with the complaint."],
["figure out","понять, разобраться","v","I cannot figure out this puzzle."],
["find out","выяснять","v","Find out when the shop opens."],
["get along","ладить","v","I get along well with my colleagues."],
["get over","пережить, оправиться","v","It took him a year to get over the divorce."],
["give up","сдаваться, бросать","v","Never give up."],
["go on","продолжаться, происходить","v","What is going on here?"],
["hold on","подождать","v","Hold on, I will check."],
["keep up","не отставать","v","I cannot keep up with him."],
["look after","присматривать","v","Who will look after the dog?"],
["look forward to","ждать с нетерпением","v","I look forward to your reply."],
["look into","изучать, расследовать","v","We will look into the problem."],
["look up","искать (в словаре)","v","Look up the word in a dictionary."],
["make up","выдумывать; мириться","v","He made up an excuse."],
["pick up","забирать; подхватывать","v","I will pick up the kids at five."],
["point out","указывать, отмечать","v","She pointed out a mistake."],
["put off","откладывать","v","Do not put off the decision."],
["put up with","мириться, терпеть","v","I cannot put up with the noise."],
["run out of","заканчиваться (о запасах)","v","We ran out of milk."],
["set up","учреждать, устанавливать","v","They set up a new company."],
["show up","появляться, приходить","v","He did not show up."],
["sort out","разобраться, уладить","v","Let us sort out the problem."],
["take off","взлетать; снимать","v","The plane took off on time."],
["take over","брать под контроль","v","A bigger firm took over the company."],
["take up","начать заниматься","v","I took up yoga last year."],
["turn down","отклонять; убавлять","v","She turned down the offer."],
["turn up","появляться; прибавлять","v","He turned up late."],
["work out","тренироваться; решать","v","I work out three times a week."],
["back up","делать резервную копию; поддерживать","v","Back up your files."],
["check out","проверять; выезжать из отеля","v","Check out this website."],
["count on","рассчитывать на","v","You can count on me."],
["end up","оказаться в итоге","v","We ended up staying home."],
["fill in","заполнять","v","Fill in this form."],
["go through","проходить через, просматривать","v","She went through a hard time."],
["hand in","сдавать (работу)","v","Hand in your essay by Friday."],
["let down","подводить","v","Do not let me down."],
["rely on","полагаться на","v","I rely on public transport."],
["stand for","означать; отстаивать","v","What does BBC stand for?"],
["drop out","бросать (учёбу)","v","He dropped out of college."],
["run into","случайно встретить","v","I ran into an old friend."],
["wear out","изнашивать(ся); выматывать","v","My shoes wore out."],
// Уровень 19 — наречия и связки
["accordingly","соответственно","adv","Plan accordingly."],
["additionally","дополнительно, кроме того","adv","Additionally, we need a budget."],
["alternatively","в качестве альтернативы","adv","Alternatively, we could go by train."],
["apparently","по-видимому","adv","Apparently, he has left."],
["approximately","приблизительно","adv","It costs approximately fifty dollars."],
["barely","едва","adv","I barely slept last night."],
["basically","в основном, по сути","adv","Basically, we agree."],
["consequently","следовательно","adv","He was late; consequently, he missed the train."],
["deliberately","намеренно","adv","He broke it deliberately."],
["eventually","в конце концов","adv","Eventually, we found the hotel."],
["extremely","чрезвычайно","adv","It is extremely cold."],
["fairly","довольно","adv","The test was fairly easy."],
["formerly","ранее, прежде","adv","The hotel was formerly a hospital."],
["frankly","откровенно говоря","adv","Frankly, I do not care."],
["frequently","часто","adv","He travels frequently."],
["furthermore","более того","adv","Furthermore, the price is too high."],
["gradually","постепенно","adv","The weather gradually improved."],
["hence","следовательно","adv","It rained; hence the delay."],
["increasingly","всё больше","adv","It is increasingly difficult."],
["indeed","действительно","adv","It was indeed a surprise."],
["inevitably","неизбежно","adv","Prices will inevitably rise."],
["initially","изначально","adv","Initially, the plan worked."],
["largely","в основном","adv","The success was largely due to luck."],
["likewise","аналогично","adv","She smiled, and he did likewise."],
["meanwhile","тем временем","adv","Meanwhile, the guests arrived."],
["merely","просто, всего лишь","adv","It is merely a suggestion."],
["moreover","более того","adv","Moreover, it is cheap."],
["nevertheless","тем не менее","adv","It was hard; nevertheless, we finished."],
["nonetheless","тем не менее","adv","The plan is risky; nonetheless, we will try."],
["notably","в особенности","adv","Many countries, notably Japan, agreed."],
["obviously","очевидно","adv","Obviously, he was wrong."],
["occasionally","время от времени","adv","I occasionally eat meat."],
["overall","в целом","adv","Overall, it was a good year."],
["particularly","особенно","adv","I particularly liked the ending."],
["partly","частично","adv","It is partly my fault."],
["presumably","предположительно","adv","Presumably, she knows."],
["previously","ранее","adv","He previously worked in banking."],
["primarily","главным образом","adv","The course is primarily for beginners."],
["rarely","редко","adv","I rarely watch TV."],
["regardless","несмотря ни на что","adv","We will go regardless of the weather."],
["relatively","относительно","adv","The test was relatively easy."],
["roughly","примерно, грубо","adv","There were roughly a hundred people."],
["seldom","редко","adv","He seldom complains."],
["significantly","значительно","adv","Sales rose significantly."],
["slightly","слегка","adv","It is slightly cheaper."],
["subsequently","впоследствии","adv","He subsequently moved to Spain."],
["thus","таким образом","adv","Thus, the project was cancelled."],
["ultimately","в конечном счёте","adv","Ultimately, it is your choice."],
["whereas","тогда как","conj","He likes tea, whereas I prefer coffee."],
["virtually","практически, фактически","adv","The city was virtually empty."],
// Уровень 20 — абстрактные понятия
["advantage","преимущество","n","Speed is the main advantage."],
["disadvantage","недостаток","n","The cost is a disadvantage."],
["aspect","аспект","n","Consider every aspect of the plan."],
["assumption","предположение","n","That is a dangerous assumption."],
["awareness","осведомлённость","n","The campaign raised awareness."],
["benefit","выгода, польза","n","Exercise has many benefits."],
["circumstance","обстоятельство","n","Under the circumstances, we agreed."],
["consequence","последствие","n","Every action has consequences."],
["context","контекст","n","Look at the word in context."],
["contribution","вклад","n","She made a big contribution."],
["criteria","критерии","n","What are the selection criteria?"],
["effect","эффект, влияние","n","The drug has a strong effect."],
["emphasis","акцент, упор","n","The emphasis is on speaking."],
["exception","исключение","n","There is one exception."],
["factor","фактор","n","Price is an important factor."],
["impact","воздействие","n","The impact was enormous."],
["implication","последствие, подтекст","n","What are the implications?"],
["influence","влияние; влиять","n","Parents have a strong influence."],
["insight","понимание, проницательность","n","The book gives insight into history."],
["issue","проблема, вопрос; выпуск","n","This is a serious issue."],
["likelihood","вероятность","n","There is a high likelihood of rain."],
["means","средство, способ","n","Email is a means of communication."],
["obstacle","препятствие","n","Money is the main obstacle."],
["opportunity","возможность","n","It is a great opportunity."],
["perspective","перспектива, точка зрения","n","Try to see it from my perspective."],
["potential","потенциал; потенциальный","n","She has great potential."],
["priority","приоритет","n","Safety is our priority."],
["procedure","процедура","n","Follow the procedure."],
["process","процесс","n","The process takes a week."],
["proportion","доля, соотношение","n","A large proportion of people agreed."],
["prospect","перспектива","n","The prospects are good."],
["range","диапазон, ассортимент","n","We offer a wide range of services."],
["scale","масштаб; шкала","n","The scale of the problem is huge."],
["scope","масштаб, рамки","n","This is beyond the scope of the report."],
["source","источник","n","What is the source of the information?"],
["strategy","стратегия","n","We need a new strategy."],
["tendency","тенденция, склонность","n","He has a tendency to exaggerate."],
["trend","тенденция, тренд","n","The trend is upwards."],
["variety","разнообразие","n","There is a variety of options."],
["notion","понятие, представление","n","I have no notion of what he means."],
["dilemma","дилемма","n","We face a dilemma."],
["compromise","компромисс","n","We reached a compromise."],
["commitment","обязательство, приверженность","n","It requires commitment."],
["consistency","последовательность","n","Consistency is the key to learning."],
["flexibility","гибкость","n","The job offers flexibility."],
["motivation","мотивация","n","Motivation is important for learning."],
["reputation","репутация","n","The firm has a good reputation."],
["stability","стабильность","n","People want stability."],
["transition","переход","n","The transition was smooth."],
["uncertainty","неопределённость","n","There is a lot of uncertainty."],
];
